### ISSUE TITLE
atrous_do not set in mask_low in Initial-Subtract.parset

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#10]
For the high-res masking we use

mask_high.argument.atrous_do                    =   True

For the mask_low this argument is not set, which defaults to False. Is there a specific reason why it is not se in mask_low ? (did it produce bad results ?)

**Comment by AHorneffer** [comment]
There doesn't seem to be a reason that it isn't set, so I also set it in mask_low.
