### ISSUE TITLE
pytables 3.3.0 not compatible?

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#102]
Hello,
I am not sure if this should be in the losoto github only or not, but here we go ...

While running prefactor it stopped due to errors in losotoimporter.py. I looked deeper into this and the actually error apparently occurs in h5parm.py.

Traceback (most recent call last):
File "scripts/losotoImporter.py", line 524, in
solset = parmDBs2h5parm(hdf5File, parmDBnames, antennaFile, fieldFile, skydbFile, compression=compression, solsetName=solsetName)
File "scripts/losotoImporter.py", line 139, in parmDBs2h5parm
h5parmDB = h5parm(h5parmName, readonly = False, complevel = compression)
File "/home/lofar/opt/lofar/lib64/python2.7/site-packages/losoto-0.4-py2.7.egg/losoto/h5parm.py", line 45, in init
self.H = tables.openFile(h5parmFile, filters=f, mode='w', IO_BUFFER_SIZE=1024_1024_10, BUFFER_TIMES=500)
AttributeError: 'module' object has no attribute 'openFile'

We have pytables (python-tables) 3.3.0 installed.

I checked the pytables website and apparently they changed the syntax, so openFile() is now open_file() and createTables() is now create_tables().

I then tried to simply replace them in h5parm.py but this lead to

WARNING:root:Appending to ./h5imp_cal_losoto.h5.
WARNING:root:Solution-set sol000 already present. Switching to default.
ERROR:node.slurm1.python_plugin:group /sol001 does not have a child named _f_getChild

So, I am not sure if changing is enough.

**Comment by AHorneffer** [comment]
This is a losoto issue. I see that you already asked this in [losoto #13](https://github.com/revoltek/losoto/issues/13) and it should be discussed there.
