### ISSUE TITLE
behaviour if all data flagged

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#118]
Not really much of an issue but if unflagged fraction is lower than threshold for all datasets the pipeline fails with a mapfile error as the check_unflagged_mapfile is empty. This is a bit awkward for sara processing when each 10 subband block is passed through a separate pipeline parset and usually the highest frequency one is nearly completely flagged. Easy for us to fix by just setting the unflagged fraction to 0 but if possible a nicer fix would be for the pipeline to end without going into an error state.

**Comment by AHorneffer** [comment]
Well, the pipeline wouldn't do much different, the only thing would be the error state with which the pipeline ends. (E.g. it won't generate any more output files or so.)
Implementing this is actually not trivial, so is this real problem or more a "nice to have".

**Comment by twshimwell** [comment]
Yeh I thought it may not be so simple unless the pipeline could be terminated in a successfully complete state from the check unflagged script itself but then gave a clear message that there was no unflagged data.

I think this falls more into the category of nice to have. If it ends in error state then its a bit painful for us having lots of tokens in that state as we either automatically reset them (which of course here just goes into an infinite loop) or manually go and confirm they are not errors.

We will just stick with our solution of setting the unflagged fraction to 0.0 for now.

I think you can close this ticket if you think something like this is more effort than it is worth and want to ignore it, its certainly a low priority (maybe most important for e.g. ingest where perhaps wouldn't want to archive completely flagged data)

**Comment by AHorneffer** [comment]
Why would you just re-start a pipeline that failed? Or in other words: what is the typical failure mode that can be fixed by just re-starting the pipeline?

A more fundamental question is probably: what do you want to do with bands that have next to no unflagged data? (Why the `*bleep*` would you **want** to keep them?)
And if you don't want to keep them, why process "10 subband blocks" with less than 5 input subbands in the first place?

**Comment by twshimwell** [comment]
Well generally our tokens go into error state just because of download issues from the LTA so its very frequent. It often downloads either non of the file or just part of the file then the pipeline fails due to the corrupt or non existing ms files.

Files with no data of course do not want to be kept. But having ~50% (or even 10%) of the data is arguably worth keeping. We could put a check in though for less than say 5subbands and that would solve the issue but maybe the even more fundamental question is that the concat step should not flag all the data in these 5subband (or 1subband) blocks which is the other ticket I posted earlier.
