### ISSUE TITLE
aoflagger behaviour

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#119]
In the prefactor concat step there are instances where e.g. a concat of 10 subbands worth of frequency coverage contains just 5 subbands and the others are missing (due to issues when the observation was taken or due to it being the highest frequency group of files). It seems that in these circumstances the aoflagger part of the concat step flags all the remaining data. I was just wondering how aoflagger deals with the dummy entries in the concat file… just checking it is treated ok and not used for e.g. determining statistics of what should be flagged?

**Comment by AHorneffer** [comment]
I just talked with Andre, and indeed the aoflagger will essentially ignore the flags, and will consider single subbands (with data) with data next to dummy subbands full of non-existent data to be RFI.
So if there are few real subbands in one band, there is a high likelihood that all data gets flagged.
