### ISSUE TITLE
calculate structure function from phases solutions of core stations of the target field

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#12]
It is very frequent that bad data survives all the way through the prefactor calibration pipeline and the subtract pipeline only to be identified quite a long time later when running factor. Maybe not simple to implement something robust but thought good to start a discussion about it here.

**Comment by rvweeren** [comment]
-1. First step would to be remove (entire) 10 SB blocks with ~50% data flagged. Andreas already did implement a similar thing in factor (using taql) so this should be quite easy.

-2. We need some python code, reading in the bandpass solutions and figuring out bad shapes. 
We can probably work on examples we have right now. There seem to be some common bad shapes which should not be too difficult to catch. (also by comparing bandpass rms we can remove "noisy" stations). Since we should have many of these npy (numpy arrays) (from pre factor runs) around now files we can start testing this. 

- 3. We need to think about scintillation on the target field. Maybe we need to image a single 10 SB in steps of 5 min determine rms (or some other useful quantity) to find bad time periods. WSClean allowed you to make these "movies". I think you (Tim) did make these sort of time serie images before. The question is can this be made into some reliable method to find bad/scintillation data automatically? This will need experimenting.

(we do not have to aim to catch 100% of data bad stuff, even finding 80% of it would be a big improvement and save us many hrs of hunting down bad stuff)

**Comment by AHorneffer** [comment]
I already implemented 1) in v2.0-devel. 
But I won't have time to look into the other two suggestions for quite some time...

**Comment by rvweeren** [comment]
I think for 2) we can start with some simple python script reading from the npy files (before worrying about prefactor). Anyone should be able to help here. Maybe first we need examples of bad bandpasses. If we all dump some examples (npy files, with bad data) we can easily start testing it. Maybe add a page to the Leiden Surveys wiki ? Or maybe better a dropbox folder ?

**Comment by nudomarinero** [comment]
I will be happy to write a Python script for point 2. 
We will need the npy amplitude arrays with examples of different problems.

**Comment by AHorneffer** [comment]
The interpolation of flagged amplitudes in [amplitudes_losoto_3.py](https://github.com/lofar-astron/prefactor/blob/master/bin/amplitudes_losoto_3.py) is done in 1-d only along the frequency-axis. The reason for that is that I couldn't find a useful function in scipy to do that in the time I was willing to spend on that. So if anyone has a good idea how to do that better, that would also help. (And help with the issue in Factor: ["smoothing of amplitudes leaves high outliers"](https://github.com/lofar-astron/factor/issues/31) )

**Comment by twshimwell** [comment]
Do we have a place to put the npy arrays? Perhaps the blank fields telecon dropbox?

**Comment by rvweeren** [comment]
These are 60 MB files and all charged against our Dropbox disk quota (so if we share ~10 we take up 25% of the normal quota for everyone who shares this folder, not sure if people will be ok with that ?).

**Comment by nudomarinero** [comment]
You could share the links and I will add them to a public repository with the script. After that they can be deleted from Dropbox, Drive, etc.

**Comment by twshimwell** [comment]
Perhaps an issue is also that people have often removed their bad data from the calibrator and deleted the bad npy arrays (I have done this anyway for all the Tier-1 datasets). Perhaps it is worth generating more npy arrays from datasets run with no manual intervention (unless we have enough npy arrays generated this way).

**Comment by twshimwell** [comment]
(I could easily generate lots of npy arrays if required, it would just take a bit of time to stage the data again)

**Comment by twshimwell** [comment]
Hi Pepe, you still happy to have a look into point 2? I have prepared a few numpy files. Would you also like the instrument tables?

**Comment by twshimwell** [comment]
For 3) I do have something that already exists from a while ago which I can attempt to revive. This program chose a bright source in the field and made snapshot images, found the peak flux and position of the peak and attempted to say which data was bad. I never had a huge amount of success so I think this would need quite a bit of improving. 

Also, making snapshots of multiple sources would be very handy and monitoring their position changes would be good. We may then also be able to figure out which time periods have very poor phase conditions from the different movements of the sources of various separations and from that calculating a rough estimate of how many facets would be required or whether it is worth proceeding with facet calibration for that particular dataset.

**Comment by twshimwell** [comment]
For 2) I have put some files (instrument tables, npy arrays, diagnostic plots untar with tar -zxvf) for 10 3c295 calibrator observations from cycle 3 in my dropbox so they can be downloaded, the links are below. No antennas besides CS013* have been flagged so hopefully this is a good set to test automatic removal of bad data.

https://www.dropbox.com/s/v0rt6sujyq5rkye/Prefacet-L232873-cal.tar.gz?dl=0
https://www.dropbox.com/s/7g79dby5iy5iqdu/Prefacet-L276352-cal.tar.gz?dl=0
https://www.dropbox.com/s/drfrzu9qr4vx5zp/Prefacet-L324994-cal.tar.gz?dl=0
https://www.dropbox.com/s/xq0ic6zabj4do77/Prefacet-L343262-cal.tar.gz?dl=0
https://www.dropbox.com/s/xq0ic6zabj4do77/Prefacet-L343262-cal.tar.gz?dl=0
https://www.dropbox.com/s/0ztt7mxzy5ze18y/Prefacet-L341702-cal.tar.gz?dl=0
https://www.dropbox.com/s/tzb8ysv0amgoy1v/Prefacet-L337634-cal.tar.gz?dl=0
https://www.dropbox.com/s/s3uqvannxke9k1j/Prefacet-L340800-cal.tar.gz?dl=0
https://www.dropbox.com/s/m1td80p3n77nyql/Prefacet-L343234-cal.tar.gz?dl=0
https://www.dropbox.com/s/0rb42mysqhmodko/Prefacet-L340814-cal.tar.gz?dl=0
https://www.dropbox.com/s/ikvaxpso4hu8h8l/Prefacet-L276262-cal.tar.gz?dl=0

**Comment by twshimwell** [comment]
To remove time periods where the phase is a bit crazy Leah and myself wrote some code for losoto which identifies periods where the phase is noisy. In this code the flagging is done by looking at phase solutions for all core stations (could also be done on remote stations if the phase could be unwrapped) and their nearest station. Then the data is smoothed a bit. The smoothed phase solutions and subtracted from the solutions and the flagging is done on the rms of the residual and also relies on seeing bad data on a given number of baselines. Attached is an example plot which shows the phase solutions (blue), the phase solutions identified for flagging (red) and the phase solutions minus the smoothed phase solutions (green -- these are used to identify which points for flagging).
![p10-cs401hba1-cs032hba1](https://cloud.githubusercontent.com/assets/12065270/14884157/31201ae8-0d43-11e6-9c0d-68ebf5f851dd.png)

Bad points of course are that if you don't have a lot of flux your phase solutions will naturally be noise. Also, if you have a very dominant source your phase solutions will essentially be close to direction dependent solutions.

**Comment by twshimwell** [comment]
so if people think that might be useful we could probably quite easily incorporate it into the normal version of losoto and use it in prefactor.

**Comment by rvweeren** [comment]
Looks nice! Would probably catch some of the scintillation events (I would stick with the core stations because we know that our skymodels are good at these low resolutions, for the RS stations bad phases could also indicate problems with the skymodel). This method flags on an antenna per antenna basis or the flags propagate to all stations? Reading from you description of how this works I presume the latter, that would also make more sense because in general you would attribute the wild phases to bad ionospheric conditions.

If implemented it is crucial to generate a figure like you show so the user sees what was flagged.

**Comment by twshimwell** [comment]
The flags propagate to all stations so its just time slots that are flagged.

I have tested it for about 65 pointings from the Tier-1 survey. For about 62 pointings it seemed to work pretty well. The other few pointings I thought it flagged too much data but probably related to tuning the parameters a little (because it presently uses just a value for the rms to exceed and flags based on this -- I had more success with this approach then attempting to dtermine some flagging threshold from the solutions themselves).

I'll have a go getting the routine (and the plotting bit) into the standard losoto so it can be tested more.

**Comment by twshimwell** [comment]
Francesco put this into losoto (its in the git repository) and its working pretty well. Below is a comparison between the results me and Leah were getting with our code on the left (ignore squares) and the ones we are now getting in losoto. 

Would still be nice to implement the referencing to the closest antenna in losoto but it seems to be working quite well just using CS001HBA0 are the moment.

The flagging parset and the flagextend parsets I used are pasted below and could probably be more tuned but perhaps worth waiting for the reference antenna select to allow us to choose the closest antenna first.

LoSoTo.Steps = [flag]
LoSoTo.Solset = [sol000]
LoSoTo.Soltab = [sol000/phase000]
LoSoTo.SolType = [phase]
LoSoTo.ant = CS*
LoSoTo.pol = [XX,YY]
LoSoTo.Steps.flag.Operation = FLAG
LoSoTo.Steps.flag.Mode = smooth
LoSoTo.Steps.flag.Order = 5
LoSoTo.Steps.flag.ant = []
LoSoTo.Steps.flag.Cycles = 1
LoSoTo.Steps.flag.FixRms = 0.012
LoSoTo.Steps.flag.PlotFlag = True
LoSoTo.Steps.flag.Reference = CS001HBA0

LoSoTo.Steps = [flagextend]
LoSoTo.Solset = [sol000]
LoSoTo.Soltab = [sol000/phase000]
LoSoTo.SolType = [phase]
LoSoTo.pol = [XX,YY]
LoSoTo.Steps.flagextend.Operation = FLAGEXTEND
LoSoTo.Steps.flagextend.Axes = [ant]
LoSoTo.Steps.flagextend.Percent = 10
LoSoTo.Steps.flagextend.Size = [0]
LoSoTo.Steps.flagextend.Cycles = 1




<img width="1125" alt="screen shot 2016-05-11 at 4 48 17 pm" src="https://cloud.githubusercontent.com/assets/12065270/15185267/b39b8782-1798-11e6-9d3c-53b7a8c5c9af.png">

**Comment by twshimwell** [comment]
This agrees well with source position variations that can be measured from snapshot images. Below the plot shows the 4>3Jy sources in the field and their position changes in ~1min snapshot images RA (top) and DEC (bottom) with respect to an 8hr image where I have offset the different sources by 50arcsec on the y-axis for clarity. Also, the time axis is a bit different from previously (before it was for every 4x8 second samples whereas here it is for every ~8x8sec sample). Maaijke is going to help me further interpret these measurements but even these very simple plots look quite promising (although much more time consuming than looking at the phase solutions)

![brightsource-ra-movement](https://cloud.githubusercontent.com/assets/12065270/15243642/26627e64-18fd-11e6-8ea3-5a6702661d9e.png)
![brightsource-dec-movement](https://cloud.githubusercontent.com/assets/12065270/15243635/21120ea2-18fd-11e6-9889-b390cf167fc0.png)

**Comment by twshimwell** [comment]
Using a code from Maaijke we can now use the phase solutions of the core antennas to calculate the structure function and output the diffractive scale. I added some recognition and removal of bad measurements (the points above the grey line are "bad") and the plots look ok (see attached where the x axis is the baseline distance and y axis is the variance on the phase solutions -- like figure 7 or 8 of the paper by Maaijke). 

The diffractive scale (bottom plots) for the 63 HETDEX pointings is shown against rms and against integrated/peak flux ratio. Each pointing has ~20 points due to the calculations being done on each 12sb chunk. The observations I previously identified as bad (using integrated/peak flux ration) are shown in red and the other pointings are shown in green. It seems that the structure function indeed identifies these pointings as pretty bad but also some others which I previously deemed ok (by integrated/peak flux measurements of compact sources) are equally bad.

I think it is good to put this structure function code into the prefactor pipeline tomorrow. It can just be run on the phase calibrated target measurement sets and the diagnostic plots can be produced and the diffractive scale can be written to a text file.

![p1-pipeline-l241959_sb167_uv dppp ms ndppp ndppp ndppp-ionosphere](https://cloud.githubusercontent.com/assets/12065270/16957236/dc8a3dd6-4ddb-11e6-8895-c84201d63f75.png)

![p7-pipeline-l231175_sb121_uv dppp ms ndppp ndppp ndppp-ionosphere](https://cloud.githubusercontent.com/assets/12065270/16957253/f0f9433e-4ddb-11e6-8a35-bc3d146368f7.png)

<img width="993" alt="screen shot 2016-07-19 at 6 14 47 pm" src="https://cloud.githubusercontent.com/assets/12065270/16957493/d29e2976-4ddc-11e6-88d9-3871a6ce40cf.png">
<img width="571" alt="screen shot 2016-07-19 at 6 13 52 pm" src="https://cloud.githubusercontent.com/assets/12065270/16957494/d2a19868-4ddc-11e6-8a44-961796ff7b6a.png">

**Comment by twshimwell** [comment]
(note that the comparison is not entirely fair because when calculating the integrated/peak flux or the rms measurement I did some flagging of bad phases using the scripts described above).

**Comment by twshimwell** [comment]
There is now a new branch called structurefunction which should produce these plots and a text file containing the diffractive scale (which is the number surrounded by stars). It is not tested in the pipeline framework so let me know if it runs fine or if you have issues*


Not certain what is a good value for the diffractive scale to be above. I think perhaps if it is below ~5000 (low is bad high is good) then maybe it is worth worrying a little about the ionospheric conditions but hopefully having it in the pipeline and it being used will help us understand how this corresponds to e.g. whether we stand much chance at facet calibrating the data.

**Comment by soumyajitmandal** [comment]
I have tested this branch and this is working. The diagnostic plots are really useful and we can have an idea about the ionospheric condition. For example, I have tested this for the worst ionospheric conditions and the diffractive scales are at the order of ~ 2 km.

**Comment by AHorneffer** [comment]
I merged the v2.0 code into the structurefunction branch. I think it should work, but I would appreciate if someone could test it before I merge it into the "release candidate"(*) branch.

(*) Which is what the v2.0-devel branch now is.

**Comment by twshimwell** [comment]
Nice. I guess the structure function branch can now be removed then.

Also, is there any demand for this automatic phase flagging in losoto that is discussed on this page? If so we can also try to put that in for release 2.0. If not perhaps this ticket is done and we can start a fresh and more specific ticket with automatically identifying bad calibrator data.

**Comment by AHorneffer** [comment]
Please start a new ticket for the automatic phase flagging.

I haven't merged the structure function code into the "release candidate" branch! Please test the current structurefunction branch. If that actually works, then we can merge that and remove the structurefunction branch.

**Comment by AHorneffer** [comment]
Included in branch v2.0-devel now.
