### ISSUE TITLE
Add frequency dependence in getstructure_from_phases script

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#122]
Currently there is no frequency dependence in this script. Maaijke mentions that one can calculate the diffractive scale always at the same frequency to more easily compare observations. This can be done at e.g. 150MHz by converting the phase variance to phase variance at 150MHz before fitting, with

var(ph_150MHz)=var(ph_f1)*(f1/150MHz)^2

**Comment by adrabent** [comment]
[LINC](https://git.astron.nl/RD/LINC/) now uses STRUCTURE operation of [LoSoTo](https://github.com/revoltek/losoto).
