### ISSUE TITLE
make_clean_mask.py fails in pipeline, but not when started alone

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#130]
Hi,

I started the initial subtract pipeline, which at somepoints stops because of an error. After looking through the log file, I found this:

> 2017-04-19 15:03:06 DEBUG   genericpipeline.executable_args: Remote command stdout: --> Opened '/aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.fits'
> Image size .............................. : (5600, 5600) pixels
> Number of channels ...................... : 1
> Number of Stokes parameters ............. : 1
> Beam shape (major, minor, pos angle) .... : (1.19263e-02, 8.69511e-03, 24.5) degrees
> Frequency of image ...................... : 149.315 MHz
> Number of blank pixels .................. : 0 (0.0%)
> Flux from sum of (non-blank) pixels ..... : 0.136 Jy
> --> Calculating background rms and mean images
> --> Using adaptive scaling of rms_box
> Using user-specified rms_box ............ : (60, 20) pixels (small scale)
> Using user-specified rms_box ............ : (60, 20) pixels (large scale)
> --> Using 2D map for background rms
> --> Using constant background mean
> Min/max values of background rms map .... : (0.00058, 0.00136) Jy/beam
> Value of background mean ................ : 0.0 Jy/beam
> Minimum number of pixels per island ..... : 9
> Number of islands found ................. : 0
> WARNING: No islands found. Skipping wavelet decomposition.
> --> Grouping Gaussians into sources
> Number of sources formed from Gaussians   : 0
> No islands found. Clean mask cannot be made.
> 
> 2017-04-19 15:03:06 ERROR   genericpipeline.executable_args: Remote process python /aux/lofar/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py ['/aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.fits', '/aux/lofar/opt/prefactor/scripts/make_clean_mask.py', ['/aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.fits', '/aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.mask_high'], {'threshpix': '5.0', 'atrous_jmax': '3', 'adaptive_rmsbox': 'True', 'trim_by': '0.1', 'atrous_do': 'True', 'threshisl': '3.0', 'rmsbox': '(60,20)', 'img_format': 'fits'}, '/aux/amisk/N3432/Target/results/work/Initial-Subtract', False, {'args_format_option_argument': '=', 'args_format_option': '-', 'args_format': 'gnu', 'args_formatlongoption': '--', 'args_format_argument': ''}, {'JAVA_ROOT': '/usr/lib64/jvm/java', 'LOFARDATAROOT': '/opt/lofar/data', 'PYTHONPATH': ':/aux/lofar/opt/lofar/lib64/python2.7/site-packages::::::::::/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/:/aux/lofar/opt/python-casacore/lib/python2.7/site-packages/', 'ALSA_CONFIG_PATH': '/etc/alsa-pulse.conf', 'LOFARROOT': '/aux/lofar/opt/lofar', 'MANPATH': '/usr/lib64/mpi/gcc/openmpi/share/man:/usr/share/man:/usr/local/man:/usr/man', 'PATH': '::/aux/lofar/opt/lofar/bin:/aux/lofar/opt/lofar/sbin:::::::::::/usr/lib64/mpi/gcc/openmpi/bin:/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/home/muse_pipeline/bin:/usr/lib64/mpi/gcc/openmpi/bin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/aux/lofar/opt/casacore/bin:/home/muse_pipeline/bin:/usr/lib64/mpi/gcc/openmpi/bin', 'XNLSPATH': '/usr/share/X11/nls', 'LD_LIBRARY_PATH': ':/aux/lofar/opt/lofar/lib64::::::::::/usr/lib64/mpi/gcc/openmpi/lib64:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib:/aux/lofar/opt/casacore/lib'}] failed on slurm10 (status: 1)
> 

But if I start make_clean_mask.py with the exact same arguments,
`python /aux/lofar/opt/prefactor/scripts/make_clean_mask.py /aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.fits /aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.mask_high -p 5.0 -j 3 -o True -b 0.1 -i 3.0 -r "(60,20)" -f fits -a True
`
 it does find sources and it seems to work as it should.

Do you have any ideas why that would be the case?

**Comment by AHorneffer** [comment]
My guess is that the environment is different when starting `make_clean_mask.py` from the pipeline and when starting it by hand. 

> Flux from sum of (non-blank) pixels ..... : 0.136 Jy

That looks incredible low!
What is the output when you run it by hand?

**Comment by amisk** [comment]
This the result of starting it by hand:
--> Opened '/aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.fits'
Image size .............................. : (5600, 5600) pixels
Number of channels ...................... : 1
Number of Stokes parameters ............. : 1
Beam shape (major, minor, pos angle) .... : (1.19263e-02, 8.69511e-03, 24.5) degrees
Frequency of image ...................... : 149.315 MHz
Number of blank pixels .................. : 0 (0.0%)
Flux from sum of (non-blank) pixels ..... : 0.136 Jy
--> Calculating background rms and mean images
--> Using adaptive scaling of rms_box
Using user-specified rms_box ............ : (60, 20) pixels (small scale)
Using user-specified rms_box ............ : (60, 20) pixels (large scale)
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.00058, 0.00136) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Minimum number of pixels per island ..... : 9
Number of islands found ................. : 3
Total number of Gaussians fit to image .. : 3
Total flux density in model ............. : 0.012 Jy
WARNING: Total flux density in model is 0.09 times sum of pixels in input image. Large residuals may remain.

--> Wavelet scale #1
--> Calculating background rms and mean images
Using user-specified rms_box ............ : (60, 20) pixels
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.00042, 0.00112) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Number of islands found ................. : 7
Total number of Gaussians fit to image .. : 6
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 6

--> Wavelet scale #2
--> Calculating background rms and mean images
Using user-specified rms_box ............ : (60, 20) pixels
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.00024, 0.00085) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Number of islands found ................. : 6
Total number of Gaussians fit to image .. : 5
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 5

--> Wavelet scale #3
--> Calculating background rms and mean images
Using user-specified rms_box ............ : (85, 28) pixels
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.00016, 0.00054) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Number of islands found ................. : 1
Total number of Gaussians fit to image .. : 1
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 1
Total flux density in model on all scales : 0.142 Jy
--> Grouping Gaussians into sources
Number of sources formed from Gaussians   : 15
WARNING: Telescope is unknown. Mask may not work correctly in CASA.
--> Wrote file '/aux/amisk/N3432/Target/results/work/Initial-Subtract/L192987_SAP000_SB000_uv_123A9A30Dt_149MHz.pre-cal.wsclean_high1-image.mask_high'
{'multiscale': True, 'threshold_5sig': 0.0008441701144173658}

I checked the logs of the other pybdsm results, and the flux is always that low.

**Comment by amisk** [comment]
Something might be really wrong ... the fits files are empty... they basically only show the background ...
![empty](https://cloud.githubusercontent.com/assets/19927617/25232726/b4b9f5c4-25dc-11e7-9748-ad813f48a4c4.jpg)

**Comment by AHorneffer** [comment]
Looks like the calibration went wrong, i.e. the Pre-Facet-Target pipeline.

Did you have a decent model of the field for the phase only calibration in the target pipeline?
