### ISSUE TITLE
Feature request: check for existing images before remaking in init-subtract

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/prefactor#132]
I was running the init-subtract pipeline on CEP3.  It was on the first high-res imaging step and had taken ~1.5 weeks to get through ~1/2 of the images (single node) when CEP3 shut down for a stop day.  Since the step hadn't completed, it wasn't written to the statefile.  When I tried to restart the pipeline after the stop day, it started back at the top of the list of high res images to make.  
It would be very helpful if the pipeline could check the working directory for existing images with the exact same filenames and skip those that have already been made to avoid remaking identical images.  Perhaps there could be a 'no-clobber' option in the parset.  I realize that the fast version of init-subtract will make rerunning the pipeline somewhat less painful in terms of time, but it would still be nice if existing images weren't ignored/overwritten.  Losing 10 days of runtime is definitely painful...

**Comment by AHorneffer** [comment]
Have a look at the [Initial-Subtract-Fast.parset](https://github.com/lofar-astron/prefactor/blob/experimental/Initial-Subtract-Fast.parset) on the [experimental](https://github.com/lofar-astron/prefactor/tree/experimental) branch, this will mitigate the issue. (Possibly at the expense of the quality of the model that is subtracted.)

About the actual request: I don't believe that I'll find time for that before my contract runs out.
