### ISSUE TITLE
Use wsclean automasking and save-source-list

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/prefactor#136]
Hi,

maybe it would be helpful to use the new Auto-Masking feature of wsclean (available since version 2.2) in order to streamline the pipeline (less steps necessary), get rid of the two cleaning steps (high1/high2/low1/low2) and to save time.

You can even use the -save-source-list step (since v2.4). Then you only need to convert the skymodel to a sourcedb and no run of pyBDSF is neccessary anymore.

Cheers,
Alexander

**Comment by darafferty** [comment]
Even with auto masking, we might still want to run PyBDSF to further limit the number of artifacts that get included in the model. So, just one imaging run per resolution (using auto masking), followed by a masking step that filters the source list generated by WSClean (this is what Factor currently does for the shallow facet imaging at the end of selfcal).

**Comment by darafferty** [comment]
I've added auto masking to Initial-Subtract-Fast on the experimental branch. It helps a lot in avoiding artifacts in the models around bright sources (left is model from normal run, right is with auto masking):
<img width="731" alt="screen shot 2017-09-06 at 07 54 57" src="https://user-images.githubusercontent.com/5547918/30096615-b2fb8cc4-92d9-11e7-8704-c33a040650a5.png">
PyBDSF is still run after imaging, as it requires little time relative to the other steps, but perhaps it isn't needed after all...

**Comment by adrabent** [comment]
This looks promising.
Have you already tried the -save-source-list option? So you might be able to skip all the steps until make_sourcedb_high.

**Comment by darafferty** [comment]
No, but we're not using wide-band cleaning and only using the delta scale, so the advantages of using -save-source-list are sort of negated.
