### ISSUE TITLE
sort_times_into_freqGroups.py issue with combining all subbands

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#137]
The script sort_times_into_freqGroups.py says that with numSB=-1 all files should be concatenated together, but this isn't the case.  I added a couple lines to the attached script that seem to do the trick.  Is it possible to have this updated?
[sort_times_into_freqGroups.py.txt](https://github.com/lofar-astron/prefactor/files/1115523/sort_times_into_freqGroups.py.txt)

**Comment by tammojan** [comment]
Hi Leah; I converted your change into a pull request so that merging it becomes a matter of clicking a green button. @AHorneffer  can you click the button if appropriate?

**Comment by lmorabit** [comment]
thanks!

**Comment by AHorneffer** [comment]
Ah, yes. When implementing the fix for #101 I didn't think about that.
