### ISSUE TITLE
All jobs failed error

### ISSUE THREAD

**Issue by mamtz** [lofar-astron/prefactor#140]
Hello,
I was trying to run prefactor on CEP3 and all was working well, until I got the following error message:

ERROR   node.lof021.control.lofar.executable_args: Command '/home/moutzouri/prefactor-master/scripts/fit_clocktec_initialguess_losoto.py' returned non-zero exit status 1
INFO    node.lof021.control.lofar.executable_args: Total time 2.4657s; user time: 2.6818s; system time: 0.2722s
DEBUG   node.lof021.control.lofar.executable_args: Start time was 1505232185.0144s; end time was 1505232187.4802s
DEBUG   genericpipeline.executable_args: Adding node_logging_information
ERROR   genericpipeline.executable_args: All jobs failed. Bailing out!
WARNING genericpipeline.executable_args: Note: recipe outputs are not complete
WARNING genericpipeline.executable_args: recipe executable_args completed with errors
WARNING genericpipeline: executable_args reports failure (using executable_args recipe)
ERROR   genericpipeline: *******************************************
ERROR   genericpipeline: Failed pipeline run: 3C380_L547733
ERROR   genericpipeline: Detailed exception information:
ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
ERROR   genericpipeline: executable_args failed
ERROR   genericpipeline: *******************************************

I don't really get what has gone wrong. Any help?

**Comment by AHorneffer** [comment]
The `fit_clocktec_initialguess_losoto.py` script failed. Without the logfile that's all that I can say.

Have a look at the [Usage Documentation](https://github.com/lofar-astron/prefactor/wiki/Documentation%3A-Usage), in particular the parts about "Pipeline crashes" and "Getting help with errors". I suggest that you attach the logfile to the github issue here.

**Comment by mamtz** [comment]
I am attaching the log file now. I couldn't figure out anything from the documentation.
[pipeline.log.txt](https://github.com/lofar-astron/prefactor/files/1296670/pipeline.log.txt)

**Comment by twshimwell** [comment]
Seems to be:

    import progressbar
ImportError: No module named progressbar

**Comment by twshimwell** [comment]
If you cant get the progressbar library. I was told that there were two scripts in the Prefactor GitHub repository that tried to import progressbar and a workaround is to make the following changes to these:

try:
    import progressbar
except ImportError:
    import losoto.progressbar as progressbar

and comment 

#import progressbar

**Comment by AHorneffer** [comment]
@mamtz mamtz: The documentation says that you should include the full log file with debug output when reporting an error. 

I guess @twshimwell found your problem. 

Do you have any idea where all that BBS output in the logfile is coming from?

**Comment by mamtz** [comment]
@twshimwell @AHorneffer  looks like it is working now. I had indeed to apply this to amplitudes_losoto_3.py as well.

@AHorneffer I don't know. I had to get the log file from the working_directory I have assigned for the results. Maybe that is why?

I will try and close the ticket.
