### ISSUE TITLE
KeyError 'mapfile' but input is ok

### ISSUE THREAD

**Issue by mamtz** [lofar-astron/prefactor#142]
I am running the pipeline for the target this time and I am getting a KeyError 'mapfile'. I checked the input path and pattern as advised, but I don't see where the problem could be. I am attaching the full log as well.
[log.txt](https://github.com/lofar-astron/prefactor/files/1306845/log.txt)

**Comment by twshimwell** [comment]
I think what is happening is that the check_unflagged script is removing all of your files. 

You are just giving it from 0-10SB around 110MHz? If so perhaps try giving data in the range 120-168MHz where the RFI situation is a bit better as maybe less will get flagged.

**Comment by twshimwell** [comment]
(or you could try changing the tolerance on the check unflagged fraction -- presently i think it says about 70% of this data chunk are flagged).

**Comment by mamtz** [comment]
@twshimwell I tried changing the tolerance to 20% (it was 50%) and rerun it, same. I tried giving higher subbands, same. Here is the new log file. Could it be the flagging strategy is wrong? I am using the one from the cookbook tutorial (~offringa/tutorials/aoflagger-tutorial.rfis). 

[new_log.txt](https://github.com/lofar-astron/prefactor/files/1307056/new_log.txt)

**Comment by twshimwell** [comment]
I normally use one called hbadefault that flags on XY and YX. It should be in your lofar build (maybe in a folder like release/share/rfistrategies/).

In the log though it seems to suggest no flagging is done at this point by aoflagger. 

The ateam clipper log though does seem to be flagging quite a lot of your data.

SB Frequency [MHz] 131.640625
chan 0 : 0.00000% input XX flagged
chan 0 : 0.00000% input YY flagged
chan 1 : 0.00000% input XX flagged
chan 1 : 0.00000% input YY flagged
chan 2 : 0.00000% input XX flagged
chan 2 : 0.00000% input YY flagged
chan 3 : 0.00000% input XX flagged
chan 3 : 0.00000% input YY flagged
Total : 0.00000% input XX flagged
Total : 0.00000% input YY flagged

Cliplevel used [Jy] 5.0



Doing polarization,chan 0 0
Doing polarization,chan 0 1
Doing polarization,chan 0 2
Doing polarization,chan 0 3
Doing polarization,chan 1 0
Doing polarization,chan 1 1
Doing polarization,chan 1 2
Doing polarization,chan 1 3
Doing polarization,chan 2 0
Doing polarization,chan 2 1
Doing polarization,chan 2 2
Doing polarization,chan 2 3
Doing polarization,chan 3 0
Doing polarization,chan 3 1
Doing polarization,chan 3 2
Doing polarization,chan 3 3

chan 0 : 99.15812% output XX flagged
chan 0 : 99.15812% output YY flagged
chan 1 : 99.16460% output XX flagged
chan 1 : 99.16460% output YY flagged
chan 2 : 99.16343% output XX flagged
chan 2 : 99.16343% output YY flagged
chan 3 : 99.16107% output XX flagged
chan 3 : 99.16107% output YY flagged
Total : 99.16181% output XX flagged
Total : 99.16181% output YY flagged

perhaps your source is very close to one of the ateam sources?

**Comment by mamtz** [comment]
@twshimwell I believe it was this set of data that were causing the issue. I tried to rerun the pipeline for the whole set and I didn't get THIS error. I got an other one (it never ends), but I might open a new ticket...
