### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/prefactor#146]
It looks like this repository is missing license information

**Comment by AHorneffer** [comment]
Yes. Use prefactor at your own risk of being sued by the hordes of LOFAR lawyers! 

Yes, I'm serious. That's what the current license says: you don't really have a license to do anything with the code. That also means that I don't have a license to just slap a GPL onto it.

**Comment by mhardcastle** [comment]
As requested by Andreas: licensing under the GPL is fine by me.

**Comment by nudomarinero** [comment]
Any GPL is fine by me

**Comment by AHorneffer** [comment]
I guess that'll allow us to put prefactor under GPL soon:

> From: Andreas Horneffer <*beep*>
> To: Tammo Jan Dijkema <*beep*>, Martin Hardcastle <*beep*>, George Heald <*beep*>, Soumyajit Mandal <*beep*>, David Rafferty <*beep*>, Carole Roskowinski <*beep*>, Jose Sabater Montes <*beep*>, Timothy Shimwell <*beep*>, Sarrvesh Sridhar <*beep*>, Reinout van Weeren <*beep*>, "Williams, Wendy" <*beep*>, Yan Grange <*beep*>, Joshua George Albert <*beep*>, =?UTF-8?Q?Marta_Dzie=c5=82ak?= <*beep*>
> Subject: License for prefactor
> Date: Fri, 20 Oct 2017 15:31:55 +0200
> 
>     Hi
> 
> According to my list you have in some way or another contributed intellectual
> property to prefactor. I'd like to put all of prefactor under the GPL to
> eliminate the risk of anyone suing anyone else for copyright infringement.
> 
> I'd appreciate if you could state on:
>   https://github.com/lofar-astron/prefactor/issues/146
> that this is fine with you.
> 
> If you do not agree then please inform the maintainer of prefactor(*) of the
> fact and let him or her know which parts of prefactor contain your intellectual
> property.
> 
> (*) That may or may not be me.
> 
>   Greetings, Andreas
>

**Comment by twshimwell** [comment]
Fine by me too.

**Comment by wllwen007** [comment]
Yes, fine with me

**Comment by tammojan** [comment]
Fine with me.

**Comment by ygrange** [comment]
I'm ok with the current and any future change of the licensing of prefactor.

**Comment by soumyajitmandal** [comment]
Fine with me.

**Comment by gijzelaerr** [comment]
If parts of prefactor are going to be used as module or as library for/in other projects I recommend LGPL:

https://opensource.org/licenses/lgpl-license

otherwise the linking software needs to be GPL also.

**Comment by gijzelaerr** [comment]
or something more liberal like MIT or BSD.

**Comment by AHorneffer** [comment]
Well, the LOFAR software is GPL so I guess we need GPL, too.

**Comment by nudomarinero** [comment]
I suppose that it is possible to use the GPL for any code that links to the LOFAR libraries and a less restrictive one to the code that does not (if there is any).

**Comment by gheald** [comment]
Licensing is fine with me, whichever method is most appropriate.

**Comment by gijzelaerr** [comment]
re: I suppose that it is possible to use the GPL for any code that links to the LOFAR libraries and a less restrictive one to the code that does not (if there is any).

but what about if you combine prefactor with existing software that has no GPL license? Then you need to relicense the existing software. GPL is actually quite restrictive in these things.

**Comment by nudomarinero** [comment]
I did not explain myself very well. I meant that most of the prefactor code links to LOFAR libraries or python-casacore libraries that are released under the GPL license. In this case all these prefactor code must be GPL. However there are some scripts that do not link to those libraries and could be released with a different, less restrictive license in case anyone would like to reuse them.

In this case, if prefactor is combined with other software I suppose there are several options:

- If it is called but not linked from the other software (for example using subprocess.call), the license of the other software is not affected.
- If some of the prefactor GPL code is linked, the other software should be distributed as GPL.
- If some of the prefactor non-GPL code is linked, the license of the other software depends on the license chosen but with an LGPL or MIT license is should not affect it.

I always prefer MIT or BSD and perhaps LGPL but, given that most of prefactor must be released as GPL, I do not know if it makes sense to use a less restrictive license for the pieces of code that are not constrained by the GPL "virality".

**Comment by mhardcastle** [comment]
I can't imagine that there is much requirement to 'link to' prefactor rather than just running it. So I don't see any downside to GPL for the whole of prefactor in this case.

**Comment by ygrange** [comment]
It also depends on how much we (you, since I just transfered the right to chose the license to the maintainer) expect external (commercial) parties to be interested in the prefactor code too.

**Comment by carosko** [comment]
(GPL is fine with me too)

**Comment by AHorneffer** [comment]
IMHO the discussion of GPL vs. LGPL / MIT / BSD is a moot point. prefator is not a library that can easily be linked against, but a pipeline implementation. So normal users just run it, or modify it for their purpose and then run it. If these modifications are just used locally by the respective user then GPL doesn't keep anyone from doing that. And I'd prefer if any modifications that might be of more general interest wind up in the general prefactor code. So requiring modifications that are distributed are also distributed under GPL is IMHO a good thing. Thus code that was written by me should also be under GPL.

Feel free to look through the code for stuff that does not link to libraries under GPL or that was written by me.

P.S. If someone can find a good use for prefactor code that would have a problem with the GPL, they are free to contact the authors for a copy under a less restrictive license.
