### ISSUE TITLE
Problem with getStructure_from_phases.py failing

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#147]
I was having trouble with the getStructure_from_phases.py script, which boiled down to the following python error:

dphx=phx[:,np.newaxis,tm[0]:tm[1]]-phx[np.newaxis,:,tm[0]:tm[1]]
TypeError: slice indices must be integers or None or have an __index__ method

The problem is that this happens in a loop over itime, which ranges over nr_grid+1.  when itime < nr_grid the values of tm are reset to integers; when itime = nr_grid then the values of tm are [0,1e9] as set on line 77.

Suggested fix (which worked for me):  on line 77 of getStructure_from_phases.py change tm=[0,1e9] to tm=[0,int(1e9)]

**Comment by AHorneffer** [comment]
Added the fix.

@twshimwell: Can you check the code if this really fixes the problem? The code looks to me like the 1e9 was never really supposed to be actually used, but I don't really understand how that part of the code is supposed to function.

**Comment by twshimwell** [comment]
Seems fine to me. I believe it is related to numpy 1.12.0 (https://docs.scipy.org/doc/numpy-1.12.0/release.html) which is a bit stricter on how you index arrays.
