### ISSUE TITLE
Remove flagged Stations

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#15]
Stations that are fully flagged, should be completely removed from the MSs to save disk space.

**Comment by twshimwell** [comment]
tammo to write taql command to find fully flagged stations. These can then be input into NDPPP and filter can be used to remove the stations.

**Comment by tammojan** [comment]
```
from casacore.tables import taql

### Find all antennas with more than 80% flagged data
t = taql("""
SELECT antname, gsum(numflagged) AS numflagged, gsum(numvis) AS numvis,
       gsum(numflagged)/gsum(numvis) as percflagged FROM
 [
   [ SELECT mscal.ant1name() AS antname, ntrue(FLAG) AS numflagged, count(FLAG) AS numvis FROM tim.MS ],
   [ SELECT mscal.ant2name() AS antname, ntrue(FLAG) AS numflagged, count(FLAG) AS numvis FROM tim.MS ]
 ] GROUP BY antname HAVING percflagged > 0.8
""")

flaggedants = [ row["antname"] for row in t ]
print(flaggedants)
```
This was actually an example on http://taql.astron.nl :) For totally flagged antennas, just replace the `> 0.8` with `==1`.

You can make this into a one-liner by removing the line endings :)
