### ISSUE TITLE
make scripts usable from command line?

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/prefactor#154]
Hi!

I'm trying to CWLify the prefactor pipeline. Part of the pipeline is a bunch of Python plugins in `prefactor/scripts`. I think how this works is that the main function for plugins defined in a parset are called by `genericpipeline.py`. Is there a CLI wrapper for these scripts? If not, is it possible to modify these scripts so they also work from the CLI? Until now i've been the scripts return only simple things like a file path.

please let me know what you think.

**Comment by ygrange** [comment]
That'd be great! IIt would probably not add too much overhead but makes it much easier to use the scripts from a different workflow/pipeline management system...

**Comment by adrabent** [comment]
Most of the scripts can be run from the command line.
Are you aware of any script that does not work for you?

**Comment by ygrange** [comment]
Let me dig into my memory (the issue is a bit long ago to freshly remember) I think the main issue we had when trying it back then was `InitSubtract_sort_and_compute.py` and maybe `plot_image.py`. Maybe @gijzelaerr has a better memory than myself.

**Comment by adrabent** [comment]
The new version of prefactor allows all common scripts to be run from the commandline: https://git.astron.nl/eosc/prefactor3-cwl
