### ISSUE TITLE
Behaviour if anyenna missing from calibrator data

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#157]
Presently if the calibrator data doesnt have a core or a remote station that the target contains the pipeline fails (code from transfer_gains_RMextract.py pasted below). Perhaps we could just flag the antenna for these antennas using the transfer_gains_RMextract.py script instead of failing?

    # check if we have data for all target stations

    for antenna in msinfo.stations:

        if antenna not in station_names:

            if antenna[:2] == 'CS' or antenna[:2] == 'RS':

                # fail if it is a Dutch station

                print "Station %s not found in list of calibrator data!"%(antenna)

                raise ValueError("Station "+antenna+" missing in calibrator data!")

**Comment by adrabent** [comment]
This issue is already discussed here:
https://github.com/lofar-astron/prefactor/issues/185

Further discussions should be continued there.
