### ISSUE TITLE
initsub fast with wsclean 2.5

### ISSUE THREAD

**Issue by AnnalisaB** [lofar-astron/prefactor#163]
I am trying to run the initial subtraction fast pipeline using wslcean 2.5
I get the error:

Unknown parameter: paddedsize

2017-12-15 12:46:18 DEBUG   genericpipeline.executable_args: Results for job 1 submitted by R   

Should that be romoved/changed in the control.inputkeys?

Thanks,
Annalisa

**Comment by darafferty** [comment]
Yes, indeed they should be removed. I just committed a fix -- can you update and try it again?

**Comment by AnnalisaB** [comment]
Hi David, 

I get this now:

2017-12-15 14:11:53 ERROR   genericpipeline.executable_args: Exception caught: not enough arguments for format string
Traceback (most recent call last):
  File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/master/executable_args.py", line 306, in go
    len(self.inputs['inputkeys']), len(inputmapfiles))
TypeError: not enough arguments for format string

I suspect it is related to the same issue?

Thanks
Annalisa

**Comment by darafferty** [comment]
Strange -- I can't reproduce that error. Did you delete the pipeline output directory before restarting?

**Comment by AnnalisaB** [comment]
Yes, I did delete run and working directories

**Comment by darafferty** [comment]
I tried another run and had no problems (at least through the high-res imaging steps), so it might be something in your parset. Can you post it here or send it to me?

**Comment by AnnalisaB** [comment]
Thanks David, here is the parset (up to the wsclean_high step)

! data_input_path         = /data/abonafede/Z7215/DATA/prefactor/results
! data_input_pattern      = *.ms  
# name of the direction independent parmDBs inside the measurement sets
# needs to include the leading "/" to indicate that the parmDB is a subdirectory of the MS
! direction_indep_parmDBs = /instrument_directionindependent
# where to put the inspection plots generated by the pipeline
! inspection_directory = /data/abonafede/Z7215/INITSUB/INSPECTION
! local_scratch_dir        =  /data/abonafede/Z7215/INITSUB/SCRATCH



##### imaging parameters (Feel free to leave them untouched.)
#### specify  the image parameters here
# cellsize in degrees, 0.00208 deg is about 7.5 arcsec
! cellsize_highres_deg = 0.00208
! cellsize_lowres_deg  = 0.00694
# size of the image is this value times the FWHM of mean semi-major axis of the station beam
! fieldsize_highres    = 2.5
! fieldsize_lowres     = 6.5
# maximum uv-distance in lambda that will be used for imaging
# 7 klambda is machted to 7.5 arcsec cellsize
! maxlambda_highres    = 7000
! maxlambda_lowres     = 2000
# How much padding shall we add during the imaging?
! image_padding        = 1.4
# Number of bands to image (spread over the full bandwidth). Larger values
# result in better subtraction but longer runtimes
! nbands_image         = 6
# Minimum flux density in Jy of clean components from the high-resolution
# imaging to include in subtract_high step (note that all components from the
# low-resolution imaging are included in the subtract_low step). Clean
# components below this flux density will not be subtracted. Lower values result
# in better subtraction but longer runtimes
! min_flux_jy          = 0.005

##### performance parameters
! max_imagers_per_node      =  2
! max_percent_mem_per_img   =  45
! max_cpus_per_img          =  20
! max_dppp_per_node         =  6
! max_dppp_threads          =  8
# set this to True if you want the pipeline run to continue if single bands fail
! error_tolerance           =  False

##### pathes to the scripts etc.
! wsclean_executable          = /opt/wsclean/bin/wsclean
! do_magic_script             = /opt/prefactor/scripts/InitSubtract_sort_and_compute.py
! merge_skymodels_script      = /opt/prefactor/scripts/merge_skymodels.py
! make_clean_mask_script      = /opt/prefactor/scripts/make_clean_mask.py
! fits_to_casa_script         = /opt/prefactor/scripts/convert_fits_image_to_casa.py
! plot_subtract_images_script = /opt/prefactor/scripts/plot_subtract_images.py
! casapy2bbs                  = /opt/lofar/bin/casapy2bbs.py
! makesourcedb                = /opt/lofar/bin/makesourcedb

# the Steps in this pipeline
pipeline.steps = [create_ms_map, combine_mapfile, do_magic, do_magic_maps, create_parmdb_map, select_imaging_bands, select_high_size, select_high_nwavelengths, wsclean_high
, mask_high, mk_inspect_dir, copy_mask, plot_im_high, move_high, create_maxsize_high_map, pad_model_high, pad_mask_high, combine_model_high_mapfile, expand_model_high, comb
ine_mask_high_mapfile, expand_mask_high, fits_to_bbs_high, make_sourcedb_high, expand_sourcedb_high, subtract_high, select_correct_high_files, select_parmdb, select_freqste
p, select_timestep, correct_high, regroup_map, select_low_size, select_low_nwavelengths, wsclean_low, mask_low, plot_im_low, move_low, create_maxsize_low_map, pad_model_low
, pad_mask_low, combine_model_low_mapfile, expand_model_low, combine_mask_low_mapfile, expand_mask_low, fits_to_bbs_low, make_sourcedb_low, expand_sourcedb_low, subtract_lo
w, merge, copy_skymodels, createmap_plots, move_plots]

# create a mapfile with all MSs, length = nfiles
create_ms_map.control.kind                      =   plugin
create_ms_map.control.type                      =   createMapfile
create_ms_map.control.method                    =   mapfile_from_folder
create_ms_map.control.mapfile_dir               =   input.output.mapfile_dir
create_ms_map.control.filename                  =   create_ms_map.mapfile
create_ms_map.control.folder                    =   {{ data_input_path }}
create_ms_map.control.pattern                   =   {{ data_input_pattern }}

# generate a mapfile with all files in a single entry, length = 1
combine_mapfile.control.kind                    =  plugin
combine_mapfile.control.type                    =  createMapfile
combine_mapfile.control.method                  =  mapfile_all_to_one
combine_mapfile.control.mapfile_in              =  create_ms_map.output.mapfile
combine_mapfile.control.mapfile_dir             =  input.output.mapfile_dir
combine_mapfile.control.filename                =  combine_mapfile.mapfile

# compute frequency groupings, image sizes, averaging values, etc., len = different
do_magic.control.type                           =  pythonplugin
do_magic.control.executable                     =  {{ do_magic_script }}
do_magic.argument.flags                         =  [combine_mapfile.output.mapfile]
do_magic.argument.outmapname                    =  do_magic.datamap
do_magic.argument.mapfile_dir                   =  input.output.mapfile_dir
do_magic.argument.cellsize_highres_deg          =  {{ cellsize_highres_deg }}
do_magic.argument.cellsize_lowres_deg           =  {{ cellsize_lowres_deg }}
do_magic.argument.fieldsize_highres             =  {{ fieldsize_highres }}
do_magic.argument.fieldsize_lowres              =  {{ fieldsize_lowres }}
do_magic.argument.image_padding                 =  {{ image_padding }}
do_magic.argument.calc_y_axis_stretch           =  True

# convert the output of do_magic into usable mapfiles, len = 1 / different
do_magic_maps.control.kind                           =  plugin
do_magic_maps.control.type                           =  mapfilenamesFromMapfiles
do_magic_maps.control.mapfile_groupmap               =  do_magic.output.groupmap.mapfile
do_magic_maps.control.mapfile_single_map             =  do_magic.output.single_mapfile.mapfile
do_magic_maps.control.mapfile_high_size_map          =  do_magic.output.high_size_mapfile.mapfile
do_magic_maps.control.mapfile_low_size_map           =  do_magic.output.low_size_mapfile.mapfile
do_magic_maps.control.mapfile_freqstep_map           =  do_magic.output.freqstep.mapfile
do_magic_maps.control.mapfile_timestep_map           =  do_magic.output.timestep.mapfile
do_magic_maps.control.mapfile_high_padsize_map       =  do_magic.output.high_padsize_mapfile.mapfile
do_magic_maps.control.mapfile_low_padsize_map        =  do_magic.output.low_padsize_mapfile.mapfile
do_magic_maps.control.mapfile_nwavelengths_high_map  =  do_magic.output.nwavelengths_high_mapfile.mapfile
do_magic_maps.control.mapfile_nwavelengths_low_map   =  do_magic.output.nwavelengths_low_mapfile.mapfile

# create a mapfile with the direction independent parmDBs, length = nfiles
create_parmdb_map.control.kind                  =  plugin
create_parmdb_map.control.type                  =  createMapfile
create_parmdb_map.control.method                =  add_suffix_to_file
create_parmdb_map.control.mapfile_in            =  do_magic_maps.output.single_map
create_parmdb_map.control.add_suffix_to_file    =  {{ direction_indep_parmDBs }}
create_parmdb_map.control.mapfile_dir           =  input.output.mapfile_dir
create_parmdb_map.control.filename              =  dir_indep_instrument_parmdbs.mapfile

# select bands spread over the full bandwidth for imaging, length = nbands_image
select_imaging_bands.control.kind        = plugin
select_imaging_bands.control.type        = selectDistFreqs
select_imaging_bands.control.mapfile_in  = do_magic_maps.output.groupmap
select_imaging_bands.control.num         = {{ nbands_image }}
select_imaging_bands.control.mapfile_dir = input.output.mapfile_dir
select_imaging_bands.control.filename    = imaging_high_bands.mapfile

# adjust the high_size mapfile to match the selected bands, length = nbands_image
select_high_size.control.kind         = plugin
select_high_size.control.type         = matchDistFreqs
select_high_size.control.mapfile_in   = do_magic_maps.output.high_size_map
select_high_size.control.mapfile_dist = select_imaging_bands.output.mapfile
select_high_size.control.mapfile_full = do_magic_maps.output.groupmap
select_high_size.control.mapfile_dir  = input.output.mapfile_dir
select_high_size.control.filename     = imaging_high_size.mapfile

# adjust the nwavelengths mapfile to match the selected bands, length = nbands_image
select_high_nwavelengths.control.kind         = plugin
select_high_nwavelengths.control.type         = matchDistFreqs
select_high_nwavelengths.control.mapfile_in   = do_magic_maps.output.nwavelengths_high_map
select_high_nwavelengths.control.mapfile_dist = select_imaging_bands.output.mapfile
select_high_nwavelengths.control.mapfile_full = do_magic_maps.output.groupmap
select_high_nwavelengths.control.mapfile_dir  = input.output.mapfile_dir
select_high_nwavelengths.control.filename     = imaging_high_nwavelengths.mapfile

# high-res imaging, length = nbands_image
wsclean_high.control.kind                      =   recipe
wsclean_high.control.type                      =   executable_args
wsclean_high.control.executable                =   {{ wsclean_executable }}
wsclean_high.control.outputsuffixes            =   [-image.fits,-model.fits]
wsclean_high.control.outputkey                 =   name
wsclean_high.control.args_format               =   wsclean
wsclean_high.control.max_per_node              =   {{ max_imagers_per_node }}
wsclean_high.control.error_tolerance           =   {{ error_tolerance }}
wsclean_high.control.mapfiles_in               =   [select_imaging_bands.output.mapfile,select_high_size.output.mapfile,select_high_nwavelengths.output.mapfile]
wsclean_high.control.inputkeys                 =   [msfile,outputsize,nwavelengths]
wsclean_high.argument.flags                    =   [-no-update-model-required,-reorder,-local-rms,-fitbeam,msfile]
wsclean_high.argument.size                     =   outputsize
wsclean_high.argument.padding                  =   {{ image_padding }}
wsclean_high.argument.niter                    =   50000
wsclean_high.argument.threshold                =   0.0
wsclean_high.argument.pol                      =   I
wsclean_high.argument.weight                   =   briggs 0.0
wsclean_high.argument.mgain                    =   0.8
wsclean_high.argument.baseline-averaging       =   nwavelengths
wsclean_high.argument.maxuv-l                  =   {{ maxlambda_highres }}
wsclean_high.argument.scale                    =   {{ cellsize_highres_deg }}
wsclean_high.argument.mem                      =   {{ max_percent_mem_per_img }}
wsclean_high.argument.j                        =   {{ max_cpus_per_img }}
wsclean_high.argument.tempdir                  =   {{ local_scratch_dir }}
wsclean_high.argument.weighting-rank-filter    =   3
wsclean_high.argument.auto-mask                =   3.3
wsclean_high.argument.auto-threshold           =   0.5
wsclean_high.argument.local-rms-window         =   50
wsclean_high.argument.local-rms-method         =   rms-with-min

**Comment by darafferty** [comment]
I tired your parset (changing the paths), but got no error. The second error message suggests that one of the steps in your parset has a different number of parameters for `mapfiles_in` than for `inputkeys`. Can you check the later steps to see if they are all OK in this respect?

**Comment by AnnalisaB** [comment]
They look all ok to me

I attach the whole parset here
[initsub_fast.parset.txt](https://github.com/lofar-astron/prefactor/files/1569343/initsub_fast.parset.txt)

**Comment by darafferty** [comment]
I just noticed that you are missing some of the executable paths at the beginning. You should have all of the following:

```
! wsclean_executable          = /home/lofar/opt/src/wsclean/wsclean/build/wsclean
! do_magic_script             = /home/lofar/opt/src/prefactor/scripts/InitSubtract_sort_and_compute.py
! merge_skymodels_script      = /home/lofar/opt/src/prefactor/scripts/merge_skymodels.py
! make_clean_mask_script      = /home/lofar/opt/src/prefactor/scripts/make_clean_mask.py
! plot_subtract_images_script = /home/lofar/opt/src/prefactor/scripts/plot_subtract_images.py
! fits2sky_script             = /home/lofar/opt/src/prefactor/scripts/fits2sky.py
! pad_image_script            = /home/lofar/opt/src/prefactor/scripts/pad_image.py
! makesourcedb                = /home/lofar/opt/lofar/bin/makesourcedb
```

The missing ones might be causing the problem somehow.

**Comment by AnnalisaB** [comment]
Oh thanks! Those 2 went unnoticed and are not in the local installation here.
I have asked the system manager to update the version we are using and then I will try again and let you know if that works

Many thanks again

**Comment by AnnalisaB** [comment]
Hi David,
I managed to go through the wsclean_high step, but I git stack again at the next step, when the mask is created. All is OK until it reaches wavelet scale number 3 and the vaue of background mean results 0.0 Jy/beam. Later it fails because it attempts to divide by 0.

I attach the log, in case you can have a look. I am running this to test a singularity installation of the LOFAR software, so I am giving only 5 MS in input. Thanks a lot
[initsub_fast_gr5.log](https://github.com/lofar-astron/prefactor/files/1579627/initsub_fast_gr5.log)

**Comment by darafferty** [comment]
It looks like there is a problem with `L371804_SB472_uv.dppp.pre-cal_126F5A78Et_168MHz.pre-cal.ms`, as I see that WSClean reports that it cannot find any peaks. Check whether that band is fully flagged. (The background mean of 0.0 is OK, as it is forced to that during fitting.)

**Comment by AnnalisaB** [comment]
Thanks. It ends successfully now. It would be great to have some flags within the pipeline that excludes a priori fully flagged bands

Cheers and Thanks again for your help
