### ISSUE TITLE
Memory consumption question

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#164]
Hi,

I have a question about the memory question of the prefactor pipeline.

On one machine with 48 cores and 128 GB of ram, I have the following settings in the target parset:
```
# number of processes to use per step per node
! num_proc_per_node        = 4
# number of processes to use per step per node for tasks with high i/o (dppp or cp) or memory (eg calibration)
! num_proc_per_node_limit  = 3
# number of threads per process for NDPPP
! max_dppp_threads         = 16


```
This maxes out at a memory usage of about 105 GB.

On a second machine, with the same amount of cores but with 256 GB of ram, doubling the num_proc_per_node_limit to 6, uses more than 210 GB...

Does this not scale linearly? If not, how does it scale?

**Comment by rvweeren** [comment]
It seems there will be no answer/or it is not pressing. I close this one, reopen if important
