### ISSUE TITLE
ROBR files can't be downloaded via pipeline

### ISSUE THREAD

**Issue by bn-w** [lofar-astron/prefactor#166]
Hope it's not a repost...

As the CODG seems to be down, I tried to run the pipeline with the IONEX ROBR data. However, it turned out to generate errors. Tracking the error down, I came into the conclusion that whereas ROBR files are accessbile via website, the downloading script searches for names written in lower and upper case letters, while they are named a bit different - capitals only. Not sure, however, if the error is directly in the pipeline, or in the general LOFAR software. 

Manual downloading and gunzip solves the issue.

**Comment by adrabent** [comment]
There was a major overhaul in the RMextract scripts. Does this issue still persist?
