### ISSUE TITLE
Initial subtract error: oa_ndim == 0 ? 

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#169]
Hi,

I am running the initial-subtract-fast parset and every job crashes at point with 
`2018-02-27 10:46:49 ERROR   node.slurm9.python_plugin: Using "oa_ndim == 0" when "op_axes" is NULL. Use "oa_ndim == -1" or the MultiNew iterator for NumPy <1.8 compatibility`

This apparently happens in make_clean_mask.py. I checked the version by putting a print np.__version__ into this script and it shows that we have 1.13.3 installed. So I am out of ideas.

Do you have an idea?

Thx,
Arpad

**Comment by darafferty** [comment]
This error seems to be the same as https://github.com/lofar-astron/PyBDSF/issues/54, which was resolved by updating numexpr -- please reopen if not.
