### ISSUE TITLE
plot_cal_phases with losoto

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#17]
Andreas, I'm testing your v2.0-devel version and seem to have issues with the losoto call for plotting the phases. I get errors like "stderr: CRITICAL: Missing parset file, I don't know what to do"

**Comment by AHorneffer** [comment]
Hi Wendy. You need to patch the executable_args node-script, as I explained in: https://github.com/lofar-astron/prefactor/issues/4
It will be included in the next release of the LOFAR software and is already in the latest trunk.

**Comment by AHorneffer** [comment]
It is actually mentioned in the comments at the top of the Pre-Facet-Cal.parset

**Comment by wllwen007** [comment]
Whoops, sorry I missed that.

**Comment by AHorneffer** [comment]
[Sorry for the snippy comment, I confused the "Close and comment" button with an undo button.]

Do you think it would be useful to make a version that includes the patched nodescript? Or can we expect everyone to upgrade or patch the LOFAR installation?

**Comment by wllwen007** [comment]
The patch is simple enough to do and, as you said, the information is in the parset header (although it may be useful to include the patch directly or a link to [#4](https://github.com/lofar-astron/prefactor/issues/4) )
