### ISSUE TITLE
prefactor depends on lsmtools which depends on deprecated wcsaxes

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/prefactor#172]
hi!

While packaging prefactor for the upcoming KERN-4 I noticed prefactor depends on lsmtools, which depends on the deprecated wcsaxes. until wcsaxes has been ported to use astropy, I can't upload it to KERN-4.

https://github.com/kernsuite/packaging/issues/102

**Comment by adrabent** [comment]
This package is only needed for advanced plotting according to the LSMtool documentation. You should be able to use it without wcsaxes.

**Comment by darafferty** [comment]
LSMtool now supports wcsaxes in astropy (as of version 1.3), so this issue should be addressed.
