### ISSUE TITLE
prefactor python_plugin error on h5impcal step

### ISSUE THREAD

**Issue by oonkjbr** [lofar-astron/prefactor#173]
Hi All, TJD, DR, AD

So we managed to resolve the issue with  solset._f_get_child, I think, but now we have run into a new problem. The solution tables are read, but the then we get below following error. This look like something internal to prefactor, like some file is temporarily unavailable, but I would not know how to check or test what exactly is going. Note that, (i) I am running this from a singularity image, (ii) I have already once run the generic pipeline in this way successfully on the individual calibrator subbands to generate the solution tables. In this step I am just trying to combine the solutions and compute teh clock-tec. Any and all advice/help is appreciated.

Also note that I am using the same stuff as before in the previous issue i.e. LOFAR 2_20_2 and Losoto v 1.0 etc. I'll be happy to share the singularity image with anyone if that would help.

-R

```
---
2018-05-08 12:01:54 WARNING genericpipeline.executable_args:  98% |####################################################################### |
2018-05-08 12:01:55 WARNING genericpipeline.executable_args: 100% |########################################################################|
2018-05-08 12:01:55 ERROR   genericpipeline.executable_args: Failed to run remote process python /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py ([Errno 11] Resource temporarily unavailable)
Traceback (most recent call last):
  File "/opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 304, in dispatch
    job_successful = (pg.wait_for_finish() is None)
  File "/opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/subprocessgroup.py", line 237, in wait_for_finish
    fd_lookup[fileno].read(fileno)
  File "/opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/support/subprocessgroup.py", line 110, in read
    self._addoutput(self.STDERR, self.process.stderr.read(4096))
IOError: [Errno 11] Resource temporarily unavailable
2018-05-08 12:01:55 DEBUG   genericpipeline.executable_args: Adding node_logging_information
2018-05-08 12:01:55 ERROR   genericpipeline.executable_args: A job has failed with returncode 1 and error_tolerance is not set. Bailing out!
2018-05-08 12:01:55 WARNING genericpipeline.executable_args: Note: recipe outputs are not complete
2018-05-08 12:01:55 WARNING genericpipeline.executable_args: recipe executable_args completed with errors
2018-05-08 12:01:55 WARNING genericpipeline: pythonplugin reports failure (using executable_args recipe)
2018-05-08 12:01:55 ERROR   genericpipeline: *******************************************
2018-05-08 12:01:55 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Calibrator-2
2018-05-08 12:01:55 ERROR   genericpipeline: Detailed exception information:
2018-05-08 12:01:55 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2018-05-08 12:01:55 ERROR   genericpipeline: pythonplugin failed
2018-05-08 12:01:55 ERROR   genericpipeline: *******************************************
2018-05-08 12:01:55 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2018-05-08 12:01:55 WARNING genericpipeline: recipe genericpipeline completed with errors
---
```

**Comment by twshimwell** [comment]
Can you upload the full log?

**Comment by oonkjbr** [comment]
attached the stdout log file (let me know if any other logs would be useful)

-R

[07_05_2018_14.55.47_logs_out.txt](https://github.com/lofar-astron/prefactor/files/1983538/07_05_2018_14.55.47_logs_out.txt)

**Comment by twshimwell** [comment]
i could easily be misreading it but it looks a bit like it cant write the h5parm for some reason. I guess this directory -- /mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.O2FpBw6C2N/prefactor/workdir/Pre-Facet-Calibrator-2 -- exists?

**Comment by oonkjbr** [comment]
This is from a different trial, with the same error (now without cleaning up the tmp,run,work directories):

-R

[lofar001@eagle ln38s_pref_cal2_L632075_000]$ ls /mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.B88Ib9HbhS/prefactor/workdir/Pre-Facet-Calibrator-2/
h5imp_cal_losoto.h5

[lofar001@eagle ln38s_pref_cal2_L632075_000]$ ls /mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.B88Ib9HbhS/prefactor/workdir/
Pre-Facet-Calibrator-2

Prefactor is in:
[lofar001@eagle ln38s_pref_cal2_L632075_000]$ ls /mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.B88Ib9HbhS/prefactor/
bin                           Initial-Subtract.parset  pipeline.cfg  Pre-Facet-Calibrator.parset             Pre-Facet-Calibrator-RawSingle.parset  Pre-Facet-Target.parset             Pre-Facet-Target-RawSingle.parset  results  scripts                skymodels
Initial-Subtract-Deep.parset  parsets                  plugins       Pre-Facet-Calibrator-RawCombine.parset  Pre-Facet-Cal.parset                   Pre-Facet-Target-RawCombine.parset  README.md                          rundir   Simple-Selfcal.parset  workdir

The mapfiles are in:
[lofar001@eagle prefactor]$ ls /mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.B88Ib9HbhS/prefactor/rundir/Pre-Facet-Calibrator-2/mapfiles/
createmap_cal.mapfile  h5_imp_cal_map.mapfile


The data is in:
[lofar001@eagle prefactor]$ ls /mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.B88Ib9HbhS/Input/
L632075_SB000_uv.ndppp_prep_cal  L632075_SB031_uv.ndppp_prep_cal  L632075_SB062_uv.ndppp_prep_cal  L632075_SB093_uv.ndppp_prep_cal  L632075_SB122_uv.ndppp_prep_cal  L632075_SB151_uv.ndppp_prep_cal  L632075_SB180_uv.ndppp_prep_cal  L632075_SB209_uv.ndppp_prep_cal
...

**Comment by twshimwell** [comment]
and if you try just restarting the pipeline again to resume it then does it just crash again?

**Comment by oonkjbr** [comment]
The problem appears to be is related to h5parm file creation (writing) for the solutions (inst tables) that were being read

i.e.

WARNING: No sky table found. (Direction-dependent parameters will not work.)
INFO: Creating a new solution-set: sol000.
INFO: --Creating new antenna table.
INFO: --Creating new source table.
INFO: Found solution types: Gain, CommonRotationAngle
INFO: Reading *Gain:*:Imag.
100% |#######################################################################################################################################################################################################################################################################|
this works, but then the file is not written/created due to 'resource unavailable' (due create_h5parm function from importer.py in losoto)

and hence it can not continue with 'Filling table'

Strangely enough it does work when run manually with singularity in a locally (/mnt/lustre/inula/shared/lofar/oonk/zz/Input) generated directory, this local call did then not involve the generic pipeline framework, but only singularity and the local filesystem

So the problem must be a combination of the local filesystem/singularity and the generic pipeline framework... ?!

**Comment by darafferty** [comment]
I wonder if it could be related to user limits on the number of processes or open files (e.g., something like https://github.com/lofar-astron/prefactor/wiki/Documentation%3A-Faq#low-maxproc-value)? A quick search for "[Errno 11] Resource temporarily unavailable" shows that this error sometimes occurs due to the user limits being too low.

**Comment by oonkjbr** [comment]
Hi David, All,

Thanks. I'll try to look into this and cross-check with the sys admins. I also noted that the (old?) importer.py create_h5parm actually does quite a few calls on the host and file system (socket, host calls). I wonder if perhaps something like this could be an issue on different cluster systems. Similarly, is there any chance that one of these calls could leave the file in state such that it cant be accessed?

When I look in  /prefactor/workdir/Pre-Facet-Calibrator-2 I find the file:
h5imp_cal_losoto.h5
-
bash-4.1$ du -hs h5imp_cal_losoto.h5
100M	h5imp_cal_losoto.h5
-bash-4.1$ ls -allh h5imp_cal_losoto.h5
-rw-r--r-- 1 lofar038 lofar 100M May  8 16:11 h5imp_cal_losoto.h5

This is the file that we expect the step we h5_imp_cal_map to make (if I am not mistaken). Not sure if the size is as expected for a typical prefactor run. Are there any good ways of checking the validity of this file (I am not the greatest h5 expert...)?

**Comment by oonkjbr** [comment]
Dear David, TJD, All,

We have looked at number of allowed files on the eagle system and that should be more than sufficient:

ulimit -a output :

Limits :
core file size              (blocks, -c) unlimited
data seg size             (kbytes, -d) unlimited
scheduling priority     (-e) 0
file size                      (blocks, -f) unlimited
pending signals         (-i) 1030268
max locked memory (kbytes, -l) unlimited
max memory size      (kbytes, -m) 2097152
open files                   (-n) 4096
pipe size                    (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority         (-r) 0
stack size                  (kbytes, -s) unlimited
cpu time                    (seconds, -t) unlimited
max user processes (-u) 1030268
virtual memory          (kbytes, -v) unlimited
file locks                    (-x) unlimited

So the issue is likely related to either socket calls of pipe segment sizes. The eagle admins find that the pipe segment size is most likely. However, in order to increase its size one would have to recompile the kernel and reboot all nodes (which is infeasible for the current operational system until the next drain round, which is months away). An possible alternative software solution is highlighted in the below link:

https://stackoverflow.com/questions/13340893/oserror-errno-11-resource-temporarily-unavailable-what-causes-this

I dont know who develops subprocessgroup.py, but is this something worth trying to do/fix?

-R

**Comment by tikk3r** [comment]
To expand on Raymond's comment, I encounter this issue as well at the h5imp_cal step of the long baseline pipeline being developed.
It's not prefactor, but maybe it helps to know it occurs here as well. I have not (yet) encountered this error when running prefactor on this data, however.
Running this command on its own works fine, and sometimes it goes through if you spam the pipeline often enough, but it is pretty much a guaranteed crash at this step.

The user limits I have on the cluster:

> core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2062968
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65536
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

and the error message, which is the same:
> 2018-05-10 14:44:25 ERROR   genericpipeline.executable_args: Failed to run remote process python /net/lofar1/data1/oonk/rh7_lof_apr2017_2_20_2/lofar/lib64/python2.7/site-packages/lofarpipe/recipes/nodes/pyth    on_plugin.py ([Errno 11] Resource temporarily unavailable)
    Traceback (most recent call last):
      File "/net/lofar1/data1/oonk/rh7_lof_apr2017_2_20_2/lofar/lib64/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 304, in dispatch
        job_successful = (pg.wait_for_finish() is None)
      File "/net/lofar1/data1/oonk/rh7_lof_apr2017_2_20_2/lofar/lib64/python2.7/site-packages/lofarpipe/support/subprocessgroup.py", line 237, in wait_for_finish
        fd_lookup[fileno].read(fileno)
      File "/net/lofar1/data1/oonk/rh7_lof_apr2017_2_20_2/lofar/lib64/python2.7/site-packages/lofarpipe/support/subprocessgroup.py", line 110, in read
        self._addoutput(self.STDERR, self.process.stderr.read(4096))
    IOError: [Errno 11] Resource temporarily unavailable

**Comment by twshimwell** [comment]
was issue #160 the same? That seemed to be a memory issue.

**Comment by oonkjbr** [comment]
Hey Tim,

Reading through #160... Was it actually resolved?, because it does not read like it was properly resolved. It would even seem odd to me that it could it overrun the memory on this task, given the amount of data involved for this tiny step, and given the amount of memory available on (atleast) the Leiden notes.

Frits, could you check/monitor on the Leiden node whether memory is an issue and report back here?

The other reason I dont think its a memory issue, but rather a pipe issue, is that when these commands are run manually, without the generic pipeline framework, that for both me and Frits these steps do complete normally without issue. However, running these commands manually for each dataset is not really an option, so it would be good to find/fix the underlying cause.

**Comment by twshimwell** [comment]
Yeh the "solving" of that issue wasnt conclusively described but it did suggest memory. Maybe  @amisk has more insight?

Worth looking for MemoryExceptions (that are unfortunately not recorded in logs) during runs though.

**Comment by tikk3r** [comment]
> Frits, could you check/monitor on the Leiden node whether memory is an issue and report back here?

I'll see/monitor what happens on the next run and report back when done (will take a couple of days). 

The fact that it works when run separately, or sometimes when restarting after the crash makes me believe at least something is reaching its limits (sometimes / for some people) when the pipeline is run in full up to this step.

**Comment by tikk3r** [comment]
From what I've gathered the problem is related to the software version being used. Available here, I have `2_19_0` and `2_20_2`. Running the pipeline with `2_19_0` causes no problems (tried twice with the international pipeline and many times with prefactor in the past). Using `2_20_2`, however, is, as mentioned, a guaranteed crash for me.

Is there a way to check what changed between these two and causes the crash?

Perhaps this is something that has been solved/magically disappeared in newer versions, but I cannot check that at the moment as I do not have them available to me here.

**Comment by lmorabit** [comment]
I found a workaround for this, although I still don't know why it didn't work in the first place.  I changed the genericpipeline step from using losotoImporter.py as a pythonplugin to a recipe, and now this works with no issues:

h5imp_cal.control.kind                          = recipe
h5imp_cal.control.type                          = executable_args
h5imp_cal.control.executable                    = {{ losoto_importer }}
h5imp_cal.control.mapfile_in                    = find_delay_cal.output.mapfile
h5imp_cal.control.inputkey                      = source
h5imp_cal.control.arguments                     = [h5imp_cal_losoto.h5,source]

**Comment by oonkjbr** [comment]
Hi Leah, All

I tried your suggested change, thanks for adding here. I must have done something wrong, see below, related to executable_args which I did not have in my previous setup. If you have any suggestions then please let me know.

So I used to have:

# import all instrument tables into one LoSoTo file
h5imp_cal.control.type           =  pythonplugin
h5imp_cal.control.executable      =  {{ losoto_importer }}
h5imp_cal.control.error_tolerance =  {{ error_tolerance }}
h5imp_cal.argument.flags          =  [h5_imp_cal_map.output.mapfile,h5imp_cal_losoto.h5]
h5imp_cal.argument.instrument     =  /instrument
h5imp_cal.argument.solsetName     =  sol000
h5imp_cal.argument.compression    =  7

I then changed it to:

# import all instrument tables into one LoSoTo file
#h5imp_cal.control.type           =  pythonplugin
h5imp_cal.control.kind            =  recipe
h5imp_cal.control.type            =  executable_args
h5imp_cal.control.executable      =  {{ losoto_importer }}
h5imp_cal.control.error_tolerance =  {{ error_tolerance }}
h5imp_cal.argument.flags          =  [h5_imp_cal_map.output.mapfile,h5imp_cal_losoto.h5]
h5imp_cal.argument.instrument     =  /instrument
h5imp_cal.argument.solsetName     =  sol000
h5imp_cal.argument.compression    =  7

It now crashes on the lines I changed with the following error:

2018-07-17 16:20:36 ERROR   genericpipeline: *******************************************
2018-07-17 16:20:36 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Calibrator-2
2018-07-17 16:20:36 ERROR   genericpipeline: Detailed exception information:
2018-07-17 16:20:36 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2018-07-17 16:20:36 ERROR   genericpipeline: executable_args failed
2018-07-17 16:20:36 ERROR   genericpipeline: *******************************************
2018-07-17 16:20:36 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.


Another part of the std. output provides:

2018-07-17 16:20:35 ERROR   node.e1001.executable_args: Command '/mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.rVin3z5Scy/prefactor/scripts/losotoImporter.py' returned non-zero exit status 2
2018-07-17 16:20:35 INFO    node.e1001.executable_args: Total time 4.0106s; user time: 0.2370s; system time: 0.4290s
2018-07-17 16:20:35 DEBUG   node.e1001.executable_args: Start time was 1531837231.7367s; end time was 1531837235.7474s
2018-07-17 16:20:35 DEBUG   genericpipeline.executable_args: 
2018-07-17 16:20:35 WARNING genericpipeline.executable_args: 
2018-07-17 16:20:35 INFO    genericpipeline.executable_args: Subprocess completed with exit status 1: /bin/sh -c python /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py 0 172.16.19.239 33873
2018-07-17 16:20:35 ERROR   genericpipeline.executable_args: Remote process python /opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py ["['/mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.rVin3z5Scy/Input/L632075_SB000_uv.ndppp_prep_cal', '/mnt/lustre/inula/shared/lofar/oonk/ln38s_pref_cal2_L632075_000/tmp.rVin3z5Scy/Input

**Comment by tikk3r** [comment]
Seems like the script ran, but crashed on something. I think we need to see the actual crash message in the logs to see what happened (do errors from recipes get caught in the logs?).

**Comment by lmorabit** [comment]
Hi Raymond,

I think the problem might be that you're passing mapfile names to the script, and passing arguments as flags. The pythonplugin kind will interact directly with the def main() in the python script, but the recipe won't -- it will just run whatever values you pass it. Assuming h5_imp_cal_map.output.mapfile is your mapfile for the MS containing /instrument, please try:

h5imp_cal.control.kind = recipe
h5imp_cal.control.type = executable_args
h5imp_cal.control.executable = {{ losoto_importer }}
h5imp_cal.control.mapfile_in = h5_imp_cal_map.output.mapfile
h5imp_cal.control.inputkey = source
h5imp_cal.argument.arguments = [h5imp_cal_losoto.h5,source]

note:
## h5imp_cal.argument.instrument = /instrument  ## this is the default option
## h5imp_cal.argument.solsetName = sol000 ## this is the default option
## h5imp_cal.argument.compression = 7  ## default is 5 but I don't think you need to change it, and you can't do it this way with a recipe anyway.

**Comment by adrabent** [comment]
I guess this issue is obsolete since prefactor 3.0.
If not please open the issue again.
