### ISSUE TITLE
Prefactor 3.0 stuck on process_losoto_bandpass

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#178]
We are testing the prefactor 3.0 calibrator part on the Leiden cluster and it seems to be stuck on the `process_losoto_bandpass` step. It has been on this step for a couple of days now without signs of continueing or doing anything.
I have tried stopping and restarting the pipeline (updating the statefile as well), but to no avail. How long should this step take, roughly?

There is no LoSoTo output in the terminal window of the pipeline either. Running the LoSoTo command separately seems to work, it just takes a long time flagging the data.

I am using the, at the time, latest versions of prefactor (https://github.com/lofar-astron/prefactor/commit/c6428f171b923e22691d84c30a0c60699aa4e9c1) and LoSoTo (https://github.com/revoltek/losoto/commit/fe1b3b362ea2b26b61011ba698ab817470614272), with the latest LOFAR software as well.

**Comment by adrabent** [comment]
Taking too long often means that it has crashed at a point. Unfortunately, these crashes are often not put into std error outputs, so running the h5parm file outside of the genericpipeline often reveals the step of failure. But interestingly, outside it seems to work which is a bit strange.

I don't have a "number" in my head, but it should be pretty fast (depending on the amount of data).
I would suggest that you could provide me the h5parm-file where this issue appears, so that I can try to reproduce the error.

**Comment by rvweeren** [comment]
Fo checking make sure you use the same losoto (not only the same version number)

(just to rule out losoto differences…)

**Comment by tikk3r** [comment]
This is the H5Parm it's running at: https://surfdrive.surf.nl/files/index.php/s/zEElcDBDL7YGZ8t
In the inspection folder the plots `ampAFlag_pol**.png` and `ampBFlag_pol**.png` are present, so it has done something.
Running the command locally takes a long time to go through all the stations for flagging in the bandpass step, and it has the same signature in htop, i.e. pretty much no CPU and memory usage. So I'm not sure if it has actually crashed, or is still doing stuff. A couple of days seems long though.

**Comment by tikk3r** [comment]
The separate run now also appears to be stuck. I ran
   
    losoto instrument.h5imp_cal_bandpass losoto.parset

It outputted `Flagged 0.0892531876138% of solutions for station 26 (pol 0)` and since then nothing has appeared anymore. No crash, no error, just no output and very little CPU/RAM usage.

**Comment by revoltek** [comment]
Many times this "stuck" problems in parallelised code are due to a return of the main function that didn't wait for all the children to finish. E.g. this is how an error should be handled:
if "check for an error":
                        logging.error("blabla")
                        mpm.wait()
                        return 1

if one doesn't have the mpm.wait() the code get stuck.

**Comment by adrabent** [comment]
@revoltek 
I agree. In my test run some of the threads crash with the following error:

`Process multiThread-187:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/drabent/losoto/losoto/lib_operations.py", line 35, in run
    self.funct(*parms, outQueue=self.outQueue)
  File "/home/drabent/losoto/losoto/operations/prefactor_bandpass.py", line 344, in _flag_amplitudes
    p, bp_sp = _fit_bandpass(freqs, np.log10(amps_div), sigma_div, band)
  File "/home/drabent/losoto/losoto/operations/prefactor_bandpass.py", line 247, in _fit_bandpass
    bounds=param_bounds)
  File "/usr/lib64/python2.7/site-packages/scipy/optimize/minpack.py", line 750, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + res.message)
RuntimeError: Optimal parameters not found: The maximum number of function evaluations is exceeded. `

**Comment by tikk3r** [comment]
Ah. I'm assuming then that this current run will get "stuck" as well. The other one probably crashed on antenna 26, pol 1 which isn't processed yet in this run.

So should we pass errors back to the parent then, somehow? Maybe we could use something like [this](https://stackoverflow.com/questions/15536295/python-multiprocessing-process-crashes-silently) to handle exceptions?

F

**Comment by adrabent** [comment]
In order to avoid the issue you could at first set

`autoFlag = False`

**Comment by adrabent** [comment]
I added a little workaround. If the fitting fails it just returns the non-fitted output.
This should at least preventing the program for hanging at this point.

https://github.com/revoltek/losoto/commit/436cb32af09fd542d999ae888bfa7dc9886da8b1

@revoltek You are right. I need to add a robust error handling for multiprocessing tasks.

Alex

**Comment by tikk3r** [comment]
Using `autoFlag=False`, the pipeline finished successfully.

Frits

**Comment by adrabent** [comment]
You could also update your losoto and check whether it runs also successfully with `autoflag=True`.

**Comment by tikk3r** [comment]
> You could also update your losoto and check whether it runs also successfully with autoflag=True.

I will try that as well and report back.

**Comment by darafferty** [comment]
I changed the fitting method to one that I hope is more robust, and It now seems to work OK on the above h5parm. Frits, can you update losoto and try Alex's suggestion (autoflag=True) to see if the fitting is now successful?

**Comment by tikk3r** [comment]
> I changed the fitting method to one that I hope is more robust, and It now seems to work OK on the above h5parm. Frits, can you update losoto and try Alex's suggestion (autoflag=True) to see if the fitting is now successful?

I updated to the new version and set autoFlag=True. It finished successfully this time.
