### ISSUE TITLE
[Prefactor 3.0] BLsmooth.py onlycopy option wrong documentation / confusing option

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#179]
The `BLsmooth.py` script and its documentation regarding copying does not reflect what the script actually does. It is documented as

https://github.com/lofar-astron/prefactor/blob/c6428f171b923e22691d84c30a0c60699aa4e9c1/scripts/BLsmooth.py#L52

However, the parset passes an argument `do_smooth`. Which, when set to `False` actually copies instead of smoothing, which contradicts the behaviour of the script:
https://github.com/lofar-astron/prefactor/blob/c6428f171b923e22691d84c30a0c60699aa4e9c1/scripts/BLsmooth.py#L82-L84

Changing the documentation and code to reflect the smoothing operation, e.g. change `--onlycopy` to `--smooth` would be clearer I think.

Cheers,

Frits

**Comment by adrabent** [comment]
I hope that this renaming is less confusing now.

**Comment by tikk3r** [comment]
> I hope that this renaming is less confusing now.

I think it's perfect now.
