### ISSUE TITLE
[Prefactor 3.0] Hard code -pi, pi range for plotting phases

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#180]
From the pipeline output it looks like the phase plots all have slightly different ranges. Always plotting them on the same [-pi, pi] (or whatever numerical approximation) scale may make comparing them easier. They are small differences, but just for clarity :)

F.

**Comment by revoltek** [comment]
I also always plot phases with minmax = [-3.14, 3.14], that helps a lot. In case of residuals you can hardcore a [-1,1] or so

fra

**Comment by adrabent** [comment]
I thought in case of phases losoto always uses [-3.14,3,14] as a range automatically.
