### ISSUE TITLE
[Prefactor 3.0] Target crash at ms_concat

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#181]
The target pipeline crashes for met at the `ms_concat` step. It givens an error with

    2018-08-15 11:42:34 ERROR   node.lofar4.strw.leidenuniv.nl.python_plugin: TableProxy::TableProxy::putColumn: no such row

from the logs, the inputs are list of all `ndppp_prep_target` sub-bands and a `L******_SB243_uv.dppp.ms_concat_target`.
At first I thought maybe the parset was incomplete (I don't immediately see what `outputkey` in this step refers to), but since it does pass two arguments to `concat_MS.py` in the logs, it seems to work.

What could cause this crash?

Frits

**Comment by adrabent** [comment]
Hmm.. there should be only `ndppp_prep_target` as an input.
How do the entries in the mapfile of `combine_target_map` look like?

**Comment by adrabent** [comment]
The mapfile should only contain entries like this:
`[{'host': 'localhost', 'file': ['/data/scratch/drabent/working_directory/Pre-Facet-Target/L228163_SB150_uv.dppp.ndppp_prep_target'`[...] `'/data/scratch/drabent/working_directory/Pre-Facet-Target/L228163_SB199_uv.dppp.ndppp_prep_target'], 'skip': False}]`

If this is the case, please check whether one of the `ndppp_prep_target` files might be broken.

**Comment by tikk3r** [comment]
My mapfile looks like that

    [{'host': 'localhost', 'file': ['/net/lofar5/data2/sweijen/prefactor_3.0_test_target/working/Pre-Facet-Target/L427100_SB000_uv.dppp.ndppp_prep_target',...,'/net/lofar5/data2/sweijen/prefactor_3.0_test_target/working/Pre-Facet-Target/L427100_SB243_uv.dppp.ndppp_prep_target'], 'skip': False}]

The parset passes two options though:

https://github.com/lofar-astron/prefactor/blob/780102016dc9c3ec5615e8eb856d53fdf0a81b59/Pre-Facet-Target.parset#L294-L298

If I remove `outputkey` (tried it since I couldn't find any reference to it), it crashes with the complaint that `concat_MS.py` expects two arguments. Further down it says

    Successful readonly open of default-locked concatenated tables [<prep_target MSes>] 24 columns, -769840736 rows

    Successful creation of default-locked table /net/lofar5/data2/sweijen/prefactor_3.0_test_target/working/Pre-Facet-Target/L427100_SB243_uv.dppp.ms_concat_target: 24 columns, 0 rows

I will see if I can figure out if one of the MS is somehow corrupt.

**Comment by tikk3r** [comment]
There is one SB missing, which does appear in the mapfile, but not in the directory. The pipeline seems to handle this though?
Anyway, it errors on the `DATA_DESC_ID` column, which I checked with TaQL to exist in all MS and to have the same length as well.

Testing the concat by hand, using `pyrap.tables.msconcat(<list of ms>, <output>)`, I get this error whenever I try to concatenate more than 148 sub-bands. Anything less and it works fine, anything more and the above error appears. Am I hitting some system limit perhaps?

**Comment by adrabent** [comment]
I tested this script on CEP3 and I could concatenate 371 subbands. The same script is used in the calibrator part, so you could see whether your calibrator files are properly concatenated or not. Some system have a sort or hard limit for the number of open files. Maybe this causes this issue.

If there is one subband missing, which appears in the mapfile I would suggest to remove this entry in the mapfile by hand and try to run it again.

**Comment by tikk3r** [comment]
Still nothing, even starting from scratch again. What is the open file limit on CEP3? Did you have to increase it (or something else)? I can run this step just fine on the calibrator data.

**Comment by adrabent** [comment]
That's odd. The calibrator usually has the same amount of open files.
If I do this on CEP3 I get:
`ulimit -Sn`
or
`ulimit -Hn`

I get the following tupel:
`32768`

But since it works for the calibrator there is something wrong the target data.
Maybe this is a stupid question: Does this crash appear also on every randomly selected sample of 148 subbands?

**Comment by tikk3r** [comment]
Yeah for me those are set to 4096. This is as far as I can raise it myself though, I'd have to check with the sysadmins to test a higher limit.
It happens when I go over that number yes. I tried from 0-147, 20-167, 95-243 they all work, but if I add one more that error occurs.
This data has been processed with the old prefactor, DDFacet and the interational baseline pipeline all just fine, so I don't see what could be wrong.

**Comment by adrabent** [comment]
I encounter exactly the same issue with another data set. My workaround is to use only a fraction of the bandwidth to be flagged at once.
Please test this new approach!

https://github.com/lofar-astron/prefactor/commit/c3b3a8664c2e2c16b4c5f86a8bd1b1763207502a

**Comment by lmorabit** [comment]
I've also had trouble with this -- I can set my ulimit to 16384 (no higher) but that does not solve the problem.

**Comment by adrabent** [comment]
Does this issue still occur?

**Comment by tikk3r** [comment]
Haven't seen this one since.

**Comment by adrabent** [comment]
Okay.. then I will close this ticket until it appears again.
