### ISSUE TITLE
Prefactor target pipeline crash with DPPP error: Unknown correction type: bandpass

### ISSUE THREAD

**Issue by marcoiacobelli77** [lofar-astron/prefactor#182]
The problematic step is when running NDPPP on the target data to flag, transfer calibrator values, and average. The parset of the target pipeline specifies ndppp_prep_target.argument.applybandpass.correction    = bandpass
but than NDPPP crashes
Unknown correction type: bandpass

**Comment by tikk3r** [comment]
I think this may be a typo in either the H5Parm solset or one of the parsets. I changed it to bandpass000 in the applybandpass step, as that's what the solset was actually called in my case.

Frits

Sent from BlueMail<http://www.bluemail.me/r?b=13569>
On 5 Sep 2018, at 17:53, marcoiacobelli77 <notifications@github.com<mailto:notifications@github.com>> wrote:

The problematic step is when running NDPPP on the target data to flag, transfer calibrator values, and average. The parset of the target pipeline specifies ndppp_prep_target.argument.applybandpass.correction = bandpass
but than NDPPP crashes
Unknown correction type: bandpass

**Comment by marcoiacobelli77** [comment]
Hi Frits,


thanks for your suggestion.


By looking in my h5 file from the calibrator pipeline I find 



>>> import h5py
>>> filename = 'instrument.h5imp_cal'

>>> data = h5py.File(filename, 'r')
>>> for key in data.keys():
...     print(key)
... 
sol000



However trying both ndppp_prep_target.argument.applybandpass.correction
= bandpas000 or ndppp_prep_target.argument.applybandpass.correction =
sol000 it does not helpinmy case.


Any other hint ?


Thanks,
 Marco
 




>>> Frits Sweijen <notifications@github.com> 09/05/18 6:01 PM >>>
I think this may be a typo in either the H5Parm solset or one of the
parsets. I changed it to bandpass000 in the applybandpass step, as
that's what the solset was actually called in my case. 
 
 Frits 
 
 Sent from BlueMail<http://www.bluemail.me/r?b=13569> 
 On 5 Sep 2018, at 17:53, marcoiacobelli77
<notifications@github.com<mailto:notifications@github.com>> wrote: 
 
 The problematic step is when running NDPPP on the target data to flag,
transfer calibrator values, and average. The parset of the target
pipeline specifies ndppp_prep_target.argument.applybandpass.correction =
bandpass 
 but than NDPPP crashes 
 Unknown correction type: bandpass 
 
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on
GitHub<https://github.com/lofar-astron/prefactor/issues/182>, or mute
the

**Comment by tikk3r** [comment]
> However trying both ndppp_prep_target.argument.applybandpass.correction
> = bandpas000

A typo perhaps? There's an "s" missing here, it should be `bandpass000`. I see it has been fixed in the calibrator parset about a month ago though.

From your Python snippet,

    data['sol000'].keys()
should list all solution tables that are in there. That should tell you if it's `bandpass` or `bandpass000`.

**Comment by marcoiacobelli77** [comment]
Hi Frits,


your suggestion to check the solution tables name was very useful:


>>> data['sol000'].keys()
[u'RMextract', u'XYoffset', u'XYoffset_notimes', u'amplitude000',
u'antenna', u'bandpass', u'bandpass_notimes', u'clock', u'clock000',
u'phase000', u'phase_offset000', u'rotation000', u'source', u'tec000']


It seems that I have a zoo of names with e.g. 000 and _notimes suffices.




As concerns the bandpass table I am going to try both  u'bandpass' and
u'bandpass_notimes'



Hopefully it will work.


Thanks,
 Marco




>>> Frits Sweijen <notifications@github.com> 09/09/18 1:02 PM >>>
 However trying both ndppp_prep_target.argument.applybandpass.correction
 = bandpas000
  A typo perhaps? There's an "s" missing here, it should be bandpass000.
I see it has been fixed in the calibrator parset about a month ago
though.
 From your Python snippet,
 data['sol000'].keys() should list all solution tables that are in
there. That should tell you if it's bandpass or bandpass000.

**Comment by marcoiacobelli77** [comment]
Hi Frits,


sorry for bothering you but unfortunately either bandpass, bandpass000
or bandpass_notimes is working.



Any further hint ?


Thanks,
 Marco


>>> Frits Sweijen <notifications@github.com> 09/09/18 1:02 PM >>>
 However trying both ndppp_prep_target.argument.applybandpass.correction
 = bandpas000
  A typo perhaps? There's an "s" missing here, it should be bandpass000.
I see it has been fixed in the calibrator parset about a month ago
though.
 From your Python snippet,
 data['sol000'].keys() should list all solution tables that are in
there. That should tell you if it's bandpass or bandpass000.

**Comment by tammojan** [comment]
No, this is not related. I did not implement the suggested change to the interpretation of correction.

**Comment by wllwen007** [comment]
Hey Marco, not sure if it is the same problem as yours, but I've just run into this NDPPP error (Unknown correction type: bandpass) using the prefactor target pipeline in the master branch.

My solution was to set the h5parm variable in the Pre-Facet-Target parset 

It wasn't set, so the generic pipeline was trying to run NDPPP with parameters like applybandpass.parmdb={{ h5parm }}. Strange though that the error appears on applybandpass and not the first occurrence on applyclock...

**Comment by tikk3r** [comment]
@wllwen007 I think that's probably it. In the parset for the `version3.0` branch, this h5parm is explicitely defined on the top.

Perhaps the parset on the master branch is missing this variable?

**Comment by adrabent** [comment]
Please check if the fix has resolved the issue.

**Comment by marcoiacobelli77** [comment]
Hi,

Wendy's workaround fixed the issue:

Hey Marco, not sure if it is the same problem as yours, but I've just
 run into this NDPPP error (Unknown correction type: bandpass) using the
 prefactor target pipeline in the master branch.
My solution was to set the h5parm variable in the Pre-Facet-Target
parset
It
 wasn't set, so the generic pipeline was trying to run NDPPP with 
parameters like applybandpass.parmdb={{ h5parm }}. Strange though that 
the error appears on applybandpass and not the first occurrence on 
applyclock...


Issue could be closed






>>> adrabent <notifications@github.com> 09/21/18 4:00 PM >>>
Please check if the fix has resolved the issue.
