### ISSUE TITLE
What should the final prefactor3.0 products be?

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#184]
Presently the products from prefactor3.0 are msfiles from each of 10sb chunks with DATA and CORRECTED_DATA. There is also a h5parm with all the solutions

Why dont we change this by adding a step at the end that simply takes CORRECTED_DATA (using msout.storage.manager=dysco) from each 10sb block and putting this into a new file. These new files would then be the final products and would be much smaller than the existing products.

I know this is incompatible with FACTOR at present. But, in the short term, one could easily make it compatible again by artificially redoing the GSM cal to create a new CORRECTED_DATA column if you wanted to do so.

**Comment by twshimwell** [comment]
(ddf-pipeline does not need the DATA column at all)

**Comment by twshimwell** [comment]
Can init subtract not work on the corrected_data column?

**Comment by darafferty** [comment]
Yes, but Factor expects the SUBTRACTED_DATA_ALL column to be uncorrected (e.g., it corrupts the models with the dir-indep soutions before adding/subtracting them). I guess we could change Factor instead, but aren't there are some advantages to using the uncorrected data in selfcal (e.g., fewer free parameters)?

**Comment by twshimwell** [comment]
Would changing factor be a lot of work though?

Yeh im not sure about the advantages. I think we have always thought that indeed working on the uncorrected data is more pure to e.g. get TEC values. But im not sure in practice how much difference it makes (assuming the model you used to make CORRECTED_DATA was ok).

**Comment by rvweeren** [comment]
What about provide:

-a one column ms that contains the applied bandpass, offsets, clocks (bit not the GSM cal) + final/full h5parm from the calibrator.
-provide the H5parms from the GSM cal.

(if you want to use the GSM call, there is only one NDPPP applycal needed which is trivial)

Alternatively,

-a one column ms that contains the applied bandpass, offsets, clocks, + GSM cal + final/full h5parm from the calibrator + GSM cal H5parm.

With the H5parm in hand it would in principle be possible to undo the GSM applycal (by applying the 1/solutions, although mathematically that is not very stable, but doing it once should be ok....).

**Comment by adrabent** [comment]
To answer this question we should think about the use case.
If a user asks for an observation and would like to get the "prefactor"ed data from an archive:
Do we want that the user always needs to apply GSM-cal solution manually if the user wants to do some basic-imaging or whatever afterwards or should the data set be "ready-to-go".

**Comment by darafferty** [comment]
Right -- keep in mind that it is the RO's plan to also make and archive the basic image after GSM cal, which I think would usually be what the average user would be after (if they're interested in the calibrated data in the first place)

**Comment by adrabent** [comment]
Ya.. but this image is created using the `CORRECTED_DATA` column only

**Comment by darafferty** [comment]
Yeah, I mean that the fact that the image will be archived will obviate the need to archive the corrected data for most users (at least that's my theory...).

**Comment by twshimwell** [comment]
Seems like an odd thing to archive...

**Comment by adrabent** [comment]
But the user might and will probably want to re-image the data with different settings.

**Comment by rvweeren** [comment]
Note that having a "corrected" ms that user can directly image is not that important I think. For science purposes this data is of little use (even the image is only useful as a quality control product under most circumstances). The whole point of pre-factor is that is the starting point of DD calibration, hence the name "pre" (not some final science output).

**Comment by rvweeren** [comment]
We should not forget that there are no real science cases for the output of prefactor, it is just a preparation step.

**Comment by twshimwell** [comment]
So maybe we are converging on keeping:

-a one column ms that contains the applied bandpass, offsets, clocks, + GSM cal + final/full h5parm from the calibrator + GSM cal H5parm.

(so a dyscod version of the CORRECTED_DATA column of the present prefactor final product)

**Comment by twshimwell** [comment]
but not if that creates a lot of work for FACTOR or anything else...

**Comment by adrabent** [comment]
Factor does not need to have the uncorrected column anymore.
So we now have decided to keep the corrected and compressed column only.

All solutions are stored in a single h5parm.
