### ISSUE TITLE
Robustness against station mismatch target data and calibration solutions.

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#185]
Currently the pipeline will crash if there are stations in the data that are not in the calibration solutions, e.g. on the RMextract step. This is probably an exotic situation, but it might be useful if the pipeline checks, as first step, the stations and removes stations that are not in the calibration solutions from the measurement sets.

For example, I have to mix and match calibrators with the NCP field, and in some cases this results in the calibration missing e.g. CS0013, while it is present in the target.

**Comment by tikk3r** [comment]
It happens here, in `add_RMextract_and_times_to_H5parm.py`, so just after the RMextract step if I'm not mistaken:
https://github.com/lofar-astron/prefactor/blob/0864dadb4d8b688f5d1fc28f1f0ddeddfec75516/scripts/add_RMextract_and_times_to_H5parm.py#L125-L134

**Comment by adrabent** [comment]
Have you tried again whether the station is now properly flagged?

**Comment by tikk3r** [comment]
Not yet. This data is on the grid where we still run prefactor 2 (but hopefully soon move to Singularity and then prefactor3).
