### ISSUE TITLE
library not found

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#188]
Hi,

I just tried running the latest prefactor with the latest lofar software. After a couple of hours it crashes with

`libdppp_ddecal.so: cannot open shared object file: No such file or directory`

I noticed once, without using prefactor, that when I used NDPPP with steps  = [avg] and forgot to define the type of avg, it also crashed with the error that libdppp_avg.so was not found.

Is this similar?
There is the line
`calib_cal.argument.solve.type                        =   ddecal`
in the Prefactor calibrator parset that is shipped with the latest prefactor version from here.
Is ddecal maybe missspelled?

Thx.

**Comment by adrabent** [comment]
`ddecal` is quite a new operation.
Do you run the latest LOFAR software? You might need to install the current `trunk` version.
@tammojan is `ddecal` already available in the latest LOFAR software stable release?

**Comment by amisk** [comment]
I did an svn checkout of  https://svn.astron.nl/LOFAR/branches/LOFAR-Release-3_2 LOFAR

**Comment by adrabent** [comment]
Hmm.. this seems to be quite a recent release.
You could also try to checkout the [LOFAR SVN trunk](https://svn.astron.nl/LOFAR/trunk/).

Nevertheless, please check whether the library is installed or not:
`ls $LOFARROOT/lib64/libdppp_ddecal.so`

**Comment by amisk** [comment]
I checked out the trunk and there is no libdppp_ddecal.so inside, also not in the 3.2 release.

**Comment by aroffringa** [comment]
In the LOFAR trunk, ddecal is not build when Armadillo is not found. The cmake process mentions this when you run it. So you probably have to install the Armadillo lib and recompile the LOFAR repos.

The "next" DPPP, which was forked from the LOFAR repos, has already solved a lot of these issues (but is not released as a stable version yet, it needs a bit more testing).

**Comment by tikk3r** [comment]
Is SuperLU installed? That's a requirement for armadillo, though I guess installing libarmadillo-dev will install that as a dependency.

What is your full cmake command? The ddecal part built succesfully for me with lofar 3.2.2 (although I have built Armadillo from source). Perhaps try pointing, even though it is found, CMake directly to your armadillo library by passing -DARMADILLO_LIBRARY=/path/to/libarmadillo.so and -DARMADILLO_INCLUDE_DIR=/path/to/armadillo/include.
It may also be worth inspecting the logs (save the make output to a file, e.g. `make | tee log.txt`), maybe there's something else besides finding the library that's off?

**Comment by amisk** [comment]
This is my cmake command

`cmake -DCASACORE_ROOT_DIR=/opt/soft/lofar-stuff -DWCSLIB_ROOT_DIR=/opt/soft/lofar-stuff -DBUILD_TESTING=NO -DBUILD_SHARED_LIBS=ON -DUSE_OPENMP=ON -DBUILD_PACKAGES="Offline" -DCMAKE_INSTALL_PREFIX:PATH=/opt/soft/lofar-stuff ../../LOFAR/`

I also installed superlu3, but to no effect.

**Comment by tikk3r** [comment]
Hmm looks alright to me, similar to mine. Since you said cmake succeeds in finding everything, I think looking through make's output for/around the ddecal part has the best chance of finding any potential issues.

**Comment by amisk** [comment]
Hey, sorry for the delay.
I uploaded the log files of cmake and make. Maybe you can find the reason.
https://my.pcloud.com/publink/show?code=kZJdMM7ZtDiEqgovrbF2thTc6KkjmFlu7ifk

**Comment by aroffringa** [comment]
It appears your cmake decides not to build ddecal, but there's no clue as to why, which is weird because, for the LOFAR trunk, cmake should output messages that should give you the reason why.  

I see you're not building inside a directory called 'gnucxx11_opt', but you're building in 'gnu_opt' instead. This will in any case disable ddecal, so that's one thing you'll have to do. However, it might be that more is wrong because that would normally lead to a warning, which I don't see in your log.

With packages do you actually ask to be built? Can you put DPPP_DDECal as the only package in there? (it is enough to specify DPPP and DP3, but listing it explicitly and as the only package to build might isolate a bit better where things are going wrong).

**Comment by amisk** [comment]
Why does the directory name make difference?

I am using the cmake command as shown above. I had a look into the possible options for building using ccmake, but I did not see any flag to explicitly enable ddecal.

**Comment by aroffringa** [comment]
In the LOFAR build system, the choice of enabling c++11 is made depending on the directory name, and DDECal depends on c++11. 

I see your building Offline -- which is fine, as it depends on CEP, which includes DP3 and thereby should give warnings if it decides not to build DDECal. In any case, try building in the correct dir name, as maybe that solves it... Despite that I don't understand where the warning went.

**Comment by amisk** [comment]
We're getting closer:
[ 96%] Built target dppp_ddecal
make: *** [all] Fehler 2

Lets see if I see somtething somewhere...

**Comment by aroffringa** [comment]
Since it says it failed, make must have produced an error earlier on, which will be in the output somewhere.

**Comment by amisk** [comment]
Maybe casarest is too old? Or maybe I do need to recompile again in a gnucxx11 directory?

```
In file included from /opt/soft/lofar-stuff/BuildDir/lofarsoft/LOFAR/CEP/Imager/LofarFT/src/LofarCubeSkyEquation.cc:61:0:
/opt/soft/lofar-stuff/include/casarest/synthesis/MeasurementComponents/nPBWProjectFT.h:162:5: error: looser throw specifier for ‘virtual casa::nPBWProjectFT::~nPBWProjectFT() throw (casa::AipsError)’
     ~nPBWProjectFT();
     ^
In file included from /opt/soft/lofar-stuff/include/casarest/synthesis/MeasurementEquations/SkyEquation.h:37:0,
                 from /opt/soft/lofar-stuff/BuildDir/lofarsoft/build/gnucxx11_opt/include/LofarFT/LofarCubeSkyEquation.h:30,
                 from /opt/soft/lofar-stuff/BuildDir/lofarsoft/LOFAR/CEP/Imager/LofarFT/src/LofarCubeSkyEquation.cc:51:
/opt/soft/lofar-stuff/include/casarest/synthesis/MeasurementComponents/FTMachine.h:126:11: error:   overriding ‘virtual casa::FTMachine::~FTMachine() noexcept (true)’
   virtual ~FTMachine();
           ^
In file included from /opt/soft/lofar-stuff/BuildDir/lofarsoft/LOFAR/CEP/Imager/LofarFT/src/LofarCubeSkyEquation.cc:62:0:
/opt/soft/lofar-stuff/include/casarest/synthesis/MeasurementComponents/AWProjectFT.h:169:5: error: looser throw specifier for ‘virtual casa::AWProjectFT::~AWProjectFT() throw (casa::AipsError)’
     ~AWProjectFT();
     ^
In file included from /opt/soft/lofar-stuff/include/casarest/synthesis/MeasurementEquations/SkyEquation.h:37:0,
                 from /opt/soft/lofar-stuff/BuildDir/lofarsoft/build/gnucxx11_opt/include/LofarFT/LofarCubeSkyEquation.h:30,
                 from /opt/soft/lofar-stuff/BuildDir/lofarsoft/LOFAR/CEP/Imager/LofarFT/src/LofarCubeSkyEquation.cc:51:
/opt/soft/lofar-stuff/include/casarest/synthesis/MeasurementComponents/FTMachine.h:126:11: error:   overriding ‘virtual casa::FTMachine::~FTMachine() noexcept (true)’
   virtual ~FTMachine();
```

**Comment by aroffringa** [comment]
I don't know, the LofarFT stuff is not well maintained. I think it is part of AWImager. If you don't use it you can just disable it (e.g. I always compile with: `-DBUILD_PACKAGES="DPPP DP3 StationResponse BBSControl ParmDB pyparmdb` )

**Comment by rvweeren** [comment]
It seems this is a sleeping thread. Reopen if needed.
