### ISSUE TITLE
latest release incompatible with losoto

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/prefactor#189]
Hi,

I noticed prefactor 2.0.3(.1) is incompatible with losoto 2.0 and people are reporting KERN issues about this. Losoto 2.0 has been uploaded to KERN-dev and KERN-4, making prefactor in KERN broken.

What we could do is:
 * Make a new prefactor release (3)
 * Downgrade losoto in KERN-4
 * upgrade prefactor in KERN-dev.

What do you think? When can we expect a prefactor 3.0?

**Comment by adrabent** [comment]
I am not sure whether a new prefactor release is really preferrable, since most of the development is put into v3.0 and only basic maintenance is done.
But if the current master is stable enough we could release it.

@darafferty is the current master compatible to factor? I guess it is so.

**Comment by darafferty** [comment]
Yes, Factor is compatible with the current master, so we can do a new release (I think @tammojan already made a prerelease last week).

**Comment by darafferty** [comment]
Ah, I see the prerelease was not made against the current master, so we should indeed make a new one. I would say that the new version should be called v2.1, since there were quite a few changes since the last release.

**Comment by revoltek** [comment]
we are fixing the last things before a release of losoto 2.1

**Comment by gijzelaerr** [comment]
this is still an issue. I'm currently rolling out KERN-5, what shall I do?

**Comment by adrabent** [comment]
The current master branch is compatible with losoto 2.0
Are there still issues rolling it out in KERN-5?

**Comment by gijzelaerr** [comment]
yes, losoto/prefactor depends on the python lofar software, but this has not been ported to casacore 3 yet: https://github.com/kernsuite/packaging/issues/181

**Comment by adrabent** [comment]
Any news about these compatibility issues?

**Comment by gijzelaerr** [comment]
hi @adrabent  ! sorry for the delay in answer. We managed to get losoto and prefactor working, I've uploaded a package to KERN-6.

thanks
