### ISSUE TITLE
When running prefactor-cwl on a non-test dataset: libcasa_lofarstman.so.2: cannot open shared object file

### ISSUE THREAD

**Issue by HannoSpreeuw** [lofar-astron/prefactor#190]
Running [prefactor-cwl](https://github.com/EOSC-LOFAR/prefactor-cwl) on anything else than a test dataset downloaded using e.g.
`make small`
results in [this error](https://github.com/EOSC-LOFAR/prefactor-cwl/issues/23#issuecomment-429770468):

> libcasa_lofarstman.so.2: cannot open shared object file

Allegedly, this could be attributed to an error in prefactor, that's why I posted it here.

Is someone on the prefactor team willing to run prefactor-cwl with a measurement set different from any of its test datasets to reproduce the error?

**Comment by apmechev** [comment]
I had the same issue when the dysco shared library is named *so.0 
My (temporary) workaround was 
`ln -s /usr/lib/libdyscostman.so.0 ~/libdyscostman.so
export LD_LIBRARY_PATH=$HOME:$LD_LIBRARY_PATH`

This assumes your dysco library is in /usr/lib

**Comment by aroffringa** [comment]
Do you have to do this to process _any_ Dysco data set? If so, then it is not a Prefactor error but something might be wrong in the setup script of Dysco (or it might be installed incorrectly). In that case I'd be happy to hear how Dysco was configured (feel free to open a bug at https://github.com/aroffringa/dysco in that case).

**Comment by HannoSpreeuw** [comment]
@apmechev I followed your instructions, but the error persists. 
Possibly because the ```make run-singularity``` command from `prefactor-cwl` deploys containers and the addition to LD_LIBRARY_PATH should be done from within the container.

I have now done this in the bash shell from which I enter ```make run-singularity```.

**Comment by gijzelaerr** [comment]
https://github.com/kernsuite/packaging/issues/96

If I remember correctly, a workaround is to install the `lofar-dev` package. The error is caused by (I guess) dp3 or some related program during runtime dynamically loading a shared library with a fixed SO number (2), while we packaged everything with SO version 0. In Kern-dev we now set everything to SO version 2 because of this pain.

**Comment by adrabent** [comment]
Please try the new prefactor version: https://git.astron.nl/eosc/prefactor3-cwl
