### ISSUE TITLE
[Prefactor v3.0] h5imp_RMextract numpy IndexError

### ISSUE THREAD

**Issue by mooneyse** [lofar-astron/prefactor#192]
The `Pre-Facet-Target.parset` pipeline crashes on the `h5imp_RMextract` step (so very early in the pipeline) on the Prefactor version 3.0 branch. I tried running the `createRMh5parm.py` script outside the pipeline on one of my measurement sets with 
```
python ./createRMh5parm.py --all L572667_SB000_uv.MS cal.h5
```
and I got the following error:
```
Traceback (most recent call last):
  File "/data5/sean/home/github/github/new-prefactor/asdf/prefactor//scripts/createRMh5parm.py", line 170, in <module>
    earth_rot=args.earth_rot)
  File "/data5/sean/home/github/github/new-prefactor/asdf/prefactor//scripts/createRMh5parm.py", line 109, in main
    rm_vals=np.array([rmdict["RM"][stat] for stat in station_names])[:,:,0]
IndexError: too many indices for array
```
By changing the `[:,:,0]` on this line:
https://github.com/lofar-astron/prefactor/blob/a6a1c630d954af167c2a3527e269ecb1407d88c1/scripts/createRMh5parm.py#L109
to `[:,:]`, it works.

**Comment by adrabent** [comment]
So, it doesn't crash if you run it within the genericpipeline?
We had a similar issue there, which has been fixed in RMextract.
Are you running the most recent version of RMextract?

Alex

**Comment by mooneyse** [comment]
It was crashing inside the pipeline too -- but editing the `createRMh5parm.py` resolved it. I have RMextract installed through KERN, which is version 0.1. OK if you haven't come across this before, I can dig deeper into it on my side.

**Comment by maaijke** [comment]
I do not understand how the number of axes could be different when using the new RMextract, I updated the createh5parm code and will create  a new release, such that the code is updated anywhere.

**Comment by mooneyse** [comment]
OK I will find out what is going on specifically.

**Comment by mooneyse** [comment]
Alright so in the shebang for `createRMh5parm.py` it specifies Python 3, but for me the pipeline was using my default Python installation which is 2.7. Changing to Python 3 fixed this issue.
