### ISSUE TITLE
demixing needs to be an option at some point

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#193]
Currently we only employ Ateam clipping, in a future release we need to have the option to demix so just opening an issue for it so we do not forget.

 (we have HBA datasets for which Ateam clipping is not sufficient , for LBA it is always required but usually it already run by the RO)

**Comment by twshimwell** [comment]
I think this is becoming increasingly important. Perhaps for this to run easily in the pipeline I guess the smart demix thing would need to be revisited because otherwise it might be a little clunky with the user always deciding what sources to demix.

**Comment by adrabent** [comment]
https://github.com/lofar-astron/prefactor/commit/46625c3e52ca8bc152fff229c0e93dd00a02ac96
