### ISSUE TITLE
Folder has +x flag, but "Invalid value" error persists

### ISSUE THREAD

**Issue by HannoSpreeuw** [lofar-astron/prefactor#197]
Running prefactor - from a Singularity container - persistently gives

>   ../../../lofar/bin/NDPPP is an invalid value for ExecField executable

`chmod -R +x ../../../lofar/bin` does not make a difference.

**Comment by adrabent** [comment]
To my knowledge this error only occurs in two cases:

- the executable called has no executable flag set
- the executable called does not exist

Unfortunately I can not have a look into your Singularity image, but for whatever reason the `genericpipeline` does not "see" an executable DPPP. Could you check the flags with `ls -ltad` or anything similar? Does the user calling `genericpipeline` has full read-access to all directories of the LOFAR software?

**Comment by tikk3r** [comment]
The `chmod -R +x ../../../lofar/bin` most likely wouldn't help anyway, as Singularity images are not writable unless explicitely set during build. So as @adrabent says it's either permissions or the path itself. Try using the absolute path instead of a relative one.

**Comment by HannoSpreeuw** [comment]
Thanks,  I used absolute paths, but didn't want to include the fulll path in this issue.
`ls -ltad ../../../lofar/bin`
and
`ls -ltad ../../../lofar`
both give a 777 permission:

>   drwxrwxrwx 2 hanno hanno

**Comment by tikk3r** [comment]
And the executables inside the bin folder?

**Comment by HannoSpreeuw** [comment]
Sorry, see my comment above. I just edited it. There are no executables left.
>  Apparently, the NDPPP executable is removed by the container after its failed attempt to execute NDPPP.

**Comment by tikk3r** [comment]
It probably didn't exist in the first place, giving you that error. Maybe the LOFAR software didn't install successfully. Do the other things like lib64 exist in the lofar folder?

**Comment by HannoSpreeuw** [comment]
No, it only made a `var` folder within the lofar folder with a `log` subdirectory and a .log file wthin that subdirectory.

**Comment by tikk3r** [comment]
I don't know about the setup, but it looks like the installation failed then as there should be a bunch of folders like `bin`, `lib64`, `include` etc.

**Comment by HannoSpreeuw** [comment]
Yes. But no clue why that failed.
