### ISSUE TITLE
sky_cal finds Ateam skymodel instead of 3C295

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#199]
In the sky_cal step find_skymodel_cal.py is returning the Ateam skymodel as the calibrator model instead of 3C295 -- 3C295 appears in Ateam_LBA_CC.skymodel which happens to come first in my glob listing of {{ prefactor_directory }}/skymodels so it is being picked up and returned before it gets to the 3C295 model...

https://github.com/lofar-astron/prefactor/blob/e6117449a1f6d3811a056d4194d30bc7518691f7/scripts/find_skymodel_cal.py#L70

I can strip out the Ateam models fairly easily from the list

    skymodels = glob.glob(PathSkyMod + "/*" + extensionSky)
    
    # remove any Ateam models from the listing
    skymodels = [s for s in skymodels if 'Ateam' not in s]
    skymodels = [s for s in skymodels if 'A-Team' not in s]

**Comment by wllwen007** [comment]
A similar issue this time with 3C196 and Calibrators_SH_lowres.skymodel

One can add another line to find_skymodel_cal to exclude Calibrators_SH_lowres.skymodel
    `skymodels = [s for s in skymodels if 'Calibrators_SH_lowres' not in s]`

But maybe it would be better to put the calibrators in a subdirectory?

What is Calibrators_SH_lowres.skymodel used for? this file is a bit confusing because it contains calibrators and Ateam sources...

**Comment by adrabent** [comment]
I think the main issue is that they are several skymodels for the same calibrator and there is no clear algorithm to decide which one to prefer.
I would like to propose, at least in case of the default calibrators, to define one calibrator model for a particular 3C source and remove the others from the directory. If these duplicate models are REALLY needed we could put them into a special sub-directory for manual use.

**Comment by wllwen007** [comment]
Agreed.

The other issue is that if a calibrator appears in a skymodel with other
sources,  prefactor doesn't know this and does a predict then solve with
all the sources in that skymodel :-/

**Comment by wllwen007** [comment]
> I would like to propose, at least in case of the default calibrators, to define one calibrator model for a particular 3C source and remove the others from the directory. If these duplicate models are REALLY needed we could put them into a special sub-directory for manual use.

Can we remove `Calibrators_SH_lowres.skymodel` from this directory now? The calibrators included in this file (all single components) are all also included as single source skymodels which are identical except for 3C196 and 3C295 where we have 4-component and 2-component models (`3C196-pandey.skymodel` and`3c295-twocomp.skymodel`) also ~ on the Scaife&Heald fluxscale and should be the preferred models to use  as far as I know.

In my case, it should be using the 4-component model for 3C196 and instead it is picking the single component model in `Calibrators_SH_lowres.skymodel` (at least it is only predicting 3C196 now, but it is the wrong model, especially for the most remote stations)

**Comment by adrabent** [comment]
Is your issue resolved?

**Comment by adrabent** [comment]
I assume this issue at least temporarily resolved. We might want to open a new issue in case of related issues.
