### ISSUE TITLE
ndppp_prep_target not working in v2.0-devel?

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#20]
The v2.0-devel version of pre-facet-cal does the transfer of clock and gain now in the first ndppp step before averaging, but it the pipeline keeps failing this ndppp step. I think the reason is that it is not getting the right msout -- all the bands are trying to output to the same file (instrument_amp_clock_offset.ndppp_prep_target in the pipeline-products directory) instead of something like L343224_SB127_uv.dppp.ndppp_prep_target. The pipeline log shows the msin and msout as
msin=/data/lofar/wwilliams/survey_cal/dry_run/P214p55/L343224//L343224_SB000_uv.dppp.MS
msout=/car-data/wwilliams/pipeline-products/pfc_L343224_v2_devel/instrument_amp_clock_offset.ndppp_prep_target

Is this something to do with the output (/instrument_amp_clock_offset) in the previous step parmmap step?  I don't know how to fix this in the pipeline context - it should take the createmap_target mapfile from the target_input_path directory (msin) and map it to some sensible output in the pipeline working directory for ndppp (msout) and not involve the parmdb name.

**Comment by AHorneffer** [comment]
That's a bug in the genericpipeline. I think it is fixed in the current version of the LOFAR software. But I can also put in a workaround in the pipeline parset.

**Comment by AHorneffer** [comment]
So, if I didn't screw up in this quick fix, it should work now.

**Comment by wllwen007** [comment]
Works now - thanks!

A workaround in the parset is probably better at this point as many of us are not using the latest LOFAR version.
