### ISSUE TITLE
predict_cal not used?

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#200]
I may be mistaken but it seems to me that the predict_cal step is not used as the calib_cal step is using the sourcedb directly and not using the already predicted MODEL_DATA column (with `solve.usemodelcolumn=True`) from the earlier predict_cal step ... so each time calib_cal runs, it is redoing the same predict.

https://github.com/lofar-astron/prefactor/blob/f45da871ea33fe0f3f7f2d5645c03a1b12453e2c/Pre-Facet-Calibrator.parset#L349-L370

**Comment by adrabent** [comment]
Indeed. Thanks for spotting this.
It will be changed with the next update.

**Comment by adrabent** [comment]
Commit https://github.com/lofar-astron/prefactor/commit/5d362286469d330885ad54e42df8da52c55a40fb resolved this issue as well.
