### ISSUE TITLE
[version3.0] Calibrator parset missing comma

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#201]
In the calibrator parset,

https://github.com/lofar-astron/prefactor/blob/cc7008786c4ee3d6ef0878cdb3930e7f266adb03/Pre-Facet-Calibrator.parset#L194

I think `{{ initial_flagging }},{{ demix_step }}interp,avg` should be `{{ initial_flagging }},{{ demix_step }},interp,avg`?

**Comment by adrabent** [comment]
I guess this additional comma might lead to the exception raised in #202

**Comment by tikk3r** [comment]
Nothing wrong, see #202.
