### ISSUE TITLE
[version3.0] Optional demix errors when set to none

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#202]
In relation to #193 and #201, I'm trying to run the calibrator parset with https://github.com/lofar-astron/DP3/commit/a95f889f0bd6065d259ea67fd5d9ac561a65cc13, but I'm having trouble when I set the `demix_step = {{ none }}`. I see the following errors pop up during `ndppp_prep_target`:
```
2018-12-19 14:55:16 WARNING node.lofar6.strw.leidenuniv.nl.executable_args.L427096_SB013_uv.dppp.MS: /net/lofar1/data1/sweijen/software/LOFAR/latest/lofar/bin/NDPPP stderr: 
std exception detected: Shared library  not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
libdppp_.so: cannot open shared object file: No such file or directory
libdppp_.so: cannot open shared object file: No such file or directory
```

If I remove `{{ demix_step }}` from `ndppp_prep_target.argument.steps` it starts the preparation step properly.

**Comment by adrabent** [comment]
It looks like `DPPP` is trying to call an empty step, e.g., `steps=[,]`.
This will lead to an exception like this:

`terminate called after throwing an instance of "casa::AipsError"
  what():  Shared library  not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
libdppp_.so: cannot open shared object file: No such file or directory
libdppp_.so: cannot open shared object file: No such file or directory`

Please make sure that the `! none`  is actually empty and that there is no comma after `{{ demix_step }}`

**Comment by tikk3r** [comment]
In my parset it is set to `! demix_step               =  {{ none }}`, but it appeared to still be executing the demix step, which is why I tried this.

**Comment by tikk3r** [comment]
Ok never mind, I was just a bit confused by the output showing the `demix` in the list of parameters (as normal), but they're not used. Everything's fine, my bad!
