### ISSUE TITLE
skip_international doesn't do what is intended ...

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#205]
I had a discission with @adrabent about this, but when running the calibrator parset the international stations are sometimes flagged.  The newest version of the parset has a "skip_international" variable, but this doesn't actually fix the problem -- at least not in my case.  The international stations are still being flagged. I'll re-run with the flagbp step taken out just to confirm this is where it is still happening.  

Output from a calibrator run on 8 January (my version of prefactor version3.0 was updated this morning).

![ampbflag_polxx](https://user-images.githubusercontent.com/7126374/50837286-2aa23e80-1353-11e9-925c-5616f1830fa4.png)
![ampaflag_polxx](https://user-images.githubusercontent.com/7126374/50837290-2c6c0200-1353-11e9-8d2a-45ec2b1dfdab.png)

**Comment by rvweeren** [comment]
seems to be some of the automatic losoto bad station detection code that causes this

**Comment by lmorabit** [comment]
Yes, I've been skipping this step because of it but I knew there was going
to be a fix... I thought the new 'skip_international' variable was meant to
solve this, but it doesn't.

**Comment by darafferty** [comment]
Are you using the latest version of losoto (master branch)? The skip option was added about a month ago.

**Comment by tikk3r** [comment]
It seems to work as intended for me using the latest prefactor and losoto.

**Comment by lmorabit** [comment]
@darafferty yes, sorry, I am still crawling out of post-holiday fog I guess.  I haven't updated losoto in a while, I'll try that.

**Comment by adrabent** [comment]
@lmorabit  Is your issue solved?

**Comment by lmorabit** [comment]
yes, thanks.
