### ISSUE TITLE
gsmcal_tec step is not direction-independent

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#210]
The gsmcal_tec step is doing a direction-dependent solve with each source in the sourcedb a different direction (>200 directions!!). Should this not be a regular dppp gaincal step with caltype=tec? (or the sky model needs to be manipulated to put all the sources in one patch)

**Comment by adrabent** [comment]
I just checked Francesco's pipeline for LBA and he uses DDEsolve for TEC.
But beforehand the pipeline is putting the skymodel into the `MODEL_DATA` column.
I now adapted this approach. Please let me know if this solves your issue.

Why the DDEsolver is preferred, I need to crosscheck with Francesco.

**Comment by wllwen007** [comment]
Thanks, I will test it.

I think DDEcal is actively supported while gaincal is not anymore. The phaseonly solve could also be done with ddecal.

**Comment by darafferty** [comment]
@adrabent: maybe a better way in this case is to group the sky model, as it saves a read and write of the data. Since we don't do multiple solves with the same model (like we do for the calibrator), I don't see any benefit from predicting.

**Comment by aroffringa** [comment]
@wllwen007 I don't know much of the context so I might answer incorrectly; but gaincal is as supported as ddecal, though ddecal has more features (even for single direction calibration), so that might be why it is used in this case. With comparable independent direction calibration tasks, gaincal is faster though, so gaincal certainly doesn't need to be avoided.

**Comment by lmorabit** [comment]
One of the things to consider for the pipeline is that ddecal will write an h5parm with an extra axis -- direction -- so instead of, e.g., [ant,freq,time,pol] you get [ant,dir,freq,time,pol] . This can be an issue later down the line, and it has already broken some of the long baseline scripts.

**Comment by lmorabit** [comment]
> Why the DDEsolver is preferred, I need to crosscheck with Francesco.

I'm also curious to know the answer to this, I think we should stick with gaincal if there's no reason to use DDEsolver.

**Comment by wllwen007** [comment]
Thanks @aroffringa, I think it is used here for the additional features specifically for the tec solve. Good to know gaincal is still supported. I did wonder about the speed difference.

>One of the things to consider for the pipeline is that ddecal will write an h5parm with an extra axis -- direction -- so instead of, e.g., [ant,freq,time,pol] you get [ant,dir,freq,time,pol] . This can be an issue later down the line, and it has already broken some of the long baseline scripts.

The solves for the calibrator are all ddecal ... with a single direction. @lmorabit I may be wrong, but I hadn't noticed the extra dir axis when I was looking at my calibrator solutions.

**Comment by tikk3r** [comment]
It makes sense though, I think, to have a direction tab present anyway, whether one solves in 1 or 100 directions. Even the direction-independent solve still is in some direction. Scripts can just check whether or not it's present. Maybe it might be nice for consistency if they'd produce an h5parm with the same structure for a single direction solve, however.

**Comment by lmorabit** [comment]
@wllwen007 ah you're right. I should have double checked before commenting.  I had some issues with this with the Pre-Facet-Calibrator parset but I'm sure that's changed a bunch of times in the last week that I've been ill. 

@tikk3r Whether or not we include 'dir' as an axis, you're absolutely right, we need to be consistent.

**Comment by revoltek** [comment]
I recently moved to DDEcal everywhere in the calibrator (note that the first solves are with the rot matrix and we need DDEcal) to use some of the new features that @darafferty  added to that solver. The difference, as Leah noticed, are in the added axis (and that step is slower by a factor of 2 or so).

For the tec solving we *need* to use the DDEsolver everywhere (at least in LBA) or the phase jumps in the bandpass would kill us.

**Comment by adrabent** [comment]
@darafferty .. this is a good hint. I will make the changes accordingly.
