### ISSUE TITLE
updateweights

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#214]
I'm a bit confused why updateweights is now False for the Target pipeline. This used to be True for prefactor2.

The docs suggest setting updateweights to True for LBA and False for HBA (False is the default setting in the parset now).

**Comment by wllwen007** [comment]
> The docs suggest setting updateweights to True for LBA and False for HBA (False is the default setting in the parset now).

I would almost expect it to be the other way around, especially if the weights are updated also by BLsmooth for LBA (but they don't seem to be as far as I can tell)

**Comment by revoltek** [comment]
BLsmooth has the option to update weights but I tend not to touch them (too many complications if you re-run something twice). In LBA weights needs to be "reversed" so you need 2 updateweights (1 for the beam and 1 for the bandpass). In HBA I don't know in which way weights are set, I believe DDFacet re-set them.

**Comment by wllwen007** [comment]
Ok, the LBA case makes sense then. But HBA could still update them (unless someone knows a specific reason for not doing this), though perhaps it is less important because of the smoother bandpass. Yeah, DDFacet in the pipeline is currently ignoring them (but DDFacet can use them)...

**Comment by rvweeren** [comment]
HBA should follow factor2 unless there was a good reason behind it to not to follow it. Why was this changed from factor2?

**Comment by rvweeren** [comment]
I check and last summer updateweights was still true twice.... (as it should be I think for HBA so I am very surprised this was changed, also in the production version)
