### ISSUE TITLE
provide TGSS catalog with prefactor?

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#215]
https://github.com/lofar-astron/prefactor/blob/6efd6b4160659c22b4ffade943cc53e8e0e26bed/scripts/download_skymodel_target.py#L117

Prefactor crashes if the TGSS server is not online (which happens too often). Can we include the TGSS sykmodel with prefactor? So we can run prefactor without relying on the TGSS catalog server (ASTRON VO) being online?

**Comment by adrabent** [comment]
This could be an option.
On the other hand it might be even simpler to have some mirrors of the databases, so if one fails you will have at least one backup for access.
