### ISSUE TITLE
Missing file in 2.1?

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#217]
Hi,

Im trying to process the data from LOFAR 2018 School. The file convert_fits_image_to_casa.py seems to be missing. If I copy this file from Factor, the pipeline continues, but later it crashes at:

> 2019-03-01 13:01:40 INFO genericpipeline: Beginning step expand_sourcedb_high_deep
> 2019-03-01 13:01:40 ERROR genericpipeline: *******************************************
> 2019-03-01 13:01:40 ERROR genericpipeline: Failed pipeline run: Initial-Subtract-Deep
> 2019-03-01 13:01:40 ERROR genericpipeline: Detailed exception information:
> 2019-03-01 13:01:40 ERROR genericpipeline: <type 'exceptions.AttributeError'>
> 2019-03-01 13:01:40 ERROR genericpipeline: 'list' object has no attribute 'startswith'

Im using RMExtract 0.2, LoSoTo master and WSClean 2.6. I tried various versions of LOFAR software between and including 3.0.3 and 3.2.9.

Also, I would like to report that LoSoTo 2.0 seems to be not enought for Prefactor 2.1 (ERROR genericpipeline: /opt/lofarsoft/bin/H5parm_collector.py is an invalid value for ExecField executable), but master version of LoSoTo is able to complete this step.

Best regards,
Alex

**Comment by darafferty** [comment]
Thanks for reporting the missing script and losoto issue. As to the other error, I'm not sure what could be causing it as I've never run this pipeline myself (it's been effectively deprecated for some time and has been removed from the next version). I would recommend using the Initial-Subtract-Fast.parset instead.

**Comment by AlexKurek** [comment]
Hi,
... so I checked Fast version. It completed successfully on the same machine.
I was thinking Deep version is supposed to give better results than Fast, is it not true?
Best regards,
Alex

**Comment by darafferty** [comment]
Yes, it will likely provide somewhat better subtraction, but Factor does this anyway as it processes the facets (it improves the subtraction with the direction-dependent solutions and selfcal models) . So as long as the initial subtraction is good enough to get started, it usually works fine.

**Comment by adrabent** [comment]
Version 2.1 is no longer supported.
