### ISSUE TITLE
Overly aggressive station solution flagging?

### ISSUE THREAD

**Issue by gheald** [lofar-astron/prefactor#218]
I've run the prefactor calibrator pipeline on HBA 3C295 data from LC9_033. The solutions all look quite good, but at some point the bandpass, clock and faraday solutions are flagged for several (~18% in the case of bandpass, for example) of the Dutch stations. I'm attaching two indicative inspection plots showing what I think are quite reasonable bandpass waterfall plots (
![bandpass_polXX](https://user-images.githubusercontent.com/12065292/54125744-c9751500-4440-11e9-9708-c7d6d1e04059.png)
), but ultimately the bandpass is flagged for many stations (
![bandpass_time5027895674 002781](https://user-images.githubusercontent.com/12065292/54125755-d4c84080-4440-11e9-96b8-c1c405127568.png)
).

I can't find output in the log file that suggests _why_ this is taking place, and I don't see any obvious parameters to change in the pipeline setup. Is there something that I can adjust to avoid flagging stations that appear to be behaving well?

I'm using the latest prefactor version with a lofar software stack provided by ASTRON as a singularity container. I haven't made any changes to the pipeline configuration or settings apart from required changes related to paths, etc.

**Comment by gheald** [comment]
As an extra remark: the above behaviour is not only for 3C295, but is also similar for 3C196 from the same observing session. But, prefactor seems to produce valid bandpasses for 3C295 in a different observing session just a few days later (same project & setup). Maybe something is a bit overly fine-tuned when it comes to the flagging that's applied toward the end.

**Comment by adrabent** [comment]
Dear @gheald,

this is indeed not the intended behaviour of the bandpass step.
Could you provide the following inspection plots:
`ampBFlag_polXX.png` or `YY`
`ampAFlag_polXX.png` or `YY`
`fr_ph_polXX.png` or `YY` (since you said the ratio of flagged data was already high at the `faraday` step)?

**Comment by gheald** [comment]
Sure, here you go @adrabent (these are from the case that I initially reported)

`ampBFlag_polXX.png`:
![ampBFlag_polXX](https://user-images.githubusercontent.com/12065292/54265721-ea5c7800-45b0-11e9-9742-43be401612e0.png)

`ampAFlag_polXX.png`:
![ampAFlag_polXX](https://user-images.githubusercontent.com/12065292/54265857-2f80aa00-45b1-11e9-99ee-f880dbc7e556.png)

`fr_ph_polXX.png`:
![fr_ph_polXX](https://user-images.githubusercontent.com/12065292/54265879-3efff300-45b1-11e9-99c8-776c749a6081.png)

**Comment by adrabent** [comment]
Okay.. I guess the 18% you have reported stem from the flagged international stations. The solutions look pretty good.
Also `ampAFlag_polXX.png` shows that basically not much has been flagged in the flagging step.
So maybe something went wrong in the `INTERPOLATE` or `SMOOTH` step.

Are you working on CEP3? It would be good to dig into the solutions file to identify the error.

**Comment by gheald** [comment]
Could be - I'm not sure that I fully understand all of the percentages that are reported to be honest. I did think that I excluded the international stations from that statistic, but I could be misremembering (I tried a few things in the meantime).

I'm not doing the processing on CEP3 but I can copy the data there.
Here it is: `lhd001:/home/heald/for_adrabent/cal_solutions.h5`
I also put the log in the same directory,
`lhd001:/home/heald/for_adrabent/pipeline-Pre-Facet-Calibrator-20180315-2019-03-13T01:40:07.log`

**Comment by adrabent** [comment]
The issue we see her is just a "plotting" issue. The bandpass solution table has a time axis and just by chance the solution of first time slot has been flagged and thus not plotted.
If I take the median of all solutions I get the results back:

![bandpass_time5027895674 0](https://user-images.githubusercontent.com/19146990/54270634-20cdcf00-4580-11e9-8666-a811ca1d5e6b.png)

The station `RS306HBA` shows very low amplitudes. If you still want to include it, you might lower the `amprange` parameter in the parset.

The altered h5parm is located in:
`/home/drabent/solution_gheald.h5`

**Comment by gheald** [comment]
Aha, I see. Thanks for clarifying that. The compounded problem was that when I applied those solutions to the target data I ended up with everything flagged and a crashed target pipeline. I assumed that it was related to what I thought was an overly flagged set of calibration solutions. I'm repeating the process for another cal,target pair and will look more closely this time.

**Comment by nealjackson** [comment]
Deepika Venkattu and I have had this issue with losotoV2 on some cycle 0 data. Some of the calibrator solutions are quite hairy and a number of international stations end up flagged. I think the cal solutions are still usable (or at least better than nothing) so we have gone through a number of the steps, in particular prepare_losoto_PA.control.align, and also the earlier faraday step, setting maxResidual to 0 instead of the default 1.
