### ISSUE TITLE
add_RMextract_and_times_to_H5parm.py crashes if too many files are used

### ISSUE THREAD

**Issue by antonfj** [lofar-astron/prefactor#219]
I'm currently trying to process an observation using prefactor 2.1.
When I was tried to process the entire observation at once (2924 files), the pipeline crashed when it got to the 'trans' step where it runs the script add_RMextract_and_times_to_H5parm.py.
I tried running the script outside of the pipeline on all of the files and it gave the error 'Argument list too long'
I had to run the script on only part of the observation (380 files) to get it to run. It seems to work within the pipeline as well when run on only part of the observation.

**Comment by amisk** [comment]
I don't know at which step it happened for me, but I often also had a too many open files error. I solved by setting the limit to a very high number using 
`ulimit -Sn 1000000`

This always works for me.

**Comment by adrabent** [comment]
Yes, it is described in this FAQ article:
https://github.com/lofar-astron/prefactor/wiki/Documentation%3A-Faq#too-many-open-files

**Comment by antonfj** [comment]
> I don't know at which step it happened for me, but I often also had a too many open files error. I solved by setting the limit to a very high number using
> `ulimit -Sn 1000000`
> 
> This always works for me.

I don't think this is the issue. I've already set ulimit to be a high number but I still get an error about 'Argument list too long'
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2063382
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2063382
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by tikk3r** [comment]
Maybe this helps: https://unix.stackexchange.com/questions/45583/argument-list-too-long-how-do-i-deal-with-it-without-changing-my-command

> On Linux, the maximum amount of space for command arguments is 1/4th of the amount of available stack space.

Perhaps try increasing the stack size `ulimit -s`, if you have the rights to do that?

**Comment by adrabent** [comment]
@antonfj  Does this issue still occur?

**Comment by antonfj** [comment]
@adrabent I'm not sure. I ended up just running the target pipeline on part of the pipeline at a time to avoid getting the error. I'm also not sure if this issue occurs in prefactor 3.0 since I was using prefactor 2.1.

**Comment by adrabent** [comment]
This script is deprecated and not used anymore in the current master.
