### ISSUE TITLE
Connection refused on single machine

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#220]
Hi,

I want to apply the calibration to the target, and the step
`h5imp_RMextract`
apparently wants a ssh password for local machine, although the method is set local in the pipeline config file.

Thx.

edit: Interestingly, even after adding an sshkey, so that I can perfectly log into localhost via ssh without prompting a password, I still get 
`ERROR   node.slurm17.python_plugin: [Errno 111] Connection refused`

**Comment by adrabent** [comment]
Hi,

please check whether the following lines appear in your `pipeline.cfg`

```
[remote]
method = local
max_per_node = 40
```
and replace the `max_per_node` parameter with the number of the available threads on your machine. Then please check what cluster description file you use. You could use this `pipeline.clusterdesc`:

```
ClusterName = Local
NNodes = 1
Node0.NodeName = localhost
Node0.NodeFileSys = localhost
Node0.NodeMountPoints = /
```

This should enforce the parallel processing on the local machine.

**Comment by amisk** [comment]
In my pipeline.cfg I gave the direct link to the cluster description file:
`clusterdesc = /opt/soft/lofar-stuff/share/local.clusterdesc`
further, the remote section:
```
[remote]
method = local
max_per_node = 48
```

48 is the number of cores the machine shows using htop.

And this is the clusterdesc:
```
ClusterName = Local
NNodes = 1
Node0.NodeName = localhost
Node0.NodeFileSys = /any
Node0.NodeMountPoints = /
```
I'll try if it makes a difference if I change the NodeFileSys.

In the meantime: This file downloads the ionex files, right? I know we have some restrictions regarding ftp servers, but I can download via wget, so I assume it should also be possible for the script to download stuff.

Does this also download the skymodel? Could this have some kind of restrictions?

**Comment by adrabent** [comment]
> This file downloads the ionex files, right? I know we have some restrictions regarding ftp servers.
I am not sure what `wget` does in detail. The script tries to connect via `ftp`. If `wget` uses the same port it should work.

> Does this also download the skymodel? Could this have some kind of restrictions?
No. The skymodel is downloaded at a later step.

**Comment by amisk** [comment]
In which file is the ftp command actually used? I don't see it in createRMh5parm.py.

I think the problem is the ftp connection. It works with wget because there is a ftp proxy set.

**Comment by maaijke** [comment]
getIONEX needs to connect to external  servers to download the IONEX data

**Comment by adrabent** [comment]
Indeed.
 `getIONEX.py`  is called and uses:

```
ftp = ftplib.FTP(ftpserver)
ftp.login()
```

**Comment by amisk** [comment]
Yep, thats it ... and apparently ftplib does not support proxies...

**Comment by amisk** [comment]
Ok. I have added a function to download the IONEX files through an ftp server, which can be done optionally.

For that I changed createRMh5parm.py and the target parset file.
Can I commit here? Or send it to some one via email?

I also changed two files in the RMextract git, I will also see if I can commit the changes there in order for this to work here.

**Comment by adrabent** [comment]
You can make a pull request.

**Comment by amisk** [comment]
I'm closing this now. Issue was with our network, and solved by new commit.
