### ISSUE TITLE
Crash when demixing

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#223]
When enabling demixing, the target parset crashse for me with the following error:

```
2019-03-15 15:11:40 WARNING NDPPP stderr: NDPPP: /<path>/DPPP/src/Blob/BlobIStream.cc:76: const string& DP3::BlobIStream::getNextType(uint64_t&): Assertion `hdr.checkMagicValue()' failed.
```
This only happens when running the pipeline passing the skymodel sourcedb through the mapfile. Running a demix parset with the same settings does work outside the pipeline, and the sourcedb that the pipeline generates works both in and outside the pipeline when directly specified.

**Comment by adrabent** [comment]
There is currently a bug in the target pipeline when parsing the mapfile. I will push it soon.
