### ISSUE TITLE
Continue within step after crash?

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#224]
Hi,

ndppp_prep_targat crashed for me this morning with "std exception detected : Ressource temporarily unavailable"

If I now restart prefactor, will it redo the entire step? Because its only 14 out of 309 subbands. It would be a waste of time to redo all.
If it does not do this, is there a way? I can run the pipeline only on the 14 subbands and stop after this step. I could then copy the results to the other ones. I would just somehow mark the step as completed... is that possible?

**Comment by adrabent** [comment]
Hi @amisk 
I am afraid you will need to re-run the entire step. Unfortunately, the `genericpipeline` only continues once a step is finished. If this is not the case the **whole** step is to be redone.
The completed steps are saved in the `statefile`, which can be loaded in `numpy`. You may want to manually edit it to create a finished step. This should be possible. Unfortunately, I have never tried it myself, so I am not very sure about the correct "format".
