### ISSUE TITLE
Prefactor30beta1 IONEX issue

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#227]
Dear all,

I encountered the following issue:

> 2019-03-25 01:41:19 WARNING genericpipeline.executable_args: ERROR:root:Primary and Backup Server not responding
> 2019-03-25 01:41:19 WARNING genericpipeline.executable_args: ERROR:node.mpuls.python_plugin:local variable 'url' referenced before assignment
> 2019-03-25 01:41:19 WARNING genericpipeline.executable_args: INFO:node.mpuls.python_plugin:Total time 0.8493s; user time: 0.6520s; system time: 1.2720s
> 2019-03-25 01:41:19 WARNING genericpipeline.executable_args: DEBUG:node.mpuls.python_plugin:Start time was 1553474478.9986s; end time was 1553474479.8479s
> 2019-03-25 01:41:19 DEBUG   genericpipeline.executable_args: pyrap will be used to compute positions
> 2019-03-25 01:41:19 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('149.156.70.247', 34130)
> 2019-03-25 01:41:19 DEBUG   genericpipeline.executable_args: Successful readonly open of default-locked table /workspace/akurek/T5/data/L232875/L232875_SB120_uv.dppp.MS: 24 columns, 27937665 rows
> 2019-03-25 01:41:19 DEBUG   genericpipeline.executable_args: Successful readonly open of default-locked table /workspace/akurek/T5/data/L232875/L232875_SB120_uv.dppp.MS/FIELD: 10 columns, 1 rows
> 2019-03-25 01:41:19 DEBUG   genericpipeline.executable_args: Successful readonly open of default-locked table /workspace/akurek/T5/data/L232875/L232875_SB120_uv.dppp.MS/ANTENNA: 10 columns, 62 rows
> 2019-03-25 01:41:19 DEBUG   genericpipeline.executable_args: Successful readonly open of default-locked table /workspace/akurek/T5/data/L232875/L232875_SB120_uv.dppp.MS/ANTENNA: 10 columns, 62 rows
> 2019-03-25 01:41:19 ERROR   node.mpuls.python_plugin: local variable 'url' referenced before assignment

At the same time downloading of IONEX file is working in 2.1. The FTP server is also working in web browser.
I also tried:
`! ionex_server = None`
and got the same error, even when I copied the IONEX file to the proper directory manually.

Logs and parsets are attached here:
[issue.zip](https://github.com/lofar-astron/prefactor/files/3001447/issue.zip)

LOFARsoft: Revision 42280: /tags/LOFAR-Release-3_2_12 (latest)
RMExtract master: 4a857ebd7df2a6fc2181974fff3e7a8c9d067966 (latest)
LoSoTo master: 863cf69d02c8bbb5ba6397853e0233491e0fb55f (latest)
Prefactor master: 276958a182079a3f58130ebc44b1a67ca01a8cc7 (latest, 4 commits after 3.0beta1)

**Comment by maaijke** [comment]
This is again related to the new code with the proxyserver. If you switch off the use_proxyserver after downloading/copying the file to the right location, at least it should work. That code should be repaired/made more generic.

**Comment by AlexKurek** [comment]
How to switch it off? I tried:
`grep -R "use_proxyserver" /usr/prefactor-3.0/`
and there are no results. Also adding:
`! use_proxyserver         =  False`
to the Target parset is not working - still the same error

Best regards,
Alex

**Comment by maaijke** [comment]
According to your target parset proxyserver = None, so it should be fine. Could it be that the parset parameter is passed as a string to the python script instead as the value None?

**Comment by amisk** [comment]
Exactly, it should be proxyserver = None.

**Comment by maaijke** [comment]
Yes, but how is it passed to the script? From a previous version of the code it seems it was passed as a string. I can make a workaround for that, but that's rather ugly, I prefer that the parameter is correctly passed.

**Comment by amisk** [comment]
it is a string. As far as I can tell, everything from the parset is passed as string.

**Comment by maaijke** [comment]
So what about leaving it empty instead of setting it to "None" if you don't want to use it?

**Comment by amisk** [comment]
Then the actual check would need to look for "" instead of "None".

**Comment by maaijke** [comment]
That is what is checked for (since an empty string returns False) and how it should be in a python. See the latest commit by @apmechev

**Comment by amisk** [comment]
The version that I wrote explicitly looks for "none" to not use a proxy. Although this happens in RMExtract, not in prefactor.

**Comment by maaijke** [comment]
@AlexKurek Could you try to change 
proxyserver = None 
to 
proxyserver =
in your parset? If that works we can change the default parset here.

**Comment by apmechev** [comment]
Alternatively, the IF statement can be changed to 

`if not proxyserver or 'None' in proxyserver
`
This will keep the code backwards compatible and cover both options

**Comment by maaijke** [comment]
THis would be the ugly fix that I suggested above, Feel free to implement it. An let's hope no one  gets to the idea to define a proxy server with the string None in it:-)

**Comment by AlexKurek** [comment]
@maaijke Its working, now Im at "ndppp_prep_target" step.

**Comment by AlexKurek** [comment]
Alle the rest, including Initial-Subtract-parset, worked well and I wal later able to make an image using WSClean.

**Comment by AlexKurek** [comment]
I tested it all again with updated:
LOFAR - Revision 42335: /tags/LOFAR-Release-3_2_12
PyBDSF: 1.9.0
It worked flawlessly.
