### ISSUE TITLE
aliasing in the high2 images

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#23]
The image below shows the same region of sky (close to the end of the high2 image so a long way from the pointing centre) but for different bands. On the left is about 125MHz and on the right is about 165MHz (so as its so far down the primary beam the sources are faint on the one on the right).  Anyway, it seems that there is a large artefact on the image on the right which looks like the aliasing artefacts we are seeing in the facet images.
<img width="722" alt="screen shot 2016-04-04 at 4 33 02 pm" src="https://cloud.githubusercontent.com/assets/12065270/14251636/35de4dc4-fa84-11e5-8a19-3eb16a956492.png">

**Comment by rvweeren** [comment]
Yes, agreed! This means we have to add padding and exclude anything close to the image edges to end up in the skymodel [see this for more details](https://github.com/lofar-astron/factor/issues/40).

(we are essentially corrupting our data in prefactor now, including fake sources into the skymodel)

**Comment by rvweeren** [comment]
There is a very easy fix, only changing the wsclean call.

Current situation

- scale imsize
- trim not set

Needs to be updated to:

- scale imsize*1.6
- trim imszie

That's all (this will also works with the masking without any adjustments, as the mask needs to have the size that is given by trim)

**Comment by AHorneffer** [comment]
With commit [6d13f12](https://github.com/lofar-astron/prefactor/commit/6d13f127833c503215a22c3d2e05f62483b79ff5) I added padding to Initial-Subtract. 
It is not tested yet, please let me know if it works.

**Comment by wllwen007** [comment]
Andreas, I had just done the exactly the same thing myself so will now test yours... at first glance though I thinkn you're missing the step to pass the trim value as an argument to wsclean, e.g.
wsclean_low1.argument.trim                      =   trim

**Comment by AHorneffer** [comment]
Hi Wendy

On 2016-04-13 18:26, wllwen007 wrote:
> [...] at first glance though I think you're missing the step to pass the
> trim value as an argument to wsclean, e.g.
> wsclean_low1.argument.trim = trim

It should work as it is, when the name on an inputkey is not given anywhere
within the arguments list, then it will be added as a named argument with
its name as the argument name.
But to be consistent I'll change that tomorrow. (Any code I write today has
a good chance of being "interesting" but a small chance of being useful.)

   Andreas
