### ISSUE TITLE
BLsmooth.py fails with TypeError: No loop matching the specified signature and casting

### ISSUE THREAD

**Issue by sarrvesh** [lofar-astron/prefactor#231]
I am running the prefactor (master branch) pipeline on an LBA dataset. The calibrator pipeline fails because BLSmooth.py terminated with the following error:

```
INFO:root:Set SMOOTHED_DATA=INTERP_DATA
DEBUG:root:Working on antenna: 0
DEBUG:root:0 - 1: dist = 0.4 km: sigma=16.81 samples.
Traceback (most recent call last):
  File "prefactor/scripts/BLsmooth.py", line 139, in <module>
    dataR = gfilter(np.real(data), stddev, axis=0)#, truncate=4.)
  File "/usr/local/lib/python2.7/dist-packages/scipy/ndimage/filters.py", line 206, in gaussian_filter1d
    weights = _gaussian_kernel1d(sigma, order, lw)[::-1]
  File "/usr/local/lib/python2.7/dist-packages/scipy/ndimage/filters.py", line 144, in _gaussian_kernel1d
    phi_x = numpy.exp(p(x), dtype=numpy.double)
TypeError: No loop matching the specified signature and casting
was found for ufunc exp
```

Could you please have a look?

**Comment by adrabent** [comment]
Unfortunately, I am not able to reproduce this error.
Could you give more details about the parameters you have used or if there might be something "special" with your data set?

**Comment by wllwen007** [comment]
I've just come across this now and not sure why I've not seen it before. Also running on LBA data, but it worked before on the same data... (though I was running with different band sizes).

I have found that it seems to be because in the call to the gaussian filter  `gfilter(np.real(data), stddev, axis=0)` in `BLSmooth` that `stddev` is an array. A simple test gaussian_filter1d shows this may be a scipy version issue...

```
In [16]: from scipy.ndimage.filters import gaussian_filter1d as gfilter
In [17]: gfilter(np.ones((10,10)), np.array([1]), axis=0)
    ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-a75398fce7f9> in <module>()
----> 1 gfilter(np.ones((10,10)), np.array([1]), axis=0)

/net/para11/data2/sweijen/software/env-losoto2-para/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in gaussian_filter1d(input, sigma, axis, order, output, mode, cval, truncate)
    269     lw = int(truncate * sd + 0.5)
    270     # Since we are calling correlate, not convolve, revert the kernel
--> 271     weights = _gaussian_kernel1d(sigma, order, lw)[::-1]
    272     return correlate1d(input, weights, axis, output, mode, cval, 0)
    273 

/net/para11/data2/sweijen/software/env-losoto2-para/lib/python2.7/site-packages/scipy/ndimage/filters.pyc in _gaussian_kernel1d(sigma, order, radius)
    207     p = numpy.polynomial.Polynomial([0, 0, -0.5 / (sigma * sigma)])
    208     x = numpy.arange(-radius, radius + 1)
--> 209     phi_x = numpy.exp(p(x), dtype=numpy.double)
    210     phi_x /= phi_x.sum()
    211     if order > 0:

TypeError: No loop matching the specified signature and casting
was found for ufunc exp
```
fails with scipy 1.0.0 (numpy 1.16.0) but works on with scipy 1.1.0 (numpy 1.15.4)

**Comment by sarrvesh** [comment]
In my setup, I have NumPy 1.16.2 and SciPy 1.2.1.

**Comment by tikk3r** [comment]
Possible the script is passing a wrong type of value to `gfilter`. Looking at the documentation for `scipy.ndimage.gaussian_filter1d` the functions call singature is 
```
scipy.ndimage.gaussian_filter1d(input, sigma, axis=-1, order=0, output=None, mode='reflect', cval=0.0, truncate=4.0)
```
where `sigma` should be  a _scalar_. In @wllwen007's example sigma is passed as an array `np.array([1])`, which I can reproduce the error with. Passing it as just `1` works however (NumPy 1.16.0 and SciPy 1.2.1).

Could you both check what `stddev` is passed as? A single element ndarray would still pass the normal inequality checks. Casting to a float or something might solve the issue then.

**Comment by wllwen007** [comment]
I think it may actually be the numpy version not scipy as I initially thought, and it's the newer version of numpy that doesn't work. So I guess we need to ensure that the `stddev` argument in `dataR = gfilter(np.real(data), stddev, axis=0)#, truncate=4.)`  is a float instead of an array of length one. I think the fix would be in line 68(`freq = freqtab.getcol('REF_FREQUENCY')[0]`)

**Comment by revoltek** [comment]
Are you using the last BLsmooth from my script repository? I recall an error like that but I am not sure how I fixed it, if with an update of libraries or with a fix in the code

**Comment by adrabent** [comment]
I updated BLsmooth.py accordingly:
https://github.com/lofar-astron/prefactor/commit/f8fbc7ad787d1c30993f252b375347698009f326

**Comment by adrabent** [comment]
Does this issue still occur?
