### ISSUE TITLE
Missing libdppp_interpolate.so

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#232]
Im getting the following error:

> terminate called after throwing an instance of 'casa::AipsError'
>   what():  Shared library interpolate not found in CASACORE_LDPATH or (DY)LD_LIBRARY_PATH
> libdppp_interpolate.so: cannot open shared object file: No such file or directory

in ndppp_prep_cal step.

Versions:
LOFAR_BRANCH=tags/LOFAR-Release-3_2_12
LOFAR_REVISION=42421
Prefactor: master c7101fa580bb2c1e14fef0e74465668f4441f363 (latest)

If I do `find / -name libdppp_interpolate.so`, there are no results. Full log attached.

Best regards,
Alex
[pipeline-Pre-Facet-Calibrator-2019-04-02T08%3A18%3A36.zip](https://github.com/lofar-astron/prefactor/files/3033009/pipeline-Pre-Facet-Calibrator-2019-04-02T08.3A18.3A36.zip)

**Comment by tikk3r** [comment]
I think this happens when you try to run an unsupported step. Are you running an up to date version of DPPP?

**Comment by AlexKurek** [comment]
I had problem with Armadillo, now testing if that was the case. It is aready 2 steps further. Im sorry, thats probably my mistake.

Best regards,
Alex

**Comment by aroffringa** [comment]
The new DP3 doesn't make use of a separate interpolate library, so you're using an old DP3 version. However, the old (deprecated) DP3 will only build the interpolate library if armadillo is available, so installing armadillo should fix such an issue with the deprecated DP3 version.

**Comment by AlexKurek** [comment]
I was using DP3 from the latest full LOFAR soft instalation from:
https://svn.astron.nl/LOFAR/
is it deprecated? I was thinking it is even newer than https://github.com/lofar-astron/DP3

Best regards,
Alex

**Comment by aroffringa** [comment]
DP3 in the LOFAR repository is indeed no longer developed and misses already quite a few features. The Github version is the maintained / developed one (the situation is briefly mentioned at https://github.com/lofar-astron/DP3/blob/master/README.md ).

The same holds for the LOFARBeam library.

**Comment by AlexKurek** [comment]
I understand now, Sorry for the mix-up.
The error is fixed.

Best regards,
Alex
