### ISSUE TITLE
GSM skymodel server broken?

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#234]
The GSM site seems to be broken: for a target that previously worked I am now getting an empty skymodel.

Downloading fails with an error because it can't read the empty skymodel
```
download_skymodel_target.py --Source GSM --Radius 5. --DoDownload True L667876_SB463_uv.ndppp_prep_target  target.skymodel.gsm
```

And the actual wget it runs returns a blank file...
```
wget -O target.skymodel.gsm 'http://172.104.228.177/cgi-bin/gsmv1.cgi?coord=218.0125,34.2758333333&radius=5.0&unit=deg&deconv=y'
```

I don't know who is maintaining the GSM site at http://172.104.228.177 to report it there.

**Comment by twshimwell** [comment]
Ah right. Best to mail Alex, josh and Huib

**Comment by revoltek** [comment]
Alex discontinued his service, this is now hosted in ASTRON (I am testing it since a few days with success). Please contact Reinoud Bokhorst to use it (I think it could become public now).

**Comment by adrabent** [comment]
In the meanwhile please use the TGSS option in the parset

**Comment by rbokhorst** [comment]
The GSM service is now located at https://lcs165.lofar.eu/
Please note that it is still being tested.
