### ISSUE TITLE
gsmcal_tec turn beam on?

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#235]
Shouldn't the beam be on in the tec solve?

https://github.com/lofar-astron/prefactor/blob/d97f6ca187a83423e3b3133ea03266cb7c91a012/Pre-Facet-Target.parset#L691

```
gsmcal_tec.argument.ddecal.usebeammodel                        =   True
gsmcal_tec.argument.ddecal.onebeamperpatch                     =   False
gsmcal_tec.argument.ddecal.usechannelfreq                      =   True
gsmcal_tec.argument.ddecal.beammode                            =   array_factor

```

**Comment by rvweeren** [comment]
Yes, I think the beam should be on (in particular given that is solves from a sourcedb with true fluxes), so this seems to be a mistake.

**Comment by wllwen007** [comment]
Thanks, but I think onebeamperpatch  should be  False (or not set: default=False) since this is a solve against a wide angle gsm model with a single patch (from https://github.com/lofar-astron/prefactor/issues/210)

**Comment by adrabent** [comment]
Ah.. this is a good point.
@revoltek  .. I just cross-checked with Francesco's pipeline. There `onebeamperpatch` is also set to `True`. Is there a specific reason for that I don't see or is this is a mistake?

**Comment by adrabent** [comment]
This is the link:
https://github.com/revoltek/LiLF/blob/master/parsets/LOFAR_self/DPPP-predict.parset

**Comment by wllwen007** [comment]
I think @revoltek's works because there the skymodel has no patches set, and the ddecal step is done with the predicted model column, whereas in prefactor we set a single patch in the skymodel  so that the ddecal step (which also does the predict) doesn't set the directions to be the number of sources in the skymodel
