### ISSUE TITLE
international station bandpass prefactor3

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#239]
To get good (enough) bandpasses for the international stations the best approach is to simply copy over a reference bandpass taken from 3C48.  This is needed if the standard calibrators that are used are too resolved (3C196, 3C295). The scheme would be as follows:

IF calibrator == 3C48 or 3C147 continue as normal
(user definable list which calibrators)

ELSE
Copy over the bandpasses (nothing else, only amp bandpasses), for the international stations only (user definable list, default all international), from a reference H5 file. This is done as the last step of the calibrator pipeline. The other (dutch) stations get the bandpass in the normal way. @tikk3r will provide a reference H5 that contains the bandpass solutions of 3C48.

**Comment by tikk3r** [comment]
The H5Parm with the bandpasses can be downloaded from here: https://home.strw.leidenuniv.nl/~sweijen/3C48.h5

Please note that at this moment **DE609HBA is not present yet** (it didn't participate in the observation). We will add this station later.

For some illustration, here are the bandpass plots produced by prefactor:
![bandpass_time5052122162 00278](https://user-images.githubusercontent.com/2464769/60805439-60987200-a180-11e9-9d28-6b5810574056.png)
![bandpass_time5052122162 00278_polXX](https://user-images.githubusercontent.com/2464769/60805440-61310880-a180-11e9-826f-5e7e5c11bfba.png)
![bandpass_time5052122162 00278_polYY](https://user-images.githubusercontent.com/2464769/60805441-61310880-a180-11e9-9746-f918c54e58db.png)

**Comment by adrabent** [comment]
This commit allows for transferring any type of solutions from any set of antennas from a reference file (but no time dependence allowed). The data is copied using nearest neighbour interpolation (equals direct copy if frequency resolution is identical).
The transfer scripts identifies the calibrator used and will only copy if a non-trusted calibrator (can be changed) was used and if the stations provided are present at all.

**Comment by adrabent** [comment]
Furthermore, the final h5parm will contain information if some solutions were overwritten (in the HISTORY table)

**Comment by rvweeren** [comment]
Should we test this now in Leiden, or are you still working in it?

**Comment by adrabent** [comment]
Yes, please test and report any issues here

**Comment by rvweeren** [comment]
A first test went ok in the sense that it ran smoothly. Now making some plots to verify things went as expected.

**Comment by rvweeren** [comment]
Confirmed that the international bandpasses got replaced.
