### ISSUE TITLE
better y-axis ranges for bandpass plots

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#243]
Minor enhancement fix. I noticed that the international stations bandpasses are not well plotted with the current y-axis scaling. There are two examples, see the included plots. Note that all the matrix amplitude plots also suffer from a too low max y-axis value.

![bandpass_time5066013843 00278](https://user-images.githubusercontent.com/3879473/61413305-724de800-a8eb-11e9-935a-d4a2b557894c.png)
![bandpass_time5066013843 00278_polXX](https://user-images.githubusercontent.com/3879473/61413440-cbb61700-a8eb-11e9-9fb8-bcd0d2932018.png)

**Comment by adrabent** [comment]
I agree. This issue is related to the autoset option in `losoto` PLOT (which is mainly for colorcoded plots).
Maybe one could set for non-colorcoded plots the plotrange just to be the min and the max value of the data.

**Comment by adrabent** [comment]
Changed autoscale behaviour for 1-D amplitude plots in losoto.
https://github.com/revoltek/losoto/commit/6fc915942baf620db70db5b72d2b380bf033a8d1
