### ISSUE TITLE
LOFARsoft 4 crash

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#244]
Dear all,

I installed latest LOFARsoft (4.0.2), latest NDP3 and LOFAR Beam etc. and tried to run latest master version of Prefactor. I got the following error:

> ERROR   node.mpuls.python_plugin: Missing parentheses in call to 'print'. Did you mean print('SEPERATION from A-Team sources')? (check_Ateam_separation.py, line 104)

This is under Ubuntu 18.04. Am I doing something wrong? Same thing happens if I do not update NDP3. All dependencies (RMExtract, LoSoTo, LSMTool, PyBDSF) are compilled for Python 3.

Full log, parset and pipeline.cfg are attached.

Best regards,
Alex

[logsEtc.zip](https://github.com/lofar-astron/prefactor/files/3413979/logsEtc.zip)

**Comment by adrabent** [comment]
The current prefactor master branch is not yet compatible to python3, which is used for the newest LOFAR software release. We are working on making prefactor compatible to it.

Thus, please run prefactor only with lofarsoft 3.x

**Comment by AlexKurek** [comment]
Thank you for explanations.
In that case it may be good to update the Coockbook chapter:
https://support.astron.nl/LOFARImagingCookbook/buildlofar.html#how-to-run-prefactor-3-0-inside-the-docker-container
it is suggested there that Prefactor 3 can be run using Docker image with LOFARsoft v. 4.0:
https://support.astron.nl/LOFARImagingCookbook/buildlofar.html#what-is-in-the-lofar-docker-image

**Comment by adrabent** [comment]
All software related bugs should be fixed in the new version, based on Docker images: https://git.astron.nl/eosc/prefactor3-cwl
