### ISSUE TITLE
error loading debug files 

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#245]
Hi,

It's not on my machine, but I just forward this issue.
Running the pipeline, a crash occurs within the ndddp_prepcal step, always not beeing able to load some debug files...

```
/opt/lofar-3.2.5/bin/makesourcedb stderr: Debug::loadLevels: error opening makesourcedb.debug
/opt/lofar-3.2.5//bin/NDPPP stderr: Debug::loadLevels: error opening DPPP.debug
```
for every subband.

I can supply the log file if necessary. We already checked that the directories given in the pipeline config file have read and write access.

Since this is a cluster, I assume it is on a shared file system.

Any ideas?
Thx.

**Comment by rvweeren** [comment]
reopen if needed
