### ISSUE TITLE
Column angle is not allowed

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#247]
Hi,

I do get this error
`IOError: Column '<angle 62.22443559 deg>]'' is not currently allowed.`
 when I run factor, https://github.com/lofar-astron/factor/issues/229, I just want to also mention it here, in case the error is introduced in prefactor. Maybe the target or initial subtract pipeline writes this into the wrong column.

**Comment by rvweeren** [comment]
reopen if this reappears.
