### ISSUE TITLE
Crash at make_summary

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#249]
Below is the error form log and full log is attached.

> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args: Traceback (most recent call last):
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py", line 104, in <module>
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:     sys.exit(python_plugin(jobid, jobhost, jobport).run_with_stored_arguments())
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/lofarnode.py", line 94, in run_with_stored_arguments
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:     returnvalue = self.run_with_logging(*self.arguments)
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/lofarnode.py", line 64, in run_with_logging
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:     return_value = self.run(*args)
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py", line 91, in run
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args:     for k, v in outdict.items():
> 2019-09-12 22:41:09 WARNING genericpipeline.executable_args: AttributeError: 'int' object has no attribute 'items'

[pipeline-Pre-Facet-Calibrator-2019-09-12T17%3A40%3A55.zip](https://github.com/lofar-astron/prefactor/files/3609874/pipeline-Pre-Facet-Calibrator-2019-09-12T17.3A40.3A55.zip)

**Comment by adrabent** [comment]
This crash is odd, and the traceback is not really helpful.
Unfortunately, I can not reproduce the error. Is it possible for you to figure out at which step in the script this error occurs? (maybe add some "print-debug statements").

Was anything written to /workspace/akurek/docker/working_directory//Pre-Facet-Calibrator.log ?

**Comment by AlexKurek** [comment]
> as anything written to /workspace/akurek/docker/working_directory//Pre-Facet-Calibrator.log ?

Yes, the content is:

> /workspace/akurek/docker/working_directory/Pre-Facet-Calibrator/logs/ does not exist. Please check your ID or you observation directory!

> Is it possible for you to figure out at which step in the script this error occurs? (maybe add some "print-debug statements").

I will try, however I never done this before, will se if it. Meanwhile I attach my calibrator parset, hovever I chenged only the basic patchs at the top of it.

[Pre-Facet-Calibrator.zip](https://github.com/lofar-astron/prefactor/files/3610850/Pre-Facet-Calibrator.zip)

**Comment by AlexKurek** [comment]
I have created `/workspace/akurek/docker/working_directory/Pre-Facet-Calibrator/logs/` before starting pipeline. But it still creshes and the content of `/workspace/akurek/docker/working_directory//Pre-Facet-Calibrator.log` is still the same:

> /workspace/akurek/docker/working_directory/Pre-Facet-Calibrator/logs/ does not exist. Please check your ID or you observation directory!
but it does exist.

**Comment by AlexKurek** [comment]
BTW, in latest master the patch to DPPP is hardcoded in newly added prefactor/tasks.cfg and this gives me:

> 2019-09-15 07:55:01 INFO    genericpipeline: Running task: dppp
> /opt/lofar/lib/python2.7/site-packages/lofarpipe/support/subprocessgroup.pyc : Using default subprocess module!
> 2019-09-15 07:55:01 ERROR   genericpipeline: *******************************************
> 2019-09-15 07:55:01 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Calibrator
> 2019-09-15 07:55:01 ERROR   genericpipeline: Detailed exception information:
> 2019-09-15 07:55:01 ERROR   genericpipeline: <type 'exceptions.TypeError'>
> 2019-09-15 07:55:01 ERROR   genericpipeline: /opt/cep/dp3/20190206/bin/DPPP is an invalid value for ExecField executable

**Comment by adrabent** [comment]
Just creating the log-directory is really not the point. I guess your genericpipeline logfiles are not put there, so you have a different `runtime_directory` compared to your `working_directory` in your `pipeline.cfg`.

Please don't use the `tasks.cfg` file if you are not working on a CEP3-like system. There you need to specify it. Otherwise you would use only a deprecated version of DPPP.

**Comment by adrabent** [comment]
Could you please try whether the new commit fixes your issue

**Comment by AlexKurek** [comment]
Below is the content of my pipeline.cfg. Anyway, Im running Calibrator now anew, will wrtie here if it worked.


> [DEFAULT]
> lofarroot = /opt/lofar
> casaroot = /opt/casacore
> pyraproot = /opt/python-casacore
> hdf5root = 
> wcsroot =
> aoflaggerroot= /opt/aoflagger
> 
> pythonpath = [/opt/RMextract-0.4/lib/python2.7/site-packages,/opt/LSMTool/lib/python2.7/site-packages,/opt/LoSoTo/lib/python2.7/site-packages,/opt/pybdsf/lib/python2.7/site-packages,/opt/python-casacore/lib/python2.7/site-packages,/opt/python-casacore/lib64/python2.7/site-packages]
> runtime_directory = /workspace/akurek/docker/working_directory/
> recipe_directories = [/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes]
> working_directory = %(runtime_directory)s
> task_files = [%(lofarroot)s/share/pipeline/tasks.cfg]
> 
> [layout]
> job_directory = %(runtime_directory)s/%(job_name)s
> 
> [cluster]
> clusterdesc = %(lofarroot)s/share/local.clusterdesc
> 
> [deploy]
> engine_ppath = %(pythonpath)s:%(pyraproot)s/lib
> engine_lpath = %(lofarroot)s/lib:%(casaroot)s/lib:%(pyraproot)s/lib:%(hdf5root)s/lib:%(wcsroot)s/lib
> 
> [logging]
> log_file = /workspace/akurek/docker/log/pipeline-%(job_name)s-%(start_time)s.log
> xml_stat_file = /workspace/akurek/docker/log/pipeline-%(job_name)s-%(start_time)s-statistics.xml
> 
> [feedback]
> # Method of providing feedback to LOFAR.
> # Valid options:
> #    messagebus    Send feedback and status using LCS/MessageBus
> #    none          Do NOT send feedback and status
> method = none
> 
> [remote]
> method = local
> max_per_node = 19

**Comment by AlexKurek** [comment]
It still crashes:

> /workspace/akurek/docker/working_directory//Pre-Facet-Calibrator/logs/ does not exist or is empty. Please check your job directory set!

**Comment by adrabent** [comment]
Where are your logfiles stored?

**Comment by AlexKurek** [comment]
I separated working_directory from runtime_directory. It crashed again.

> Where are your logfiles stored?

`/workspace/akurek/docker/log/`

It look like this:

> akurek@mpuls:/workspace/akurek/docker$ ls
> executeAll.sh  Pre-Facet-Calibrator.parset  prefactor
> log            Pre-Facet-Image.parset       runtime_directory
> pipeline.cfg   Pre-Facet-Target.parset      working_directory
> akurek@mpuls:/workspace/akurek/docker$ cd log
> akurek@mpuls:/workspace/akurek/docker/log$ ls
> pipeline-Pre-Facet-Calibrator-2019-09-17T06:11:56.log
> pipeline-Pre-Facet-Calibrator-2019-09-17T06:11:56-statistics.xml

**Comment by adrabent** [comment]
You have modified the location of your logfile manually in the pipeline.cfg.
Prefactor should now take this variable directly from it. Hope it works!

**Comment by AlexKurek** [comment]
Now it looks like this:

> Could not find all LOFAR or related software packages. Could not determine the used software versions.
> 
> Antennas removed from the data: NONE
> A-Team sources close to the phase reference center: Jupiter
> 
> 
> Amount of flagged solutions per station and solution table:
> Station   polalign faraday  bandpass  clock  
> CS001HBA0  0.00%    0.00%    0.98%    0.00%  
> CS001HBA1  0.00%    0.00%    0.98%    0.00%  
> CS002HBA0  0.00%    0.00%    0.98%    0.00%  
> CS002HBA1  0.00%    0.00%    0.98%    0.00%  
> CS003HBA0  0.00%    0.00%    0.98%    0.00%  
> CS003HBA1  0.00%    0.00%    0.98%    0.00%  
> CS004HBA0  0.00%    0.00%    0.98%    0.00%  
> CS004HBA1  0.00%    0.00%    0.98%    0.00%  
> CS005HBA0  0.00%    0.00%    0.98%    0.00%  
> CS005HBA1  0.00%    0.00%    0.98%    0.00%  
> CS006HBA0  0.00%    0.00%    0.98%    0.00%  
> CS006HBA1  0.00%    0.00%    0.98%    0.00%  
> CS007HBA0  0.00%    0.00%    0.98%    0.00%  
> CS007HBA1  0.00%    0.00%    0.98%    0.00%  
> CS011HBA0  0.00%    0.00%    0.98%    0.00%  
> CS011HBA1  0.00%    0.00%    0.98%    0.00%  
> CS013HBA0  0.00%    0.00%    0.98%    0.00%  
> CS013HBA1  0.00%    0.00%    0.98%    0.00%  
> CS017HBA0  0.00%    0.00%    0.98%    0.00%  
> CS017HBA1  0.00%    0.00%    0.98%    0.00%  
> CS021HBA0  0.00%    0.00%    0.98%    0.00%  
> CS021HBA1  0.00%    0.00%    0.98%    0.00%  
> CS024HBA0  0.00%    0.00%    0.98%    0.00%  
> CS024HBA1  0.00%    0.00%    0.98%    0.00%  
> CS026HBA0  0.00%    0.00%    0.98%    0.00%  
> CS026HBA1  0.00%    0.00%    0.98%    0.00%  
> CS028HBA0  0.00%    0.00%    0.98%    0.00%  
> CS028HBA1  0.00%    0.00%    0.98%    0.00%  
> CS030HBA0  0.00%    0.00%    0.98%    0.00%  
> CS030HBA1  0.00%    0.00%    0.98%    0.00%  
> CS031HBA0  0.00%    0.00%    0.98%    0.00%  
> CS031HBA1  0.00%    0.00%    0.98%    0.00%  
> CS032HBA0  0.00%    0.00%    0.98%    0.00%  
> CS032HBA1  0.00%    0.00%    0.98%    0.00%  
> CS101HBA0  0.00%    0.00%    0.98%    0.00%  
> CS101HBA1  0.00%    0.00%    0.98%    0.00%  
> CS103HBA0  0.00%    0.00%    0.98%    0.00%  
> CS103HBA1  0.00%    0.00%    0.98%    0.00%  
> CS201HBA0  0.00%    0.00%    0.98%    0.00%  
> CS201HBA1  0.00%    0.00%    0.98%    0.00%  
> CS301HBA0  0.00%    0.00%    0.98%    0.00%  
> CS301HBA1  0.00%    0.00%    0.98%    0.00%  
> CS302HBA0  0.00%    0.00%    0.98%    0.00%  
> CS302HBA1  0.00%    0.00%    0.98%    0.00%  
> CS401HBA0  0.00%    0.00%    0.98%    0.00%  
> CS401HBA1  0.00%    0.00%    0.98%    0.00%  
> CS501HBA0  0.00%    0.00%    0.98%    0.00%  
> CS501HBA1  0.00%    0.00%    0.98%    0.00%  
> RS106HBA   0.00%    0.00%    0.98%    0.00%  
> RS205HBA   0.00%    0.00%    0.98%    0.00%  
> RS208HBA   0.00%    0.00%    0.98%    0.00%  
> RS210HBA   0.00%    0.00%    0.98%    0.00%  
> RS305HBA   0.00%    0.00%    0.98%    0.00%  
> RS306HBA   0.00%    0.00%    0.98%    0.00%  
> RS307HBA   0.00%    0.00%    0.98%    0.00%  
> RS310HBA   0.00%    0.00%    0.98%    0.00%  
> RS406HBA   0.00%    0.00%    0.98%    0.00%  
> RS407HBA   0.00%    0.00%    0.98%    0.00%  
> RS409HBA   0.00%    0.00%    0.98%    0.00%  
> RS503HBA   0.00%    0.00%    0.98%    0.00%  
> RS508HBA   0.00%    0.00%    0.98%    0.00%  
> RS509HBA   0.00%    0.00%    0.98%    0.00%  
> 
> Overall amount of flagged data in the final data:
> Station

**Comment by AlexKurek** [comment]
Now it looks OK:

> Software versions currently used:
> Ubuntu 16.04 xenial 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019
> DPPP 4.1
> AOFlagger 2.14.0 (2019-02-14)
> losoto 2.0
> lsmtool 1.4.1
> WSClean version 2.8 (2019-09-16)
> Python 2.7.12
> matplotlib 2.2.4, scipy 0.17.0, astropy 2.0.14
> 
> Antennas removed from the data: NONE
> A-Team sources close to the phase reference center: Jupiter
> 
> 
> Amount of flagged solutions per station and solution table:
> Station   polalign faraday  bandpass  clock  
> CS001HBA0  0.00%    0.00%    0.98%    0.00%  
> CS001HBA1  0.00%    0.00%    0.98%    0.00%  
> CS002HBA0  0.00%    0.00%    0.98%    0.00%  
> CS002HBA1  0.00%    0.00%    0.98%    0.00%  
> CS003HBA0  0.00%    0.00%    0.98%    0.00%  
> CS003HBA1  0.00%    0.00%    0.98%    0.00%  
> CS004HBA0  0.00%    0.00%    0.98%    0.00%  
> CS004HBA1  0.00%    0.00%    0.98%    0.00%  
> CS005HBA0  0.00%    0.00%    0.98%    0.00%  
> CS005HBA1  0.00%    0.00%    0.98%    0.00%  
> CS006HBA0  0.00%    0.00%    0.98%    0.00%  
> CS006HBA1  0.00%    0.00%    0.98%    0.00%  
> CS007HBA0  0.00%    0.00%    0.98%    0.00%  
> CS007HBA1  0.00%    0.00%    0.98%    0.00%  
> CS011HBA0  0.00%    0.00%    0.98%    0.00%  
> CS011HBA1  0.00%    0.00%    0.98%    0.00%  
> CS013HBA0  0.00%    0.00%    0.98%    0.00%  
> CS013HBA1  0.00%    0.00%    0.98%    0.00%  
> CS017HBA0  0.00%    0.00%    0.98%    0.00%  
> CS017HBA1  0.00%    0.00%    0.98%    0.00%  
> CS021HBA0  0.00%    0.00%    0.98%    0.00%  
> CS021HBA1  0.00%    0.00%    0.98%    0.00%  
> CS024HBA0  0.00%    0.00%    0.98%    0.00%  
> CS024HBA1  0.00%    0.00%    0.98%    0.00%  
> CS026HBA0  0.00%    0.00%    0.98%    0.00%  
> CS026HBA1  0.00%    0.00%    0.98%    0.00%  
> CS028HBA0  0.00%    0.00%    0.98%    0.00%  
> CS028HBA1  0.00%    0.00%    0.98%    0.00%  
> CS030HBA0  0.00%    0.00%    0.98%    0.00%  
> CS030HBA1  0.00%    0.00%    0.98%    0.00%  
> CS031HBA0  0.00%    0.00%    0.98%    0.00%  
> CS031HBA1  0.00%    0.00%    0.98%    0.00%  
> CS032HBA0  0.00%    0.00%    0.98%    0.00%  
> CS032HBA1  0.00%    0.00%    0.98%    0.00%  
> CS101HBA0  0.00%    0.00%    0.98%    0.00%  
> CS101HBA1  0.00%    0.00%    0.98%    0.00%  
> CS103HBA0  0.00%    0.00%    0.98%    0.00%  
> CS103HBA1  0.00%    0.00%    0.98%    0.00%  
> CS201HBA0  0.00%    0.00%    0.98%    0.00%  
> CS201HBA1  0.00%    0.00%    0.98%    0.00%  
> CS301HBA0  0.00%    0.00%    0.98%    0.00%  
> CS301HBA1  0.00%    0.00%    0.98%    0.00%  
> CS302HBA0  0.00%    0.00%    0.98%    0.00%  
> CS302HBA1  0.00%    0.00%    0.98%    0.00%  
> CS401HBA0  0.00%    0.00%    0.98%    0.00%  
> CS401HBA1  0.00%    0.00%    0.98%    0.00%  
> CS501HBA0  0.00%    0.00%    0.98%    0.00%  
> CS501HBA1  0.00%    0.00%    0.98%    0.00%  
> RS106HBA   0.00%    0.00%    0.98%    0.00%  
> RS205HBA   0.00%    0.00%    0.98%    0.00%  
> RS208HBA   0.00%    0.00%    0.98%    0.00%  
> RS210HBA   0.00%    0.00%    0.98%    0.00%  
> RS305HBA   0.00%    0.00%    0.98%    0.00%  
> RS306HBA   0.00%    0.00%    0.98%    0.00%  
> RS307HBA   0.00%    0.00%    0.98%    0.00%  
> RS310HBA   0.00%    0.00%    0.98%    0.00%  
> RS406HBA   0.00%    0.00%    0.98%    0.00%  
> RS407HBA   0.00%    0.00%    0.98%    0.00%  
> RS409HBA   0.00%    0.00%    0.98%    0.00%  
> RS503HBA   0.00%    0.00%    0.98%    0.00%  
> RS508HBA   0.00%    0.00%    0.98%    0.00%  
> RS509HBA   0.00%    0.00%    0.98%    0.00%  
> 
> Overall amount of flagged data in the final data:
> Station  
> CS001HBA0      2.74%
> CS001HBA1      3.53%
> CS002HBA0     10.47%
> CS002HBA1     22.09%
> CS003HBA0     25.13%
> CS003HBA1     22.61%
> CS004HBA0     20.15%
> CS004HBA1     26.28%
> CS005HBA0      7.32%
> CS005HBA1     11.38%
> CS006HBA0      5.19%
> CS006HBA1     35.00%
> CS007HBA0      3.42%
> CS007HBA1     12.89%
> CS011HBA0      5.79%
> CS011HBA1     13.20%
> CS013HBA0     26.09%
> CS013HBA1     21.75%
> CS017HBA0     14.91%
> CS017HBA1     11.06%
> CS021HBA0      5.94%
> CS021HBA1      3.98%
> CS024HBA0      1.68%
> CS024HBA1      3.30%
> CS026HBA0      7.45%
> CS026HBA1     10.93%
> CS028HBA0      6.36%
> CS028HBA1      9.71%
> CS030HBA0     14.98%
> CS030HBA1     18.79%
> CS031HBA0      8.73%
> CS031HBA1     14.45%
> CS032HBA0     13.21%
> CS032HBA1      9.07%
> CS101HBA0     12.57%
> CS101HBA1      6.71%
> CS103HBA0      8.01%
> CS103HBA1      7.66%
> CS201HBA0     29.25%
> CS201HBA1     13.21%
> CS301HBA0      8.14%
> CS301HBA1     14.65%
> CS302HBA0      1.29%
> CS302HBA1      7.61%
> CS401HBA0      5.44%
> CS401HBA1      4.73%
> CS501HBA0     12.18%
> CS501HBA1      8.08%
> RS106HBA       0.64%
> RS205HBA       0.31%
> RS208HBA       2.60%
> RS210HBA       0.35%
> RS305HBA       0.46%
> RS306HBA       0.23%
> RS307HBA       0.07%
> RS310HBA       0.23%
> RS406HBA       0.15%
> RS407HBA       2.10%
> RS409HBA       0.13%
> RS503HBA       0.24%
> RS508HBA       5.60%
> RS509HBA       2.10%

**Comment by adrabent** [comment]
Great, so script works now!
