### ISSUE TITLE
Ambiguity in getStructure_from_phases

### ISSUE THREAD

**Issue by sabourke** [lofar-astron/prefactor#251]
I was getting a crash due an unexpected shape of an array in the getStructure_from_phases script. I'm assuming that the `squeeze()` is to remove the 'dir' axis but in my case it was also removing the time or freq axis (I don't remember which one) which was also of length 1. If the squeeze is for the dir axis then [this branch](https://github.com/sabourke/prefactor-1/tree/dir_squeeze) fixes it.

**Comment by sabourke** [comment]
Now that I think about it, my fix isn't good. It solved my issue - I must have not had a 'dir' axis so the squeeze() didn't happen but if there was a 'dir' axis, it would shave still have squeezed out the other axis and failed too. It shouldn't be implemented as a squeeze rather a reshape, or an explicit index selection. Eg:
```
        try:
            vals = reorderAxes( vals, soltab.getAxesNames(), ['pol', 'ant', 'time', 'freq', 'dir'])
            vals = vals[...,0]
```
This is all assuming that the purpose of that squeeze was to get rid of a 'dir' axis of length 1.

**Comment by adrabent** [comment]
You are right. In the context of a prefactor run, there should not be any dir axis left at this step (because it was already squeezed before).
