### ISSUE TITLE
apply target gsmcal solutions to DATA column not SMOOTHED_DATA

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#257]
Shouldn't the gsmcal solutions be applied to DATA and not SMOOTHED_DATA?

https://github.com/lofar-astron/prefactor/blob/f9080c20b573c5b21b28ba9d1c687f9a3a9ea72c/Pre-Facet-Target.parset#L820

with `do_smooth=False` this is probably ok since SMOOTHED_DATA is just a copy of DATA but it's not what you want for `do_smooth=True` (smoothing should only be used before calibration not in the apply)

**Comment by adrabent** [comment]
This is correct. Thanks for spotting this!
