### ISSUE TITLE
check_station_mismatch error

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#259]
I am processing some data through Pre-Facet-Calibrator and then Pre-Facet-Target, using prefactor pulled from the github as of 12 Nov.  I have an observation for which this works, but then when I run it on a different observation, Pre-Facet-Target breaks at the check_station_mismatch step with the hdf5 error in the attached log. 
[h5_error.txt](https://github.com/lofar-astron/prefactor/files/3851991/h5_error.txt)

**Comment by adrabent** [comment]
Could it be that in one of your cases the calibrator observation's `cal_solutions.h5` has been created with a different version of HDF5?

**Comment by lmorabit** [comment]
This seems to be a pipeline issue.  I can recreate the problem on a completely different cluster, and now with different data, but still get the same problem.

I can get check_station_mismatch to run if I change it to a pythonplugin rather than a plugin, but then I found that the word 'filter' is reserved in python so had to change the 'filter' variable to 'blfilter'.  I am now absolutely convinced that the 'result' is set to the right thing -- i.e.:
result = {'filter': '[CR]S*&'}
but the first time check_station_mismatch.output.filter is called, the pipeline fails.

**Comment by lmorabit** [comment]
update: i had to add another step to expand the check_station_mismatch output mapfile, but it is at least being passed to ndppp_prep_target properly.

**Comment by lmorabit** [comment]
While I am happy that I've found a workaround, I am not happy about the fact that I am running this to do a benchmark test of how the long baseline pipeline works with the standard prefactorV3.0 -- I don't know if other people have run into this issue, or if they are still using an older version of prefactor (which worked on this data) but it's not good practice to benchmark against something I've had to modify to get to work.  It would be good to have a discussion about this, or I'm happy to push my changes to the pipeline if you'll accept them.

**Comment by adrabent** [comment]
Could you at least recover a meaningful error message from your investigations? It is rather odd since I can not reproduce your error with any other data I have :(

**Comment by lmorabit** [comment]
The h5 error in the file I attached to my first comment is the only meaningful error I can get.  Depending on different things I try (like specifying max_per_node = 1) I sometimes get an 'Abort' and sometimes get a 'Segmentation fault' but the h5 error is always the same.

**Comment by lmorabit** [comment]
Happy for suggestions of anything I could try that I haven't already ...

**Comment by adrabent** [comment]
Ya.. I am happy to see logs (if they contain anything)..

**Comment by lmorabit** [comment]
Here are all the logs from all the tests I ran:
[baseline.log](https://github.com/lofar-astron/prefactor/files/3896597/baseline.log)
[disable_hdf5_version_check_1.log](https://github.com/lofar-astron/prefactor/files/3896598/disable_hdf5_version_check_1.log)
[disable_hdf5_version_check_2.log](https://github.com/lofar-astron/prefactor/files/3896599/disable_hdf5_version_check_2.log)
[max_per_node_1.log](https://github.com/lofar-astron/prefactor/files/3896600/max_per_node_1.log)
[with_usr_lib64.log](https://github.com/lofar-astron/prefactor/files/3896601/with_usr_lib64.log)

**Comment by adrabent** [comment]
> I can get check_station_mismatch to run if I change it to a pythonplugin rather than a plugin, but then I found that the word 'filter' is reserved in python so had to change the 'filter' variable to 'blfilter'. I am now absolutely convinced that the 'result' is set to the right thing -- i.e.:
result = {'filter': '[CR]S*&'}
but the first time check_station_mismatch.output.filter is called, the pipeline fails with a <type 'exceptions.KeyError'> .update: i had to add another step to expand the check_station_mismatch output mapfile, but it is at least being passed to ndppp_prep_target properly.

That is the correct behaviour. If you use a `plugin` you can directly return a variable to pipeline which can be parsed in the parset. A `pythonplugin` only returns to a mapfile, which in turn needs to be extracted as such with another `plugin`. This is what you did.
So the question is why it works for a `pythonplugin`, but not for a `plugin`? This might be related to something deep in the pipeline how it calls these two different things.

**Comment by adrabent** [comment]
This plugin imports an `h5parm` module from `losoto`.
Could you alter the plugin in the way that it prints out the used paths?

```
import sys
print sys.path
```

Then repeat the exercise in your `pythonplugin` version. Does it show the same directories or is something different there?

**Comment by tikk3r** [comment]
> Does it show the same directories or is something different there?

This is what I'm curious about as well, as the same bit of code executed during check_station_mismatch also seems to work when ran manually in a Python shell. Somehow executing it as a plugin changes something somewhere.

**Comment by lmorabit** [comment]
@adrabent the problem is I cannot get anything to print from within the plugin. print statements do not work, logging.info() does not work, and logging.error() did not work to print the PATH to a logfile. I am at a loss as to how else to extract this information from within the plugin.

**Comment by adrabent** [comment]
I see. If it really crashes at the import stage you won't get far.
Maybe you could try the following. Remove the import of the h5parm
`from losoto.h5parm import h5parm`

Then you will for sure remove many other lines which rely on that. But you should be able to execute the `sys.path` call at a certain point.

**Comment by lmorabit** [comment]
Okay, I'll try that this afternoon (travelling this morning). Thanks!
