### ISSUE TITLE
changing losoto dependency on uncommon libraries

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#26]
Is it worth removing the dependency of losoto on uncommon libraries as we have issues with the libraries required on a few of the computers (such as SURFsara) that it would be nice to run the prefactor pipeline on. 

Francesco tells me that the biggest change required would be pytables to h5py (I gather this is the main issue and whilst there are other libraries that losoto sometimes uses which are also uncommon these are for functionality we are not really using yet).

**Comment by rvweeren** [comment]
Note that for prefactor we now also use aplpy (not sure if that will create problems….)

**Comment by nudomarinero** [comment]
Which are the uncommon libraries? Currently, Losoto depends mainly on: 'numpy', 'cython', 'numexpr>=2.0', 'tables>=3.0' and pyrap. The rest of the dependencies are more or less optional.

**Comment by AHorneffer** [comment]
The prefactor answer would be: kicking out the dependency on LoSoTo would not be easy, and would incur a significant performance penalty. (You would need to read in the parmDBs in all the calibrator fitting scripts.) You would have to work pretty hard to convince me to do without it.

The dependence on aplpy is only in some of the plotting steps in initsubtract. if you don't have that, you can kick out these steps and the main part of prefactor / initsubtract will still work. 

If LoSoTo can or cannot do without some of the more problematic libraries is not a prefactor issue.

**Comment by twshimwell** [comment]
Yes we do not want to remove losoto as at some point it may be nice to include more functionality from this. I think it is mainly the pyrap.tables that is fiddly. 

OK, this is something that would be nice to change but yeh ok if it is not easy then perhaps more for the losoto github than the prefactor one.

**Comment by AHorneffer** [comment]
You probably mean [pytables](http://www.pytables.org/) and not pyrap.tables.

But I guess it is indeed better to shift this discussion to the [LoSoTo page](https://github.com/revoltek/losoto/issues).
