### ISSUE TITLE
transfer_solutions should check position, not source name

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#260]
For the international stations, sometimes the source name is something like '3C048' rather than '3C48' so the transfer_solutions.py script transfers the reference solutions when it shouldn't.  Rather than checking the source name -- which may or may not be right -- it would be better to check the pointing direction vs. reference directions for the trusted sources.

**Comment by adrabent** [comment]
`transfer_solutions` uses the skymodel name as extracted from `find_skymodel_cal`. And this depends on the name used within the skymodel file. As a first solution you could try to rename your skymodel. If you have used the default skymodel for 3C48 the naming should be correct.

You are right, using sky positions would be more robust. I think about implementing that. I hope we can discard this step once better skymodels are available.

**Comment by lmorabit** [comment]
I'm not even sure it's checking the name properly.  I have just run Pre-Facet-Calibrator.parset (using prefactor V3.0 and losoto 'pref3') and when I do losoto -i cal_solutions.h5 I see:


Summary of cal_solutions.h5

Solution set 'calibrator':
==========================

Directions: 3c147	 	 
            
Stations: CS001HBA0	CS001HBA1	CS002HBA0	CS002HBA1
          CS003HBA0	CS003HBA1	CS004HBA0	CS004HBA1
          CS005HBA0	CS005HBA1	CS006HBA0	CS006HBA1
          CS007HBA0	CS007HBA1	CS011HBA0	CS011HBA1
          CS013HBA0	CS013HBA1	CS017HBA0	CS017HBA1
          CS021HBA0	CS021HBA1	CS024HBA0	CS024HBA1
          CS026HBA0	CS026HBA1	CS028HBA0	CS028HBA1
          CS030HBA0	CS030HBA1	CS031HBA0	CS031HBA1
          CS032HBA0	CS032HBA1	CS101HBA0	CS101HBA1
          CS103HBA0	CS103HBA1	CS201HBA0	CS201HBA1
          CS301HBA0	CS301HBA1	CS302HBA0	CS302HBA1
          CS401HBA0	CS401HBA1	CS501HBA0	CS501HBA1
          DE601HBA	DE602HBA	DE603HBA	DE604HBA
          DE605HBA	DE609HBA	FR606HBA	IE613HBA
          PL610HBA	PL611HBA	PL612HBA	RS106HBA
          RS205HBA	RS208HBA	RS210HBA	RS305HBA
          RS306HBA	RS307HBA	RS310HBA	RS406HBA
          RS407HBA	RS409HBA	RS503HBA	RS508HBA
          RS509HBA	SE607HBA	UK608HBA	 
          
Solution table 'bandpass' (type: amplitude): 150 times, 286 freqs, 75 ants, 2 pols
    Flagged data: 0.000%
    History: 2019-11-29 12:04:43: Transferred solutions from 3C48.h5 for the stations
                                  'DE601HBA', 'DE602HBA', 'DE603HBA', 'DE604HBA', 'DE605HBA',
                                  'DE609HBA', 'FR606HBA', 'IE613HBA', 'PL610HBA', 'PL611HBA',
                                  'PL612HBA', 'SE607HBA', 'UK608HBA'

Solution table 'clock' (type: clock): 150 times, 75 ants
    Flagged data: 0.000%

Solution table 'faraday' (type: rotationmeasure): 75 ants, 150 times
    Flagged data: 1.333%

Solution table 'polalign' (type: phase): 150 times, 75 ants, 944 freqs, 2 pols
    Flagged data: 0.000%

**Comment by adrabent** [comment]
@lmorabit 
Since the script used 3C147 as identifier, `transfer_solutions` should not have transferred anything. This is a bug and should not have happened.
Could I get your `h5parm` and your `pipeline.log`?

**Comment by lmorabit** [comment]
@adrabent they are available on CEP3 in:
/data019/scratch/lmorabit/cal_solutions

thanks.

**Comment by adrabent** [comment]
Thanks,

now I need a single MS of your calibrator.
Could you please check the contents of the following file:

`%(runtime_directory)/mapfiles/sky_cal.SkymodelName.mapfile` ?

**Comment by lmorabit** [comment]
The contents are:

`[{'host': 'node056', 'file': '3c147', 'skip': False}]`

And I've copied over a single subband.

**Comment by adrabent** [comment]
@lmorabit 
I have a suspicion what could have caused the issue. Would you mind to re-run your calibrator pipeline from scratch and let me know if solutions are still transferred or not?

**Comment by lmorabit** [comment]
As in, repeat what I've already done?  With no changes?

**Comment by adrabent** [comment]
I pushed a commit for the current branch, where `h5parm_name` is run right before `transfer_solutions`. If you made other changes in order to make your run successful you could just make this change on your own and try:

https://github.com/lofar-astron/prefactor/commit/30eccbe926daec93fda1298e82147cb7ebc6e1ce

**Comment by lmorabit** [comment]
I am using the prefactor V3.0 release -- please let me know if it's
compatible.

**Comment by adrabent** [comment]
Since for the current master you will need to update `losoto` it is maybe easier for you to just do the same changes as I did, see https://github.com/lofar-astron/prefactor/issues/260#issuecomment-559842615

**Comment by lmorabit** [comment]
I made the changes and the history comment is no longer there.

**Comment by rvweeren** [comment]
There should at least be an easy True/False variable in the main parset to disable it (now it is too hardcoded and for a user it is not easy to change, one has to dig in the source code to see what happens).

I have been faking this (to disable it) by 

`! antennas2transfer        =  [X].* `

A simple extra True/False flag makes this much more understandable from the users point of view.

**Comment by adrabent** [comment]
I added a simple True/False flag option for `transfer_solutions`

@rvweeren  Which part of the script do you think is too much hardcoded?

**Comment by rvweeren** [comment]
@adrabent The fact that I manually provided a very good 3C196 model and that the I could not say to the parset to -not- transfer from 3C48 (I had to the the  [X].* hack). Am I overlooking some option?

**Comment by adrabent** [comment]
There is a variable called trusted_sources, which is by default = ['3C48', '3C147']
You basically can add this in the parset with:

`transfer_solutions.argument.trusted_sources                    =   {{ some_list }}`

It is coded but not in the parset description. I haven't put it there, because this is more an `expert-user` option. But I could also add this as an option to the parset.

**Comment by rvweeren** [comment]
@adrabent yes, adding that as an option is the parset would be good (in that way you make it less expert-user). 

On a different note, I agree with @lmorabit first issue post that it would be nice to do position matching. If one now uses a slightly different name it goes wrong.
