### ISSUE TITLE
messagebus support is not enabled or functional

### ISSUE THREAD

**Issue by nzasch** [lofar-astron/prefactor#263]
Hi

using prefactor commit f9080c20b573c5b21b28ba9d1c687f9a3a9ea72c and lofar version 3.2.18

altough setting in pipeline.cfg:

[feedback]
method = none

launching :
genericpipeline.py initsub.parset -d -c pipeline.cfg 

exit immediately with:

2020-01-15 14:56:31 DEBUG   genericpipeline: Pipeline start time: 2020-01-15T13:56:31
2020-01-15 14:56:31 ERROR   genericpipeline: Feedback over messagebus requested, but messagebus support is not enabled or functional
2020-01-15 14:56:31 WARNING genericpipeline: recipe genericpipeline completed with errors

thanks
nzasch

**Comment by adrabent** [comment]
Dear nzasch,

sorry for the late reply. Unfortunately, I can not reproduce your error neither on our local machines nor on a system like CEP3. Do you use a docker image for running LOFAR software or have you compiled it on your own? What is the system you are running on?

**Comment by nzasch** [comment]
Hi
thank you for your reply
the software is compiled inside a singularity image running centos7
these files are present:
/opt/lofar-3.2.18/include/MessageBus
/opt/lofar-3.2.18/include/MessageBus/MessageBus.h
/opt/lofar-3.2.18/lib64/libmessagebus.so
/opt/lofar-3.2.18/lib64/python2.7/site-packages/lofar/messagebus
/opt/lofar-3.2.18/lib64/python2.7/site-packages/lofar/messagebus/messagebus.py
/opt/lofar-3.2.18/lib64/python2.7/site-packages/lofar/messagebus/messagebus.pyc
/opt/lofar-3.2.18/lib64/python2.7/site-packages/lofar/messaging/messagebus.py
/opt/lofar-3.2.18/lib64/python2.7/site-packages/lofar/messaging/messagebus.pyc

but I think that using method = none, these modules should not be needed

cheers
nzasch

**Comment by adrabent** [comment]
Could you please tell what solved the issue?
