### ISSUE TITLE
H5parm_collector.py: error: unrecognized arguments: -H

### ISSUE THREAD

**Issue by sarrvesh** [lofar-astron/prefactor#264]
In the recent commit (5e52980edaae8160027be39df83e85135ed9f4c5) to Pre-Facet-Target, option '-H' was introduced to an H5parm_collector.py step (Line 805). Looking into losoto (release perf3), H5parm_collector.py does not have this option. This is causing the target pipeline to crash. Could you please look into this? Thanks.

**Comment by adrabent** [comment]
The recent commit also states the following software requirements:
`LoSoTo (version of Nov 21, 2019 or later, commit a7790a6)`

**Comment by tikk3r** [comment]
Maybe it would be nice if we can get a prefactor 3.0.1 and also an updated version of losoto? A bunch of bugfixes and small have been made since the 3.0 release.

**Comment by adrabent** [comment]
I can not speak for losoto, but a new release should be done soon

**Comment by AlexKurek** [comment]
> The recent commit also states the following software requirements:
> `LoSoTo (version of Nov 21, 2019 or later, commit a7790a6)`

For me the latest working version of LoSoTo was 1d93af146139f3f2529f9f98ce40be1bd24de369 when I checked. That was before Python 3 fixes in Prefactor.

Or - is Prefactor master and all its dependencies (LOFARsoft 4.x etc.) ready for Python 3, can we shift to it now?

Best regards,
Alex

**Comment by adrabent** [comment]
No.. you can't shift to full python3. Even if all prefactor scripts are python3-compatible and all the third-party is. The genericpipeline-framework has some inherent issues with the use of mapfiles. David did some work around it, but it appears to be broken on several levels.

You could try to run all scripts in python3 or python2. They should work with both. This is the idea. But the genericpipeline-framework does only work with python2. There is a prefactor-CWL project ongoing which tries to replace the genericpipeline-framework to get rid of python2.
