### ISSUE TITLE
Updated installation scripts and Dockerfiles for Ubuntu 16 and 18

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#266]
Dear Authors,

I was unable to find updated installation instructions for all dependencies of Prefactor 3, so I created installation (almost) scripts and Dockerfiles. Here I just want to make them available for everyone. (If the issue tracker is not a good place, I would understand if the subject would be closed or deleted.)

In attachment there are (almost) scripts and Dockerfiles for installing everything including what is needed by Image-Parset. Everything is more or less up-to-date. I tested it all by reducing NGC 4449 data and everything seems to be OK.

I’m also preparing same things for Ubuntu 20, but haven’t finished yet - so in this .zip package folder "20" is incomplete.

I hope this will be useful for somebody,

Best regards,
Alex (PL 611 software maintainer)
[install.zip](https://github.com/lofar-astron/prefactor/files/4530177/install.zip)

**Comment by nudomarinero** [comment]
Thank you. This is useful at least for me. I had a look at the scripts and I see that they install manually many of the dependency packages. I was wondering why the [Kern repository](https://kernsuite.info/) is not used. Are the versions of the software bundled in Kern obsolete for Prefactor 3?

**Comment by AlexKurek** [comment]
AFAIK now they are a bit obsolete and development of KERN-6 is on hold. Also the idea was to make it as up to date and efficient as possible, so I decided to go for manual compilation.

I updated Ubuntu 18 version so now it has WSClean 2.9 and also some minor tweaks are added. Version for Ubuntu 20 is also updated, bu for now on hold, since Im getting errors while trying to compile LOFARsoft.

**Comment by AlexKurek** [comment]
Here I upload a CUDA version of the above. Also some components are updated.
[SING_pref3_ubuntu18_python2_gcc9.zip](https://github.com/lofar-astron/prefactor/files/5854560/SING_pref3_ubuntu18_python2_gcc9.zip)

**Comment by adrabent** [comment]
The new prefactor will come with pre-defined Docker containers: https://git.astron.nl/eosc/prefactor3-cwl
