### ISSUE TITLE
reference antenna check/set

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#269]
For automated processing the reference antenna should be automatically set to an station that at a minimum has unflagged data. We again run into the situation today where CS001HBA0 and 1 were flagged by the observatory and this trips the entire prefactor pipeline (leading to 100% flagged data). One can manually specify the refant, but by now we should try to avoid these simple cases in a more automated way (for the sake of user friendless and avoiding unnecessary time trying to figure out why pipelines fail)

**Comment by adrabent** [comment]
I added a plugin which looks for the station with the least amount of flagged data after the first preparation steps are done.
With the `refant` variable you can filter the selected stations, e.g., in order to avoid that a remote or an international station is selected by chance.
