### ISSUE TITLE
Parallel run of BBS

### ISSUE THREAD

**Issue by nudomarinero** [lofar-astron/prefactor#27]
The step "gsmcalibtarget" is defined in my case with: ```gsmcalibtarget.control.max_per_node  =  8``` but it only runs 4 processes in parallel. The computer has 8 cores.

Is there any constrain with the task, the recipe or the generic pipeline that makes it run with only 4 processes in parallel?

**Comment by AHorneffer** [comment]
How many files do you have at this stage of the processing? If there are only 4 files left after concatenating, then only 4 processes are started.

If there are more files: does it say "Limiting to 4 simultaneous jobs/node" in the logfile?

**Comment by nudomarinero** [comment]
My bad. Data is already concatenated and there are only 4 bands in the node.
