### ISSUE TITLE
Pre-Facet-Target pipeline crashes at add_missing_stations step

### ISSUE THREAD

**Issue by marcoiacobelli77** [lofar-astron/prefactor#270]
The Pre-Facet-Target pipeline commit c2ff6e8 is crashing at the add_missing_stations step. If I run the pipeline using different losoto versions I get different ERROR messages:
with losoto latest commit 13ca575
ERROR:node.lof003.control.lofar.python_plugin:group ``/sol000/TGSSphase`` does not have a child named ``val``
with losoto commit a7790a6
ERROR: Array objects cannot currently deal with void, unicode or object arrays

Logs and files can be accessed on CEP3 node lof003, see at /data/scratch/iacobelli/Pipeline_prefactor/Prefactor_targ_L773765/

**Comment by adrabent** [comment]
@marcoiacobelli77 
I ran the target pipeline of current prefactor version (master branch, latest commit) on CEP3, and can not reproduce your error.
Your losoto version is from 19 Nov 2019. You could try to update your losoto version and try again.

**Comment by marcoiacobelli77** [comment]
Hi, I tried again with losoto latest commit c219940 and I still get the error:

**Comment by adrabent** [comment]
If you want to load my software environment, you can simply source /home/drabent/load_env.sh on CEP3. At least with this environment I don't experience a crash.

**Comment by adrabent** [comment]
@marcoiacobelli77  .. does this problem still persist?

**Comment by marcoiacobelli77** [comment]
Hi Alexander, 

sorry for my late reply.

Unfortunately yes, the problem is still there. Most of the pipeline runs but the step add_missing_station fails:

2020-09-30 20:34:29 WARNING genericpipeline.executable_args: [33m[33m2020-09-30 20:34:29 - ERROR: [31mArray objects cannot currently deal with void, unicode or object arrays[0m[0m[0m

All parsets and files are on CEP3 lof022:/data/scratch/iacobelli/

Thanks,
Marco
