### ISSUE TITLE
Pipeline crash: "Station DE609HBA does not exist in reference soltab"

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#273]
When Im trying to process L695933 as a calibrator, the pipeline crashes as pasted below.
When Im using exactly the same Prefactor and its dependencies installation to process L232873 as a calibrator, its working fine and the phrase `does not exist in reference soltab` is not present in the log.

Is it Prefactor's problem or something is wrong with L695933 data?

Full log: [pipeline-Pre-Facet-Calibrator-2020-07-08T07%3A18%3A42.zip](https://github.com/lofar-astron/prefactor/files/4891191/pipeline-Pre-Facet-Calibrator-2020-07-08T07.3A18.3A42.zip)

> 2020-07-08 10:05:35 WARNING genericpipeline.executable_args: WARNING:root:Station DE609HBA does not exist in reference soltab. No solutions will be transferred!
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: Traceback (most recent call last):
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/opt/LoSoTo/bin/losoto", line 4, in <module>
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     __import__('pkg_resources').run_script('losoto==2.1', 'losoto')
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     self.require(requires)[0].run_script(script_name, ns)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     exec(code, namespace, namespace)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/opt/LoSoTo/lib/python2.7/site-packages/losoto-2.1-py2.7.egg/EGG-INFO/scripts/losoto", line 139, in <module>
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     H = h5parm(args.h5parm, readonly=False)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/opt/LoSoTo/lib/python2.7/site-packages/losoto-2.1-py2.7.egg/losoto/h5parm.py", line 80, in __init__
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     self.H = tables.open_file(h5parmFile, 'r+', IO_BUFFER_SIZE=1024*1024*10, BUFFER_TIMES=500)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/usr/lib/python2.7/dist-packages/tables/file.py", line 320, in open_file
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     return File(filename, mode, title, root_uep, filters, **kwargs)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/usr/lib/python2.7/dist-packages/tables/file.py", line 784, in __init__
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     self._g_new(filename, mode, **params)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "tables/hdf5extension.pyx", line 487, in tables.hdf5extension.File._g_new
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: tables.exceptions.HDF5ExtError: HDF5 error back trace
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: 
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "../../../src/H5F.c", line 579, in H5Fopen
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     unable to open file
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "../../../src/H5Fint.c", line 1168, in H5F_open
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     unable to lock the file or initialize file structure
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "../../../src/H5FD.c", line 1821, in H5FD_lock
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     driver lock request failed
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "../../../src/H5FDsec2.c", line 939, in H5FD_sec2_lock
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     unable to flock file, errno = 11, error message = 'Resource temporarily unavailable'
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: 
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: End of HDF5 error back trace
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: 
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: Unable to open/create file '/verbatimy/akurek/LeoTriplet/working_directory/Pre-Facet-Calibrator/results/cal_values/cal_solutions.h5'
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: ERROR:root:An error has occured while plotting.
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: INFO:node.mpuls.python_plugin:Total time 1.5930s; user time: 1.6570s; system time: 0.6953s
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: DEBUG:node.mpuls.python_plugin:Start time was 1594202734.9116s; end time was 1594202736.5050s
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: Traceback (most recent call last):
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py", line 104, in <module>
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     sys.exit(python_plugin(jobid, jobhost, jobport).run_with_stored_arguments())
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/lofarnode.py", line 94, in run_with_stored_arguments
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     returnvalue = self.run_with_logging(*self.arguments)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/lofarnode.py", line 64, in run_with_logging
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     return_value = self.run(*args)
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py", line 91, in run
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args:     for k, v in outdict.items():
> 2020-07-08 10:05:36 WARNING genericpipeline.executable_args: AttributeError: 'int' object has no attribute 'items'

[...]

**Comment by tikk3r** [comment]
> 2020-07-08 10:05:35 WARNING genericpipeline.executable_args: WARNING:root:Station DE609HBA does not exist in reference soltab. No solutions will be transferred!
This means your calibrator is not 3C 48 or 3C 147, so it'll transfer reference bandpasses I made from 3C 48. These do not container DE609, because it was not present in that observation.

The other error seems to be a possible problem with the HDF5 installation or hdf5 related packages.

**Comment by AlexKurek** [comment]
> The other error seems to be a possible problem with the HDF5 installation or hdf5 related packages.

Thats right, but this error is not present in case of other data, where Im using the same Singularity container for processing. HDF5 version is 1.8.21 in both cases.

**Comment by tikk3r** [comment]
You can try setting `HDF5_USE_FILE_LOCKING` to `FALSE`. I know that HDF5 and e.g. NFS don't work well together in that regard.

**Comment by AlexKurek** [comment]
I tried `HDF5_USE_FILE_LOCKING=FALSE` but it didnt helped. The calibrator is 3C295

**Comment by AlexKurek** [comment]
Same crash happens for L657308 (target) and L657312 (calibrator, 3C195):

> 2020-07-14 12:01:26 INFO    node.mpuls.python_plugin: Processing 3c295_2c
> 2020-07-14 12:01:27 INFO    genericpipeline.executable_args: Waiting for compute threads...
> 2020-07-14 12:01:27 WARNING genericpipeline.executable_args: WARNING:root:Station DE609HBA does not exist in reference soltab. No solutions will be transferred!
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: Traceback (most recent call last):
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/opt/LoSoTo/bin/losoto", line 4, in <module>
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     __import__('pkg_resources').run_script('losoto==2.1', 'losoto')
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     self.require(requires)[0].run_script(script_name, ns)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     exec(code, namespace, namespace)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/opt/LoSoTo/lib/python2.7/site-packages/losoto-2.1-py2.7.egg/EGG-INFO/scripts/losoto", line 139, in <module>
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     H = h5parm(args.h5parm, readonly=False)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/opt/LoSoTo/lib/python2.7/site-packages/losoto-2.1-py2.7.egg/losoto/h5parm.py", line 80, in __init__
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     self.H = tables.open_file(h5parmFile, 'r+', IO_BUFFER_SIZE=1024*1024*10, BUFFER_TIMES=500)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/usr/lib/python2.7/dist-packages/tables/file.py", line 320, in open_file
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     return File(filename, mode, title, root_uep, filters, **kwargs)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/usr/lib/python2.7/dist-packages/tables/file.py", line 784, in __init__
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     self._g_new(filename, mode, **params)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "tables/hdf5extension.pyx", line 487, in tables.hdf5extension.File._g_new
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: tables.exceptions.HDF5ExtError: HDF5 error back trace
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: 
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "../../../src/H5F.c", line 579, in H5Fopen
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     unable to open file
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "../../../src/H5Fint.c", line 1168, in H5F_open
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     unable to lock the file or initialize file structure
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "../../../src/H5FD.c", line 1821, in H5FD_lock
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     driver lock request failed
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "../../../src/H5FDsec2.c", line 939, in H5FD_sec2_lock
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     unable to flock file, errno = 11, error message = 'Resource temporarily unavailable'
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: 
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: End of HDF5 error back trace
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: 
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: Unable to open/create file '/verbatimy/akurek/LeoTriplet1/working_directory/Pre-Facet-Calibrator/results/cal_values/cal_solutions.h5'
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: ERROR:root:An error has occured while plotting.
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: INFO:node.mpuls.python_plugin:Total time 1.6144s; user time: 1.6330s; system time: 0.7378s
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: DEBUG:node.mpuls.python_plugin:Start time was 1594728086.6489s; end time was 1594728088.2638s
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: Traceback (most recent call last):
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py", line 104, in <module>
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     sys.exit(python_plugin(jobid, jobhost, jobport).run_with_stored_arguments())
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/lofarnode.py", line 94, in run_with_stored_arguments
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     returnvalue = self.run_with_logging(*self.arguments)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/support/lofarnode.py", line 64, in run_with_logging
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     return_value = self.run(*args)
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:   File "/opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py", line 91, in run
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args:     for k, v in outdict.items():
> 2020-07-14 12:01:28 WARNING genericpipeline.executable_args: AttributeError: 'int' object has no attribute 'items'

**Comment by tikk3r** [comment]
Do you have the right permissions to open and/or write to the file and are all necessary paths bound to the singularity?
I'm not sure about using external hard drives, it might be an issue?

**Comment by AlexKurek** [comment]
Also calibrator 3C296 for also those data crashed same way. I moved the data to internal drive, so this is not the issue here. Now Im trying from sudo

**Comment by tikk3r** [comment]
What version of HDF5 are you running? Is it 1.8 or 1.10? Version 1.10 introduced (changes to) file locking, and only >1.10.1 allows you to disable that with e.g. that environment variable. Maybe try downgrading HDF5 to 1.8 (also making sure things like h5py are linked against the correct library).

**Comment by AlexKurek** [comment]
Im using 1.8.21 only. 1.10 caused something (maybe it was casacore 2.2?) to crash during compilation.
I attach my Singularity file. Its always working - except those two Leo Triplet observations form Nov 2019
[SING_pref3_ubuntu18_python2.zip](https://github.com/lofar-astron/prefactor/files/4924963/SING_pref3_ubuntu18_python2.zip)

**Comment by AlexKurek** [comment]
@tikk3r I would like to try using your image from Fri Jun 19 11:48:22 CEST 2020. Is it compatible with latest Prefactor master?

**Comment by AlexKurek** [comment]
@tikk3r,
> This means your calibrator is not 3C 48 or 3C 147, so it'll **transfer reference bandpasses I made** from 3C 48. These do not container DE609, because it was not present in that observation.

Is this some code you wrote for Prefactor? Does it have any additional requirements, eg. h5p?

(Im still getting this error using my recipes. Your latest recipes are working fine for me)

**Comment by tikk3r** [comment]
> Is this some code you wrote for Prefactor? Does it have any additional requirements, eg. h5p?

I didn't write the code, but it was implemented because currently there are no high resolution models of the other sources included in prefactor (3C 48 and 3C 147 are point like enough to work for the international baselines).



> (Im still getting this error using my recipes. Your latest recipes are working fine for me)

This is strange to me though. It still makes me think there is something hidden in the HDF5 related packages that is not fully correct then. I'd double check that after installing HDF5 1.8.21 all other HDF5 related things such as `tables` and potential other things are actually using your HDF5 1.8.21 installation and not, for example, their own shipped binaries.

**Comment by AlexKurek** [comment]
Thank you, that's exactly what was wrong. Solved by installing tables using pip, not apt-get, like before.
