### ISSUE TITLE
Crash after Target is finished

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#274]
Im getting what is pasted below. But everything related to results seems to be OK.

[Pre-Facet-Target.zip](https://github.com/lofar-astron/prefactor/files/4924794/Pre-Facet-Target.zip)
[pipeline-Pre-Facet-Target-2020-07-15T09%3A32%3A42.zip](https://github.com/lofar-astron/prefactor/files/4924796/pipeline-Pre-Facet-Target-2020-07-15T09.3A32.3A42.zip)

> 2020-07-15 11:03:44 INFO    genericpipeline.executable_args: Waiting for compute threads...
> 2020-07-15 11:03:46 DEBUG   genericpipeline.executable_args: Summary logfile is written to /workspace/akurek/Pref30_master/working_directory/Pre-Facet-Target.log
> 2020-07-15 11:03:47 DEBUG   genericpipeline.executable_args: Summary has been created.
> 2020-07-15 11:03:47 DEBUG   genericpipeline.executable_args: Results for job 0 submitted by ('149.156.70.247', 50158)
> 2020-07-15 11:03:47 INFO    node.mpuls.python_plugin: Total time 3.3205s; user time: 2.1844s; system time: 1.3833s
> 2020-07-15 11:03:47 DEBUG   node.mpuls.python_plugin: Start time was 1594811024.5235s; end time was 1594811027.8445s
> 2020-07-15 11:03:48 WARNING genericpipeline.executable_args: Closing remaining open files:/workspace/akurek/Pref30_master/working_directory/Pre-Facet-Target/results/cal_values/solutions.h5...done
> 2020-07-15 11:03:48 DEBUG   genericpipeline.executable_args: 
> 2020-07-15 11:03:48 WARNING genericpipeline.executable_args: 
> 2020-07-15 11:03:48 INFO    genericpipeline.executable_args: Subprocess completed with exit status 0: /bin/sh -c python /opt/lofar/lib/python2.7/site-packages/lofarpipe/recipes/nodes/python_plugin.py 0 149.156.70.247 43613
> 2020-07-15 11:03:48 DEBUG   genericpipeline.executable_args: compute.dispatch results job 0: job_duration: 4.3175330162, returncode: 0 
> 2020-07-15 11:03:49 DEBUG   genericpipeline.executable_args: Adding node_logging_information
> 2020-07-15 11:03:49 DEBUG   genericpipeline.executable_args: Writing data map file: /workspace/akurek/Pref30_master/working_directory/Pre-Facet-Target/mapfiles/make_summary.mapfile
> 2020-07-15 11:03:49 INFO    genericpipeline.executable_args: recipe executable_args completed
> 2020-07-15 11:03:49 INFO    genericpipeline: LOFAR Pipeline finished succesfully.
> 2020-07-15 11:03:49 INFO    genericpipeline: recipe genericpipeline completed
> 2020-07-15 11:03:50 ERROR   genericpipeline: *******************************************
> 2020-07-15 11:03:50 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Target
> 2020-07-15 11:03:50 ERROR   genericpipeline: Detailed exception information:
> 2020-07-15 11:03:50 ERROR   genericpipeline: <type 'exceptions.TypeError'>
> 2020-07-15 11:03:50 ERROR   genericpipeline: set() takes exactly 1 argument (3 given)
> 2020-07-15 11:03:50 ERROR   genericpipeline: *******************************************
> 2020-07-15 11:03:50 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
> 2020-07-15 11:03:50 WARNING genericpipeline: recipe genericpipeline completed with errors

**Comment by tikk3r** [comment]
Same as #233. I've seen it as well some times, but I'm not sure what causes it. It seems harmless apart from the error message.

**Comment by AlexKurek** [comment]
Yes, it seems harmless. I run like this:
`singularity exec -B /workspace/akurek/ ./pref3_ubuntu18_python2.sif ./executeAll.sh`
and the content of .sh file is:

> #!/bin/bash
> 
> genericpipeline.py Pre-Facet-Calibrator.parset -v -d -c pipeline.cfg && \
> genericpipeline.py Pre-Facet-Target.parset -v -d -c pipeline.cfg
> #genericpipeline.py Pre-Facet-Image.parset -v -d -c pipeline.cfg

Maybe it happens when `genericpipeline.py Pre-Facet-Target.parset -v -d -c pipeline.cfg` is executed from a script (not from the command line)?

**Comment by adrabent** [comment]
I guess this is the same issue as #233
