### ISSUE TITLE
make_source_list.py cannot connect to GSM server

### ISSUE THREAD

**Issue by tfranzen2** [lofar-astron/prefactor#276]
Hi,
I am running the script ‘make_source_list.py’ on an LBA image to check the flux scale but I get the following error:

INFO: Writing test.fits
--> Wrote BBS sky model ‘test.fits’
Failed for reason: [Errno 111] Connection refused
Traceback (most recent call last):
 File “./make_source_list.py”, line 136, in <module>
   atrous_jmax=args.atrous_jmax, compare_dir=args.compare_dir, format=args.format)
 File “./make_source_list.py”, line 108, in main
   s_vo = lsmtool.load(vocat, VOPosition=[refRA, refDec], VORadius=‘5 deg’)
 File “/opt/cep/lsmtool/LSMTool-1.2.0/lsmtool/__init__.py”, line 86, in load
   VORadius=VORadius)
 File “/opt/cep/lsmtool/LSMTool-1.2.0/lsmtool/skymodel.py”, line 106, in __init__
   self.table = Table.read(fileObj.name, format=‘makesourcedb’)
 File “/usr/lib64/python2.7/site-packages/astropy/table/table.py”, line 2521, in read
   out = io_registry.read(cls, *args, **kwargs)
 File “/usr/lib64/python2.7/site-packages/astropy/io/registry.py”, line 531, in read
   data = reader(*args, **kwargs)
 File “/opt/cep/lsmtool/LSMTool-1.2.0/lsmtool/tableio.py”, line 124, in skyModelReader
   raise IOError(“No valid format line found in file ‘{0}‘.“.format(fileName))
IOError: No valid format line found in file ‘/tmp/tmpBYIKnQ’.

It looks like there is a problem connecting to the GSM server. I am running the script on CEP3. I contacted sysadmin but it is is not clear to them what the script is trying to connect to.

Thanks,
Tom

**Comment by adrabent** [comment]
Hallo Tom,

the line of code that returns the error:
`s_vo = lsmtool.load(vocat, VOPosition=[refRA, refDec], VORadius=‘5 deg’)` is reported to be line 108. In the current prefactor master it should be line 111. Are you running the most recent version of prefactor?

Nevertheless, the problem seems to be related to `lsmtool`.

**Comment by tfranzen2** [comment]
Hi Alex,

I was not running the latest version of prefactor. I have tried again using the latest version and I get the same error. I would appreciate it if you can help.

Thanks,
Tom

**Comment by adrabent** [comment]
Hi Tom,

are you also running the most recent version of lsmtool?
https://github.com/darafferty/LSMTool

I tried it with my version on CEP3 and don't get any error :(

**Comment by tfranzen2** [comment]
Hi Alex,

I was using lsmtool/1.2.0, which is the default on CEP3. As far as I can see, the latest version available on CEP3 is lsmtool/1.4.1. With this version, I don't get any error. I'm not sure why lsmtool/1.4.1 is not the default.

Thanks for your help!

Cheers
Tom

**Comment by adrabent** [comment]
Dear Tom,

I think the third-party software on CEP3 is not really maintained/updated anymore.

Alex
