### ISSUE TITLE
add -weighting-rank-filter 3

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#28]
Similar to factor:

add "-weighting-rank-filter 3" to all wsclean calls.

**Comment by rvweeren** [comment]
So just add this to the Initial-Subtract.parset

wsclean_high1.argument.weighting-rank-filter                  =   3
wsclean_high2.argument.weighting-rank-filter                  =   3

wsclean_low1.argument.weighting-rank-filter                   =  3
wsclean_low2.argument.weighting-rank-filter                   =  3

**Comment by AHorneffer** [comment]
Done.
