### ISSUE TITLE
wrong residual step

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#280]
https://github.com/lofar-astron/prefactor/blob/98b512b224f1ef7bb1667747918214ad928e277f/Pre-Facet-Calibrator.parset#L636

@adrabent @revoltek, I miss the  logic of this step (and the next plotPr, PlotPr2). The Faraday rotation is fitted to the rotation000 soltable. The soltable phase000 should be completely free from Farday Rotation (that is the reason why we solve with "rotation+diagonal"). But here at this line in prefactor, the residual is taken as phase000-faraday, this does not make sense to me (or am I overlooking something?). What would make sense is to do rotation000-faraday and then plot the residual. One would hope to see a low residual rotation000 indicating the faraday fit is good. I tried to adjust prefactor myself, however, losoto trips over this and cannot subtract faraday from rotation000.

```
2020-08-08 13:41:58 - INFO - Subtract soltab: rotation000
2020-08-08 13:41:58 - WARNING - faraday is of type clock/tec/rm and should be subtracted from a phase. Skipping it.

```

**Comment by adrabent** [comment]
@rvweeren .. I agree with you. This residual is somehow pointless. I will remove it from the current parset as long as https://github.com/revoltek/losoto/issues/104 is not resolved.

**Comment by revoltek** [comment]
yes, that should be removed, it is probably a residual of when we were estimating FR from RR-LL
