### ISSUE TITLE
LBA-compatibility of prefactor3

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/prefactor#283]
This issue shall help to document ideas for upcoming changes in **prefactor** regarding its compatibility to LBA data and the potential impact on the HBA calibration. It aims for an open discussion, so don't hesitate to provide comments or suggestions.

I aim to incorporate minor and major changes for prefactor to better match the approach of  [PiLL](https://github.com/revoltek/LiLF) and allow a reasonable calibration of LBA data in **prefactor**.

- **`BLsmooth.py`** 
**PiLL** uses a more parallel/faster version. This script can be incorporated in prefactor without any changes in the pipeline. Because the new version requires python3 it will not be available in the genericpipeline version anymore.

- **DPPP-ddecal**:
The `ddecal` (for Polarization Alignment, Faraday Rotation etc.) in **PiLL** uses slightly different parameters (in parenthesis current parameters):
`uvlambdamin = 100 `(300)
`minvisratio = 0.3` (0)
`maxiter = 300` (50)
`solint = 2` (1)
`nchan = 2` (1)

Here I don't see any critical point, except that for LBA a longer solution interval might help to increase S/N and speed up the calibration a bit, but the impact on HBA should not be large. In terms of maxiter it is even quite more conservative. The `uvlambdamin` parameter might be more critical, since the LBA does not suffer from "very-short" baselines. Here I would suggest to add a variable for this parameter.

- **DPPP-ddecal** (last step for clock/TEC separation):
Here **PiLL** uses `scalarphase` instead of `diagonal`, which might help to increase the S/N ratio in the solutions and simplifies the clock/TEC seperation as they are not dependend on it (since X-Y offsets should be more or less corrected at this stage).

- when applying the beam **PiLL** uses `usechannelfreq = False` (**prefactor** uses `True`). Since we apply the beam on each subband separately it should not really matter.

The target pipeline will need a major overhaul to allow a descent DIE-processing. The application of calibrator solutions to the target is already implemented in **prefactor** and could be used without a major change. The self-calibration using **GSM** is though more complex and may require another iteration of self-calibration using an updated skymodel from `wsclean`. A first iteration would look like this:

- removing faint sources from the **GSM** and limit it to FWHM/2 (to be implemented as option in `download_skymodel_target.py`)
- predicting skymodel to `MODEL_DATA` (like in the calibrator pipeline)

- **solving for slow TEC (part 1)**
   1. BLsmooth `CORRECTED_DATA` --> `SMOOTHED_DATA`
   2. BLsmooth `MODEL_DATA` --> `MODEL_DATA`
   3. solving for TEC on core + remote stations (except more distant remote stations), and constrain that superterp stations have the same solutions (`solve.antennaconstraint`), reset more distant remote station solutions/weights to 0/1, and plot TEC solutions.
   4. applying these TEC solutions to `CORRECTED_DATA` and smooth to `SMOOTED_DATA`
   
- **solving for slow TEC (part 2)**
   1. solving again for TEC on the whole array and constrain that core + (closer) remote stations have the same solutions, and plot TEC solutions
   2. apply these TEC solutions to `CORRECTED_DATA`
   
- **solving for Faraday Rotation**
   1.  convert to circular --> `CORRECTED_DATA`
   2. solve for slow diagonal (RR,LL) on full array and constrain that core stations have same solutions, plot amp/phase, derive Faraday Rotation
   3. convert back to linear --> `CORRECTED_DATA`
   4. apply these Faraday Rotation solutions
  
- **solving for slow relative amplitudes**

  1. solve for slow diagonal (XX,YY) on full array and constrain that core stations have same solutions, plot amp/phase, derive smooth amplitude variations (normalized) 
  2. apply these amplitude solutions
 
Cheers,
Alex

**Comment by tikk3r** [comment]
Lots of hopefully nice changes! Given the scale of the overhaul I presume that this will happen on a separate branch for the foreseeable future?

Will(can) we also get a new release of the current prefactor before these changes start?

**Comment by adrabent** [comment]
Yes, we could think of incorporating the target pipeline changes in a separate branch.

Since we want to change to the CWL version of prefactor soon, I was thinking to avoid maintaining two different versions and to stop the support of the `genericpipeline` version at about this time. There will be a "last" release soon. I was thinking of (at least) still updating the calibrator part for LBA to match **PiLL**, because these things are easy and fast to implemented.

**Comment by adrabent** [comment]
The LBA development is continued within [LINC](https://git.astron.nl/RD/LINC/).
