### ISSUE TITLE
Scaife & Heald 2012 scale and 3C196-offringa.skymodel

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#291]
Just raising awareness that `3C196-offringa.skymodel` is off the Scaife & Heald 2012 scale, between 10-20% if I recall correctly in the HBA band (the comment lines in the file give some more detail). In Leiden we're using a simple rescaled version made by @cgroeneveld that puts 3C196-offringa.skymodel on  Scaife & Heald 2012 scale.  Should we update to this model?

**Comment by adrabent** [comment]
Dear Reinout,

thanks for letting us now. The WARNING that the used skymodel for 3C196 is not at S&H is also been mentioned in the README. If you would not mind I would upgrade this model in prefactor. You can make a pull request or send it to me directly, so I will update it then.

Thanks for the re-scaling.
Alex

**Comment by lmorabit** [comment]
Has this been updated yet?

**Comment by adrabent** [comment]
No.. I haven't got the new model yet. Maybe I contact @cgroeneveld directly.
