### ISSUE TITLE
Broken Prefactor results/ ?

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#292]
Im getting the following error while trying to run DDF pipeline of Prefactor's results/ for fields L258201 and L343256:

> RuntimeError: SSMIndex::getIndex - access to non-existing row 60 in column NAME of table [...]

reported here:
https://github.com/mhardcastle/ddf-pipeline/issues/252

@mhardcastle  wrote a small script:

```
from __future__ import print_function
import pyrap.tables as pt
import numpy as np
import os
import glob

def fix_antenna(ms):

    for tname in ['ANTENNA','LOFAR_ANTENNA_FIELD']:
        t1=pt.table(ms+'/'+tname)

        # work out how many valid rows there are by trying to read each one and catch the exception
        valid=[]
        for i in range(len(t1)):
            try:
                _=t1[i]['NAME']
                valid.append(True)
            except RuntimeError:
                valid.append(False)

        if np.sum(valid)==len(t1):
            print('Everything is OK! Skip correction step')
            t1.close()
        else:
            print('There are',np.sum(valid),'valid rows present in corrupt table, generating new table')

            t1.copy(ms+'/TEMP',copynorows=True)
            t2=pt.table(ms+'/TEMP',readonly=False)
            t2.addrows(np.sum(valid))
            j=0
            for i in range(len(t1)):
                if valid[i]:
                    t2[j]=t1[i]
                    j+=1
            t2.close()
            t1.close()
            os.rename(ms+'/'+tname,ms+'/OLD_'+tname)
            os.rename(ms+'/TEMP',ms+'/'+tname)

if __name__=='__main__':
    g=glob.glob('*.ms')
    for ms in g:
        print('Doing',ms)
        fix_antenna(ms)
```
that is able to fix the MSs (Prefactor's results/ folder) and Im able to run DDF now. I attach zip-ed logs and summary files from Prefactor for both fields.
[L343256.zip](https://github.com/lofar-astron/prefactor/files/7273250/L343256.zip)
[L258201.zip](https://github.com/lofar-astron/prefactor/files/7273249/L258201.zip)

**Comment by AlexKurek** [comment]
I uploaded both those MS sets here:
lofar.herts.ac.uk:/beegfs/lofar/alexkurek

**Comment by adrabent** [comment]
I am not aware of such kind of an issue. Writing corrupted MS is usually related to an issue with  `DP3`, not directly with the pipeline. Can you constrain at which step of prefactor the data might have gotten corrupted?

**Comment by AlexKurek** [comment]
> Can you constrain at which step of prefactor the data might have gotten corrupted?

**Comment by adrabent** [comment]
#293

**Comment by AlexKurek** [comment]
After recomputing L258201 using current master of Prefactor Im still getting this error.

**Comment by adrabent** [comment]
Dear @AlexKurek 

yes, there is a documentation for running prefactor3-cwl, but this has not been published as HTML so far.

- [Installation instructions: ](https://git.astron.nl/eosc/prefactor3-cwl/-/blob/master/docs/source/installation.rst)
- [Configuration](https://git.astron.nl/eosc/prefactor3-cwl/-/blob/master/docs/source/parset.rst)
- [Running prefactor](https://git.astron.nl/eosc/prefactor3-cwl/-/blob/master/docs/source/running.rst)

> EDIT: Using DP3 4.1 I also got this error.

This is really a concern. Could you try to reproduce your issue with a minimal example? As I understood one possible reason could be the removal of the International Stations. This happens right at the beginning. If you would just run a simple parset doing only this job .. will it corrupt the data?

Cheers,
Alex

**Comment by adrabent** [comment]
Summary files look fine to me. Do you mean you made a pull request?

**Comment by AlexKurek** [comment]
> Summary files look fine to me. Do you mean you made a pull request?

No, no, I meant those recent commits that are now merged.

**Comment by AlexKurek** [comment]
I did:
```
msin                                =   /storage/akurek/N4449_mozaik/L258201_tests_small/3C196/L258197_SB000_uv.dppp.MS
msin.datacolumn                     =   DATA
msin.baseline                       =   [CR]S*&
msin.autoweight                     =   False
msout                               =   test.MS
msout.datacolumn                    =   DATA
msout.writefullresflag              =   False
msout.overwrite                     =   True
msout.storagemanager                =   "Dysco"
msout.storagemanager.databitrate    =   0
steps                               =   [filter]
filter.type                         =   filter
filter.baseline                     =   [CR]S*&
filter.remove                       =   true
```
and later as @mhardcastle suggested:
```
import pyrap.tables as pt
t=pt.table('/storage/akurek/N4449_mozaik/L258201_tests_small/test.MS/ANTENNA')
print(t[:]['NAME'])

for i in range(len(t)):
    print(i,t[i]['NAME'])
```
and Im getting:

> Successful readonly open of default-locked table /storage/akurek/N4449_mozaik/L258201_tests_small/test.MS/ANTENNA: 10 columns, 69 rows
> Traceback (most recent call last):
>   File "first.py", line 3, in <module>
>     print(t[:]['NAME'])
>   File "/usr/lib/python3/dist-packages/casacore/tables/table.py", line 466, in __getitem__
>     return self._row._getitem(key, self.nrows())
>   File "/usr/lib/python3/dist-packages/casacore/tables/tablerow.py", line 73, in _getitem
>     result.append(self.get(rownr))
>   File "/usr/lib/python3/dist-packages/casacore/tables/tablerow.py", line 50, in get
>     return self._get(rownr)
> RuntimeError: SSMIndex::getIndex - access to non-existing row 62 in column OFFSET of table /storage/akurek/N4449_mozaik/L258201_tests_small/test.MS/ANTENNA

**Comment by mhardcastle** [comment]
So you just removed the international stations with DPPP and that corrupted the MS? Then it's a DPPP bug. What version of DPPP are you using?

**Comment by AlexKurek** [comment]
> So you just removed the international stations with DPPP and that corrupted the MS? Then it's a DPPP bug. What version of DPPP are you using?

DPPP 4.2
