### ISSUE TITLE
Changing default IONEX download to use http

### ISSUE THREAD

**Issue by jwpetley** [lofar-astron/prefactor#297]
Recent updates to the COSMA machine in Durham have caused FTP transfer of the ionospheric data in the createRMh5parm.py script to fail. After some discussion, we believe the simple, and more modern, fix would be to update the default `ionex_server="ftp://ftp.aiub.unibe.ch/CODE/"` to the appropriate http URL instead. An example of the current error is below:

`singularity exec --bind /cosma5/data/durham/dc-petl1/ /cosma5/data/durham/dc-petl1/Software/singularity/cosma_selfcal_sandybridge.sif python /cosma5/data/durham/dc-petl1/Software/prefactor/scripts/createRMh5parm.py --ionexpath=/cosma5/data/durham/dc-petl1/VLBI_BALs/P250+33/IONEX --solsetName=target `head -n 1 srms_L726526.txt` /cosma5/data/durham/dc-petl1/VLBI_BALs/L657118/cal_values/cal_solutions.h5

`pyrap will be used to compute positions
Successful readonly open of default-locked table /cosma5/data/durham/dc-petl1/VLBI_BALs/Data/L726526/L726526_SB244_uv.MS: 24 columns, 81966000 rows
Successful readonly open of default-locked table /cosma5/data/durham/dc-petl1/VLBI_BALs/Data/L726526/L726526_SB244_uv.MS/FIELD: 10 columns, 1 rows
Successful readonly open of default-locked table /cosma5/data/durham/dc-petl1/VLBI_BALs/Data/L726526/L726526_SB244_uv.MS/ANTENNA: 10 columns, 75 rows
Successful readonly open of default-locked table /cosma5/data/durham/dc-petl1/VLBI_BALs/Data/L726526/L726526_SB244_uv.MS/ANTENNA: 10 columns, 75 rows
Traceback (most recent call last):
  File "/cosma5/data/durham/dc-petl1/Software/prefactor/scripts/createRMh5parm.py", line 257, in <module>
    proxyType=args.proxytype,proxyUser=args.proxyuser,proxyPass=args.proxypass)
  File "/cosma5/data/durham/dc-petl1/Software/prefactor/scripts/createRMh5parm.py", line 119, in main
    outpath = ionexPath)
  File "/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/RMextract-0.4-py2.7-linux-x86_64.egg/RMextract/getIONEX.py", line 694, in getIONEXfile
    return _get_IONEX_file(time, server, prefix, outpath, overwrite)
  File "/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/RMextract-0.4-py2.7-linux-x86_64.egg/RMextract/getIONEX.py", line 515, in _get_IONEX_file
    ftp.retrlines("NLST", myl.append)
  File "/usr/lib64/python2.7/ftplib.py", line 441, in retrlines
    conn = self.transfercmd(cmd)
  File "/usr/lib64/python2.7/ftplib.py", line 378, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/lib64/python2.7/ftplib.py", line 337, in ntransfercmd
    conn = socket.create_connection((host, port), self.timeout)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 110] Connection timed out
Closing remaining open files:/cosma5/data/durham/dc-petl1/VLBI_BALs/L657118/cal_values/cal_solutions.h5...done`

**Comment by gmloose** [comment]
The problem is not in `prefactor`, but in the underlying `RMextract` package.
I noticed you're still using Python 2.7, which is no longer supported. I suggest you upgrade to the latest `prefactor`, which has been renamed to `LINC`, and can be downloaded from https://git.astron.nl/RD/LINC.
Alternatively, if you're unable to upgrade, I suggest you fix `RMextract` yourself, locally, and rebuild your Singularity image.

**Comment by gmloose** [comment]
Ah, OK. I wasn't aware that the URI for the IONEX server was supplied in the parset. I assume the parset is provided as input to the Prefactor pipeline run, hence completely independent of the Singularity image being used. It should therefore be quite easy to circumvent this problem.

**Comment by tikk3r** [comment]
Indeed, prefactor is simply obtained from is repository and is independent of the container used.

**Comment by adrabent** [comment]
Dear all,

I changed the default URL for the CODE downloads from FTP to HTTP.

Cheers,
Alex
