### ISSUE TITLE
in the v2.0-devel keep plot_solutions_all_stations.py

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#32]
The new losoto images are very nice but I think that the plot_solutions_all_stations.py images of the phase solutions for a single band with the new aspect ratio very clearly show what is going on so I think we could just keep both plots.

**Comment by rvweeren** [comment]
Yes, that is my feeling as well.

**Comment by AHorneffer** [comment]
Done. Let me know if it doesn't work.
