### ISSUE TITLE
Problem with HDF5 versions

### ISSUE THREAD

**Issue by TMCantwell** [lofar-astron/prefactor#36]
The current version of LOFAR software that I am running is 2.15. 

The script is crashing when trying to fit the clock correction due to some issue with HDF5 versions which I have not been able to resolve. I was wondering if this problem has been encountered before and if a solution has been found?

We tried uninstalling pyTables from usr/local/lofar-2_15 and reinstalling them using pip install --install-option='--hdf5=/usr/local/hdf5-1.8.15-patch1' tables==3.2.1.1 . However this failed with error: option --hdf5 not recognized.

I’ve attached the log file from the script as well as other useful information. My paths are also pasted below in case these are important.

PATH:

/usr/local/casapy-42.2.30986-1-64b/bin:/usr/local/casapy/bin/:/usr/local/lofar-2_15/lofar/release/bin:/usr/local/lofar-2_15/lofar/release/sbin:/usr/local/lofar-2_15/local/release/bin:/usr/local/lofar-2_15/local/release/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

PYTHONPATH:

/home/cantwell/lib/python2.7/site-packages/:/home/cantwell/lib/python2.7/site-packages/:/usr/local/lofar-2_15/local/release/lib/python2.7/site-packages:/usr/local/lofar-2_15/lofar/release/lib/python2.7/site-packages:/usr/local/lofar-2_15/local/release/lib/python2.7/site-packages:/usr/local/lofar-2_15/local/release/lib/python2.7/site-packages

LD_LIBRARY_PATH:

/usr/local/hdf5-1.8.15-patch1/lib/:/usr/local/lofar-2_15/lofar/release/lib64:/usr/local/lofar-2_15/lofar/release/lib:/usr/local/lofar-2_15/local/release/lib:/usr/local/lofar-2_15/local/release/lib64:/usr/local/lofar-2_15/local/release/lib:/usr/local/lofar-2_15/local/release/lib64

[Pipeline_log.txt](https://github.com/lofar-astron/prefactor/files/224001/Pipeline_log.txt)
[pipeline_cfg.txt](https://github.com/lofar-astron/prefactor/files/224003/pipeline_cfg.txt)

[Pre-Facet-Cal-3C295_parset.txt](https://github.com/lofar-astron/prefactor/files/224007/Pre-Facet-Cal-3C295_parset.txt)

**Comment by fe56** [comment]
Looks like you have two different versions of hdf5 on your system and used one for the lofar software and one for the requirements.
1) /usr/local/lofar-2_15/local/release
2) /usr/local/hdf5-1.8.15-patch1
You need to compile everything with one version or try disable the version check via environment variable as the error message mentions (not recommended).

**Comment by AHorneffer** [comment]
My suggestion is to fully kick out one of the two installations of HDF5. PyTables (and thus LoSoTo) should work with either of them, just not with both of them mixed together.

The best approach depends on your local setup. (The HDF5 installation in /usr/local/lofar-2_15/local/release seems to be done by root, so maybe that's harder for you to remove. Another question is which libraries are used by casacore?)

**Comment by AHorneffer** [comment]
I assume this works now. If there are further problems, please reopen the issue.
