### ISSUE TITLE
wsclean segfaults with padding (trim)

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#37]
Using the padding (trim) options in Initial-Subtract (in commit https://github.com/lofar-astron/prefactor/commit/6d13f127833c503215a22c3d2e05f62483b79ff5), I'm now getting a lot of segfaults from wsclean.

It could be that the new size is not a bsmooth number (I am surprised that this makes it segfault and not just inefficient) -- in one test case I changed the "-size 8601 8601  -trim 5376 5376" to  "-size 8640 8640  -trim 5379 5379" so size is bsmooth and it no longer segfaults.

I changed in the pipeline InitSubtract_sort_and_compute script the  `imsize_*_pad` so that it is also computed by `get_optimum_size` and with that change I had no more segfaults on 24 bands. 
See https://github.com/wllwen007/prefactor/commit/7ccf41ed9a4111ce8f236a6094654e16edd3dcf2

I guess here that size should be a bsmooth number, but trim does not necessarily have to be (anyone know for sure?) - I've just made them both bsmooth as that was quicker to implement.
(presumably `imsize_*_pad_stretch` should also be bsmooth but I haven't tested the y-stretching)

**Comment by AHorneffer** [comment]
I find it hard to see why 5376(=3*256*7) is worse than 5379(=3*11*163), but using `get_optimum_size()` in the size calculations seems to be a good idea!
