### ISSUE TITLE
allow for pb corrected imaging of direction independent calibrated data

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#38]
The direction dependent calibrated images are sometimes still pretty decent if you get good observing conditions (I find that you can get as low as 250uJy/beam noise for the full bandwidth at 25arcsec resolution). So, if people don't want to go through the direction dependent process it would be good to give the option of primary beam corrected images.

I guess there are two ways of doing this, the first being to change the bbs calibration to not remove the beam and then allowing the user to image the data themselves. Alternatively, perhaps the option that would result in accidental operations errors would be to have a switch in the parset to enable primary beam correction the high2 images made during the source subtraction (wsclean has the beam now? or could just do similar to factor and use awimager pbimages to correct the images).

**Comment by rvweeren** [comment]
The easiest way is to enable the primary beam correction in wsclean and that only needs one extra switch in the wsclean call (you need the latest/development wsclean version for that). That should cost only a few minutes of extra runtime and requires basically no code changes (apart from updating the wsclean call)

**Comment by twshimwell** [comment]
Yeh that would be the best way to do it. The MFS image that is output by wsclean is presently not primary beam corrected. I mentioned it to Andre and he said it isn't very hard to do. So probably good to wait for that functionality.

**Comment by rvweeren** [comment]
Andre already coded this and I think it is available in the latest WSClean version.

**Comment by twshimwell** [comment]
Sounds good if it is coded already. In the version I have the channel images can be primary beam corrected but the MFS isn't  (https://sourceforge.net/p/wsclean/wiki/LOFARPrimaryBeamCorrection/)

**Comment by twshimwell** [comment]
In v2.0 André has kindly implemented this feature --  https://sourceforge.net/p/wsclean/tickets/82/ so it could go into initsubtract now

**Comment by AHorneffer** [comment]
Hmmm... What do you want?

I think it might be nice, if the channel images (or at least the model images) out of WSClean were **not** PB corrected so that we can use them to subtract the sources, but the MFS image was PB corrected so that Tim has a nice image to look at.

Another issue is mentioned at: https://sourceforge.net/p/wsclean/wiki/LOFARPrimaryBeamCorrection/

> Currently, beam correction does not work together with baseline-dependent averaging.

**Comment by twshimwell** [comment]
Yes I don't mind much about the channel images but I was kind of assuming that if pbcorrection was selected both pbcorrected and uncorrected images would be output.

The MFS image if primary beam will be perhaps be sufficient for some science. Also to check the flux scale of the images it may be useful.

Shame it doesnt work on baseline-dependent averaging at present as speed is pretty handy in this step.

**Comment by adrabent** [comment]
Added with commit: https://github.com/lofar-astron/prefactor/commit/378a399bd0dbbc987b4281c1ce8465a20765af2d
