### ISSUE TITLE
phase plotting

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#4]
Would it not be better to plot very small dots/points, instead of continuous lines. Phases that wrap often (or that are close to +/- pi) look very confusing.

**Comment by AHorneffer** [comment]
I plan to change the plots of the target phase solutions to matrix plots like the ones that Alexander shows on:
http://www.lofar.org/wiki/doku.php?id=commissioning:imag_busy_week_24:a2069

**Comment by rvweeren** [comment]
Yes, these matrix plots look nice.

**Comment by twshimwell** [comment]
Another option would be to change the aspect ratio. If you have a small y-axis and big x-axis you can see phases that wrap very quickly  (see e.g. http://lofar.strw.leidenuniv.nl/wiki/lib/exe/detail.php?id=p209_55_factor&media=p209_55_3c295_phasesols.png which shows phase solutions from RS210 to CS001, RS310 to CS001 and RS509 to CS001)

**Comment by rvweeren** [comment]
Ah yes, was just thinking about that as well (in particular for the distant RS stations we need more space along the x-axis, because it is impossible to judge from these small plots). I also like matrix phase plots, but for spotting problems on the remote stations we need much longer x-axis. 

(I was trying to spot pi-jump errors for the DDE selfcal and the current tec plots are simply not good for that)

**Comment by AHorneffer** [comment]
.oO(You do remember that this is the issues section of prefactor? So there is no direction dependent stuff done here. :-) )

I added LoSoTo matrix-plots to Pre-Facet-Cal.parset. 
To make LoSoTo work with the genericpipeline in a nice way I needed to patch the executable_args node-script. This is in the latest trunk of the LOFAR software, or you can aplly this diff manually:
```
> diff new_version_of/executable_args.py .../CEP/Pipeline/recipes/sip/nodes/executable_args.py
104,107c104
<                 if argsformat == 'losoto':
<                     args.append(parsetname)
<                 else:
<                     args.insert(0,parsetname)
---
>                 args.insert(0, parsetname)

```

**Comment by rvweeren** [comment]
Sorry, my second comment was indeed more related to the phase plotting in factor. I'll add it there.
