### ISSUE TITLE
Images for skymodels not found in v2.0-devel

### ISSUE THREAD

**Issue by shulevski** [lofar-astron/prefactor#42]
The low and high images for extracting the models are not at the location expected. I thought that the move_high2 and move_low2 steps should do the job, but apparently not; there is a file not found exception. Once I move the images manually, all is well.

**Comment by wllwen007** [comment]
Which step exactly is failing?

We fixed a bug yesterday because plot_im_high  gave file not found errors because the images had already been moved away... see https://github.com/lofar-astron/prefactor/commit/a48e6a6e05947a486fb65e2419bfc9b0ef903c0f, but that doesn't sound like what you mean.

**Comment by shulevski** [comment]
Actually, I think that that is exactly what was causing the problem. I was using an older version, so it should now be fine in the latest one. Closing the issue. Thanks!
