### ISSUE TITLE
RMextract table locks on transfer

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#45]
I get errors from transfer_gains_RMextract  table locks on the instrument tables (instrument_amp_clock_offset). This happens sporadically and randomly - on about 10 out of 240 MSs being processed.

I've made a few tweaks to the transfer script -- to get the common rotation values first (the timeconsuming step using RMextract - takes about 30min per MS), and only then open the parmdb and write all the values, and then flush the parmdb.

That seems to have fixed my problem, but I'm not sure why I ran into table lock issues in the first place.

I suppose the get_ion_script could run getRM and save the single rmdict to be used in the transfer script for all MSs

**Comment by AHorneffer** [comment]
Can you attach the logfile with the actual error messages here?

As far as I can see the only way that your code treats the parmDBs differently is the order in which the values are written to the table.
