### ISSUE TITLE
Initial subtract on low declination fields imsize

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#48]
The image sizes at low declinations are huge because the x and y directions are both scaled up by the stretched beam size 1/sin(mean_elevation) -- in my case nearly a factor 2 -- when it is only really the y direction that needs to be scaled up. It may be better to make rectangular images and only stretch the y direction, see https://github.com/wllwen007/prefactor/commit/efb426d39e4d220d56bb436211deab4c8287eb13

**Comment by darafferty** [comment]
I've tried making rectangular images (with the "axis_stretch" parameter in the parset) and it worked well. However, there is a bug in PyBDSM that I'm trying to track down that produces incorrect masks for rectangular images. Wendy, did you encounter this yet?

**Comment by wllwen007** [comment]
Not yet, it's still making all the high1 images. I guess I can look forward to encountering the bug.

**Comment by darafferty** [comment]
I found the bug in PyBDSM and committed the fix to the trunk, so if you update it should work now.

**Comment by wllwen007** [comment]
> I found the bug in PyBDSM and committed the fix to the trunk, so if you update it should work now

Yes, that fixes it. The rectangular image masks look alright now.
