### ISSUE TITLE
plotting of results (images, masks)

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#5]
Would be helpful to automatically generate the low and high-res png images + plot mask contours on top of  that in the Initial-Subtract.parset.

(could use aplpy)

**Comment by wllwen007** [comment]
Yes, I have some initial code that should do this, I just need to test it in the pipeline framework.

In the meantime I've been copying the images also to the output directory with the following steps in my initial subtract parset...

# copy the merged skymodels to the directory with the input data, length = nbands
copy_images_high.control.kind                     =  recipe
copy_images_high.control.type                     =  executable_args
copy_images_high.control.executable               =  /bin/cp
copy_images_high.control.mapfile_in               =  wsclean_high2.output.wsclean_high2-image.fits.mapfile
copy_images_high.control.inputkey                 =  source
copy_images_high.control.arguments                =  [source,{{ data_input_path }}]

# copy the merged skymodels to the directory with the input data, length = nbands
copy_images_low.control.kind                     =  recipe
copy_images_low.control.type                     =  executable_args
copy_images_low.control.executable               =  /bin/cp
copy_images_low.control.mapfile_in               =  wsclean_low2.output.wsclean_low2-image.fits.mapfile
copy_images_low.control.inputkey                 =  source
copy_images_low.control.arguments                =  [source,{{ data_input_path }}]

**Comment by AHorneffer** [comment]
Have a look at the stuff in the "v2.0-devel" branch, featuring the all-new "inspection_directory" in Pre-Facet-Cal.parset and Initial-Subtract.parset.
The restored fits-images are not used by the pipeline, so I choose to move and not copy them.

Generating png files from the images is already on my todo list, if you want contours of the masks, then it would help if you could send me a script or just some example code to do the contours. Well, and looking at my agenda for the next weeks, I don't believe I'll get around to that before the LOFAR conference in Zandvoort.

**Comment by rvweeren** [comment]
Attached an example I made.

![l343226_sbgr031-10_uv dppp pre-cal wsclean_high2-image](https://cloud.githubusercontent.com/assets/3879473/13827220/b158ca1c-eb91-11e5-8272-2d8306fe4700.png)

**Comment by AHorneffer** [comment]
Thanks.
I guess if we also change to use the wideband mode of wsclean, then we only need/want the png from the MFS image, correct?

**Comment by rvweeren** [comment]
Yes.
