### ISSUE TITLE
Frequency smoothing in amplitudes_losoto_3.py fails when few subbands are used

### ISSUE THREAD

**Issue by adamdeller** [lofar-astron/prefactor#50]
I was testing the prefactor pipeline with a very small subset of data for speed, and the amplitudes_losoto_3.py script barfed because the shape of two arrays didn't match.  After some investigating, I found that the savitzky_golay filter was extending the amplitude array it was smoothing, because it had a filter length of 17 and I only had 5 subbands.

My work around was to disable this smoothing if the number of subbands was less than the filter length.  I can commit this if desired.  At the same time, I have a question: it is unclear to me why the length of the frequency array becomes nsubbands - 1.  Probably this is for a good reason, but it wasn't clear to me.

Finally, in doing this I also noticed that the assumption of 4 chan/subband was baked in to the example Pre-Facet-Cal.parset.  You can change the freq averaging at the top of the parset, but the invocation of amplitudes_losoto_3.py further down assumes 4 channels/sb.  I can change and generalise this and re-commit if desired.

**Comment by twshimwell** [comment]
This "feature" is kind of a safe guard because the prefactor pipeline should only be run with a large number of subbands otherwise the clock cannot be derived and the results will be bad. So I would be a little reluctant to put in a work around when there are few subbands.

Hmmm yes the amplitudes losoto is called with 4 channels/sb but this should be generalised.

**Comment by AHorneffer** [comment]
I agree with Tim's sentiment about not having enough bandwidth in the first place! We should put an explicit error message into the code somewhere.

About the 4 ch/SB: IIRC if you get this wrong then you'll mess up the plots but the transfer should still be fine. (But I don't know exactly right now.) A clean-up / rewrite of that code is also waiting for a conclusion on answers to the questions I posed in: #35

**Comment by twshimwell** [comment]
Adreas will put in an error message in amplitudes_losoto3.py
