### ISSUE TITLE
Peeling script?

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#51]
Do we need a peeling script, to peel away strong sources that mess up the Initial-Subtract?
(Like 3C295 in the M101 data.)

**Comment by twshimwell** [comment]
Perhaps this is a little related to this ticket -- https://github.com/lofar-astron/prefactor/issues/57 but just dealing with sources fainter than the A-team ones. However, a consistent approach for bright sources within the region mapped by initial-subtract would be good.

**Comment by AHorneffer** [comment]
Deferred for now. Please re-open when there is more interest.
