### ISSUE TITLE
Merge branches?

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/prefactor#52]
There are too many (diverging) branches here. Can anyone explain what can be cleaned up?

**Comment by AHorneffer** [comment]
That's the github way: to have a branch for every topic you are working on.
- master is the last release (plus bugfixes)
- v2.0-devel is the latest "stable"
- RMExtract, deepimage, and dppp-gaincal are issues that are being worked on.
- pdf-doc is the version with my old pdf documentation that isn't approved by ASTRON (yet?)

So there are not too many branches.

**Comment by tammojan** [comment]
Who at ASTRON do you expect to approve the pdf-doc branch?

**Comment by AHorneffer** [comment]
The editor of the LOFAR cookbook.
