### ISSUE TITLE
Rescale 3C196 calibrator skymodel

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#53]
The 4-component skymodel for 3C196 does not have the total flux according to the Scaife & Heald flux scale. It should be rescaled to that.

**Comment by twshimwell** [comment]
The sky model that we are using here (17th April 2014) is very close to the Scaife & Heald. The older models are perhaps a little more discrepant but we are not using them here. The python code below gives a comparison of the fluxes. I think the agreement is good enough to close this issue.

[find_fluxes.txt](https://github.com/lofar-astron/prefactor/files/346606/find_fluxes.txt)
