### ISSUE TITLE
List with amplitude solutions

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#54]
To figure out which subband is bad a text-file with the subband numbers and gains would be useful.

**Comment by twshimwell** [comment]
I have added to the amplitudes_losoto_3.py to output a text file (*amplitude_array.txt which corresponds to the *amplitudes_array.npy) that has the format:

Antenna name, Antenna ID, subband, XXamp, YYamp

This updated code is tested and is in the bin of the structurefunction branch.

**Comment by twshimwell** [comment]
As a slight aside amplitudes_losoto_2.py should probably be removed from the repository as it isnt used and is the older version of amplitudes_losoto_3.py

**Comment by AHorneffer** [comment]
Included in branch v2.0-devel now.
