### ISSUE TITLE
Better bookkeeping for deep images

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#56]
The deep-imaging Initial-Subtract pipeline (discussed in #7) should offer more flexibility for the imaging:
- Image not all bands but just a given number of bands together, so that there are more imager processes running at the same time. (E.g. specify `num_bands_per_image`)
- Do not  generate one channel-image per band but only one per a given number of bands and then use the same sky-model for a number of bands. (E.g. specify `num_bands_per_channel`)

That way by setting  `num_bands_per_channel = 1` and  `num_bands_per_image = 1` one gets the behaviour of the "old" non-deep initsubtract, and by setting `num_bands_per_image = num_bands` the behaviour of the deep init-subtract, and with other settings one can fine-tune the performance.

When this is done we only need one Initial-Subtract pipeline anymore.

**Comment by twshimwell** [comment]
In this updated script it would also be good to adjust the threshold to a suitable value that depends on the amount of data being imaged. The threshold as that can be estimated from the amount of data (which is already known in magic script) as say 0.1/(bands**0.5*inttime**0.5) which corresponds to 7mJy for an 8 hr observation with 24 bands. This is most likely an overestimate of the noise but I think would probably be ok for the high1 and low1 images.
