### ISSUE TITLE
Update A-team clipping

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/prefactor#57]
Problem: the A-team clipping is very slow, and doesn't really work.

Solution:
- Remove a-team clipping.
- If A-team source closer than 30 degrees, ensure the A-team source is in global sky model

In both cases deal with the A-team signal by demixing (or maybe sagecal or killms) after the subtract step so that the field has already been subtracted (if the A-team source is in the images made at the subtract step then they will need to be added back).

**Comment by twshimwell** [comment]
For version 3.0. But for version 2.0 change the predict to NDPPP.
