### ISSUE TITLE
Start using TGSS for sky model and automatically create

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#58]
See http://tgssadr.strw.leidenuniv.nl/doku.php for how to create the model.

Perhaps take a 5deg radius model, filter out components less than 100mJy(?), add in Ateam sources if required (see https://github.com/lofar-astron/prefactor/issues/57)

**Comment by AHorneffer** [comment]
Before you put in something that won't work on all machines: Some clusters (like JUROPA) do not allow access to the outside world from a processing node.

**Comment by twshimwell** [comment]
Oh ok. Maybe it could be made that the model could be created from the catalog rather than a wget?
