### ISSUE TITLE
Make rectangular images?

### ISSUE THREAD

**Issue by darafferty** [lofar-astron/prefactor#6]
WSClean 1.11 has the option to make rectangular images, which could be useful for low dec fields. I'm not sure if it makes much difference in practical terms (speed, etc.), but it's probably worth investigating.

**Comment by AHorneffer** [comment]
With commit [6d13f12 ](https://github.com/lofar-astron/prefactor/commit/6d13f127833c503215a22c3d2e05f62483b79ff5) I added scaling the height of the images to Initial-Subtract. I believe this implements rectangular images. Please give it a test and let me know if this works.

**Comment by AHorneffer** [comment]
I assume this works. If it doesn't, then please re-open the issue.
