### ISSUE TITLE
convert gsmcal.parset to NDPPP

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#60]
NDPPP will be much faster and this is the slowest part of the pipeline.

**Comment by AHorneffer** [comment]
I just push a first version of this onto the dppp-gaincal branch. It was copied&pasted together in ca. 30min, so: **Please test it!!!**

**Comment by carosko** [comment]
Some results from the NDPPP version of the target phase calibration in the preFactor **master branch**. 
(Adapting it to and testing it in the dppp-gaincal branch should be now a just a question of short time, finally)

**-> Concerning the data used for this quick test** :
- They are ("bad quality") data set from cycle0
- Interleaved (30min on the target, 40SBs used, grouped in 10) 



**-> Phase solutions:**
- For quiet data/ionosphere, the XX and YY solutions are very close to each other, especially for the core stations. (They are similar and, at least, behave the same way for the remote ones)
- For some time chunks, when the ionosphere is very choppy, the BBS preFactor gives smoother solutions than this first attempt by NDPPP (if we don't have to consider these results as failed).

(The solutions' plots are generated by a script adapted from Wendy's _plot_solutions_all_stations.py_. For each station, they show:

1. in the first plot of each station, the XX solutions: in green are the BBS results and in red the NDPPP ones.
2. Same in the second plot for the YY solutions.
3. The difference between solutions of the BBS and NDPPP runs (in blue the XX, a the YY in green)

**-> The high2 maps** created by Initial-Subtract are similar for the BBS and NDPPP versions (10SBs, one good time chunk). When subtracting the BBS from the NDPPP fits, the result is coherent (max ~40mJy), but a pattern can be found around several sources (if not all of them); it looks like sides lobes and can be either positive or negative but has the same shape.


**->** Finally, it seems that the syntax for the parameters of the **beam** are correct, and that the beam is correctly applied: no negative bowls in a low1 maps from Initial-Subtract (same data than for the high2).

**->** Also, for curiosity, a very rough estimation of the speed: for 40SBs and 16*30min, the target's steps of the preFactor pipeline took ~19h "human time" for the BBS version, and ~16h for NDPPP (the node was busy with other and different tasks during their running time).


**Plots:**

-> High2: NDPPP-BBS ("fits on request"):
![is_high2_ndppp-bbs_zoom](https://cloud.githubusercontent.com/assets/20458825/17410669/fe46d11e-5a74-11e6-938e-b656267755d2.jpeg) 
![is_high2_ndppp-bbs_zoom2](https://cloud.githubusercontent.com/assets/20458825/17410844/c2ea681e-5a75-11e6-9d55-383ad721d2ec.jpeg)

-> Low 1:
![low1](https://cloud.githubusercontent.com/assets/20458825/17410970/6207d9ae-5a76-11e6-95da-892480dbe118.jpeg)

-> XX and YY solutions:
![l165238_sbgr017_phase](https://cloud.githubusercontent.com/assets/20458825/17411032/b559bcf8-5a76-11e6-88e0-d0c91c1522c1.png)
![l165240_sbgr018_phase](https://cloud.githubusercontent.com/assets/20458825/17411054/c8773da6-5a76-11e6-88b2-9b09bf7b34be.png)

(an example of "bad" time chunk:)
![l165266_sbgr018_phase](https://cloud.githubusercontent.com/assets/20458825/17411091/ed54fa1e-5a76-11e6-8de8-6a988594a905.png)

**Comment by wllwen007** [comment]
I tried using the **dppp-gaincal** branch for some target calibration. I don't have any comparisons with a bbs version, but came across a small bug that losotoImporter.py complains that there is no 'sky' directory in the calibrated ms's (because dppp doesn't write this). 
In this case the source table is not needed because the solutions have no directions.

**Comment by nudomarinero** [comment]
I think that losoto always requires a sky directory so this problem will affect losoto as well. Maybe it could be useful to take the direction of the MS (from a default value) if the sky file is not specified.

@wllwen007 could you list the content of the MS to be sure that we have the required (sub)table to extract the default direction value?

**Comment by nudomarinero** [comment]
@wllwen007 I think we would need the "FIELD" sub-table to extract the phase centre but I would like to be sure that this sub-table is there in general.

**Comment by AHorneffer** [comment]
Included in branch v2.0-devel now.
