### ISSUE TITLE
call RMwriter once per time-step not once per MS

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#61]
As discussed in #22 the latest version of the Pre-Facet-Target.parset includes correction of the ionospheric Faraday rotation with RMextract. 

The current implementation calls RMextract once per input MS. But the RotationMeasure is independent of frequency, so there is only need to call it once per time-step. RMextract does take some non-negligible time, so changing this would make a difference.

**Comment by AHorneffer** [comment]
A side issue: Maaijke told me that NDPPP can now correct for "commonrotationmeasure" (or however you chose to spell it). Is that true? (It is not mentioned on the [NDPPP wiki pages](http://www.lofar.org/wiki/doku.php?id=public:user_software:ndppp#applycal).)

**Comment by tammojan** [comment]
Yes, that's true. Sorry for not mentioning it on the wiki, I added it. Note that you have to use your own tools for adding a parameter called "RotationMeasure" to the parmdb (BBS or DPPP can not do that).

**Comment by AHorneffer** [comment]
Hmmm...
Is now the "RotationMeasure" that BBS uses different from the "RotationMeasure" that NDPPP uses? Because the former is a direction- (patch-) dependent parameter and the latter is not?

Otherwise: it is clear that I need to generate the  "RotationMeasure" values in the parmDBs myself. That's what we use RMextract for.

**Comment by tammojan** [comment]
Ok. About the Hmmm: see https://support.astron.nl/lofar_issuetracker/issues/9273 . I think the idea there makes sense: make the `Common` prefix optional, and make a `Directional` prefix obligatory for directional parameters.

**Comment by twshimwell** [comment]
Given the -timestep = 300 option that is now used in rmextract it is really pretty fast (issue #86). Perhaps we don't need to worry about this issue now and can close this ticket too?

**Comment by AHorneffer** [comment]
But I want to, so it stays!
