### ISSUE TITLE
utilise baseline dependent averaging in initsubtract

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#62]
Andre has put this option in the latest version of wsclean. Tests by Reinout and Andre show it will give a big speedup (maybe ~7) in the imaging. To use this the nwavelengths option needs calculating for the high and low images.

**Comment by twshimwell** [comment]
The FACTOR way of doing this is:

        # Set the baseline-averaging limit for WSClean, which depends on the
        # integration time given the specified maximum allowed smearing. We scale
        # it from the imaging cell size assuming normal sampling as:
        #
        # max baseline in nwavelengths = 1 / theta_rad ~= 1 / (cellsize_deg * 3 * pi / 180)
        #
        # nwavelengths = max baseline in nwavelengths * 2 * pi * integration time in seconds / (24 * 60 * 60)

Here seems fine to do the same at least for first testing. I'll put this into the init subtract magic script.

**Comment by AHorneffer** [comment]
This is currently only implemented in `Initial-Subtract-Deep.parset`. So I leave this issue open for the time being.

**Comment by darafferty** [comment]
I added the required calculations to the non-deep version of the magic script so that the `Initial-Subtract-Fast` pipeline (on the experimental branch only) can use it as well. It's still not available in the `Initial-Subtract.parset`, though.
