### ISSUE TITLE
Give final time and frequency resolution in averaging step rather than the amount of averaging

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#66]
Perhaps giving the final time and frequency resolution in the parset would simplify matters a little and make the default parameters more suitable. Would require a simple script (which is probably already part of factor).

**Comment by AHorneffer** [comment]
I would prefer if it would be possible to specify it this way in NDPPP. (We discussed about this some time ago.)

**Comment by tammojan** [comment]
Agreed, I'll put it on my to do list (it's been there for a while).

**Comment by AHorneffer** [comment]
Well, my question was also: "Should we add an extra script to prefactor, or shall we wait until it is implemented in NDPPP?"

Maybe we can discuss this on Wednesday.

**Comment by twshimwell** [comment]
Yeh can discuss on Wednesday but i suspect Tammo's todo list is quite long so maybe a simple script is good for prefactor for now.

**Comment by twshimwell** [comment]
not that other peoples todo lists are not long :)

**Comment by tammojan** [comment]
Actually this should be trivial to implement. So better have it in the right spot (DPPP) than have workarounds. How should this be specified? One way I think should be nice if `nchan` can have two meanings: the current one, and the meaning you have in mind (the number of output channels). The meaning can then be set with a new option: `nchanmeansnumberofoutputchannels`, which could be false by default (the current behavior). The reason of not just making up a new option `nchan2` or something is then specifying both `nchan` and `nchan2` would mean something strange. If you agree with this, what would be the correct name for the key `nchanmeansnumberofoutputchannels`?
And can you think of something similar for `ntime`?

**Comment by AHorneffer** [comment]
Well, what one actually wants to specify is the output resolution in physical units, e.g. "4 seconds" or "50 kHz".

My suggestion for the implementation would be:
- For ease of implementation the user can only give a single floating point value with the unit(s) being fixed (seconds and Hz come to mind).
- This is then converted to an averaging step. (And rounded down? up? Or to the nearest integer?)
- Only if the averaging step from this computation is larger (= more averaging and fewer output channels) than the averaging step given by `timestep` or `freqstep`, then the computed stepsize is used.
- If the final stepsize is larger than the input data, then it is truncated to the size of the input data. (As it is already done.)

That way you can specify simple default values (1 Hz, 0.1 s) and not change the current behavior. And there is a clear behavior if strange values are supplied.

**Comment by tammojan** [comment]
Hi Andreas, that looks good. Perhaps the default can be 0 Hz or seconds to do nothing. I can implement this after my vacation (15 august).

**Comment by tammojan** [comment]
See https://support.astron.nl/lofar_issuetracker/issues/9783 , and the documentation at http://www.lofar.org/wiki/doku.php?id=public:user_software:ndppp#averager (note: it's not in the trunk yet).

**Comment by AHorneffer** [comment]
It is implemented now in the pipeline parsets on the experimental branch.
