### ISSUE TITLE
concat step fails if less than 10subbands

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#67]
Whilst not very often an issue and not something major. The concat step seems to fail if there are less than 10 subbands. This is an issue when we are running on surfsara because we split the target dataset into groups of 10 when running and because we have 244 subbands one of the groups actually only contains 4 subbands.

**Comment by wllwen007** [comment]
Strange, I think I have successfully run like this. sort_times_into_freqGroups should drop off the last incomplete band and create 24 groups of 10 files.
Also if there are missing bands the concatenation shouldn't be a problem as it should just fill with dummy data. Do you have some output/log to show the exact problem?

**Comment by twshimwell** [comment]
244 subbands does work fine and properly deals with the 4subbands at the end. It is just when running the entire pipeline with only 4 subbands throughout that we seem to get an error (so ndppp_prep_target only has 4 entries). 

I think it is due to this step anyway. I have attached the end of the sara log but the error is a KeyError after the ateamclipper step is complete (so I thought likely an error in the concat mapping).

[error.txt](https://github.com/lofar-astron/prefactor/files/390722/error.txt)

**Comment by fe56** [comment]
hmm so its the plugin after the ateamclipper step?

can you attach the dpppaverage.output.mapfile so i can try to reproduce it next week?

**Comment by twshimwell** [comment]
Yeh I think the sortmap_tar step. 

Hmmm I no longer have the dpppaverage.output.mapfile on sara unfortunately. I can make a new example if needed though.

**Comment by AHorneffer** [comment]
Hmmmm, it says:

> sortmap_target.argument.truncateLastSBs  = True # This means that a excess subbands that don't make a full group get discarded

So it does what it is supposed to do if you give it less than `num_SBs_per_group` subbands, then it cannot make a full group and discards everything. If you want a different behavior, then have a look at `bin/sort_times_into_freqGroups.py`:
```
    mergeLastGroup, truncateLastSBs : bool, optional
        mergeLastGroup = True, truncateLastSBs = True:
          not allowed
        mergeLastGroup = True, truncateLastSBs = False:
          put the files from the last group that doesn't have SBperGroup subbands 
          into the second last group (which will then have more than SBperGroup entries). 
        mergeLastGroup = False, truncateLastSBs = True:
          ignore last files, that don't make for a full group (not all files are used).
        mergeLastGroup = False, truncateLastSBs = False:
          keep inclomplete last group, or - with NDPPPfill=True - fill
          last group with dummies.      
```
(Although I'm not sure that I actually tested all combinations.)

**Comment by AHorneffer** [comment]
O.K. it doesn't deal too gracefully with that situation. But the result is the same: the pipeline should stop immediately.
 
Remind me to put in an explicit error message for this case.

(P.S. The internet here in the hotel sucks!)

**Comment by twshimwell** [comment]
The error is just:

2016-07-29 11:50:45 ERROR   genericpipeline: *******************************************
2016-07-29 11:50:45 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Cal
2016-07-29 11:50:45 ERROR   genericpipeline: Detailed exception information:
2016-07-29 11:50:45 ERROR   genericpipeline: <type 'exceptions.KeyError'>
2016-07-29 11:50:45 ERROR   genericpipeline: 47
2016-07-29 11:50:45 ERROR   genericpipeline: *******************************************
2016-07-29 11:50:45 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2016-07-29 11:50:45 WARNING genericpipeline: recipe genericpipeline completed with errors

**Comment by AHorneffer** [comment]
So it should tell you now why it failed.

And I saw that `mergeLastGroup` is not implemented. If you want to have that, then please let me know.

**Comment by twshimwell** [comment]
Thanks.

It may be nice to have to the option to keep the last group even if it isn't the full number of subbands 

(I guess this option
        mergeLastGroup = False, truncateLastSBs = False:
          keep inclomplete last group, or - with NDPPPfill=True - fill last group with dummies.      
)

But its not a big deal at all (on sara Alex has now changed it so that we just alter the number of files in the concat step to the number of files we are sending to a node) so certainly very low priority and I don't mind if you close the ticket.

**Comment by AHorneffer** [comment]
> It may be nice to have to the option to keep the last group even if it isn't the full number of subbands 

In that case just set  `sortmap_target.argument.NDPPPfill` to `False` in the pipeline parset.

> But its not a big deal at all (on sara Alex has now changed it so that we just alter the number of files in the concat step to the number of files we are sending to a node) so certainly very low priority and I don't mind if you close the ticket.

Why the *bleep* would you want to do that? You do realize that this means you will have problems using the output of such a pipeline with Factor?

**Comment by twshimwell** [comment]
Ha, ok. Yes... Alex will unchange it on sara and set sortmap_target.argument.NDPPPfill to False

**Comment by AHorneffer** [comment]
Arrrgh! Of course it isn't `sortmap_target.argument.NDPPPfill` that you need to set to `False`, but `sortmap_target.argument.truncateLastSBs`!
