### ISSUE TITLE
Flag bad phase solutions for the target field with losoto

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#68]
Time periods where the phase varies rapidly can now be identified in losoto (see ticket #12 for details and demonstration). In this code the flagging is done by looking at phase solutions for all core stations and a reference station. Then the data is smoothed a bit. The smoothed phase solutions and subtracted from the solutions and the flagging is done on the rms of the residual and also relies on seeing bad data on a given number of baselines. The losoto parset for this operation is given below and could be put into the pipeline. Once the gsmcalibration solutions are obtained this can be run and then once the solution tables, which have been updated with flags, are applied the data should get flagged.

LoSoTo.Steps = [flag]
LoSoTo.Solset = [sol000]
LoSoTo.Soltab = [sol000/phase000]
LoSoTo.SolType = [phase]
LoSoTo.ant = CS*
LoSoTo.pol = [XX,YY]
LoSoTo.Steps.flag.Operation = FLAG
LoSoTo.Steps.flag.Mode = smooth
LoSoTo.Steps.flag.Order = 5
LoSoTo.Steps.flag.ant = []
LoSoTo.Steps.flag.Cycles = 1
LoSoTo.Steps.flag.FixRms = 0.012
LoSoTo.Steps.flag.PlotFlag = True
LoSoTo.Steps.flag.Reference = CS001HBA0

LoSoTo.Steps = [flagextend]
LoSoTo.Solset = [sol000]
LoSoTo.Soltab = [sol000/phase000]
LoSoTo.SolType = [phase]
LoSoTo.pol = [XX,YY]
LoSoTo.Steps.flagextend.Operation = FLAGEXTEND
LoSoTo.Steps.flagextend.Axes = [ant]
LoSoTo.Steps.flagextend.Percent = 10
LoSoTo.Steps.flagextend.Size = [0]
LoSoTo.Steps.flagextend.Cycles = 1

**Comment by AHorneffer** [comment]
Hmmmm...
Can we have a version of NDPPP that takes a LoSoTo file as input for `applycal`? **SCNR ;-)**

**Comment by adrabent** [comment]
This is done, since we moved fully to LoSoTo handling the calibration solutions
