### ISSUE TITLE
Standard Prefactor testing

### ISSUE THREAD

**Issue by shulevski** [lofar-astron/prefactor#69]
Develop a standardized test procedure using a dedicated test data set. 10 minute full BW calibrator run and 10-20 SBs on target.

**Comment by AHorneffer** [comment]
Hmmm, let's think what we want of the data:

- available to everyone
- not too big to download
- can be processed by prefactor and Factor automatically (no complicated stuff in there that requires manual tweaking of the parameters)
- runs quite fast in prefactor and Factor (well, for certain values of "fast")

Anything else?

**Comment by HannoSpreeuw** [comment]
I would really appreciate a working example of prefactor.
I.e. the parsets and a pipeline.cfg.
And a link to the data. 
Or perhaps upload a small Measurement Set to ftp://ftp.astron.nl/outgoing.

**Comment by shulevski** [comment]
Unfortunately, an end-to-end test environment for Prefactor is still not available. The [Prefactor wiki](https://github.com/lofar-astron/prefactor/wiki)  contains some helpful tips tough.

As for test data, the test data for the [examples](https://support.astron.nl/LOFARImagingCookbook/tutorial.html) from the LOFAR cookbook may be useful.
