### ISSUE TITLE
make deep image containing data from all subbands

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#7]
currently factor reads in the *merge files which contain clean components from 10subband images. It may be preferable if in the pre-factor pipeline we would make a deep ~200subband image (by regridding, smoothing and weighted average of 10subband images) and either read that image or a catalog from it into factor. This would allow factor to pick up much more sources and would reduce the chance of sources laying on the facet boundaries.

**Comment by rvweeren** [comment]
A natural way to achieve this would be to use WSclean in wideband mode for the full bandwidth (120-160+MHz). That would keep the frequency dependence of the sky, but making a much deeper image. I think this would make a lot of sense to implement (and it is relatively low-risk and easy) and can completely replace the current medium/low res images for each 10 SB block. This would allow much fainter sources to be included in the skymodel, but keep the frequency dependence for each 10 SB block. (this also avoids stacking, smoothing, regridding and should produce a much better result)

**Comment by AHorneffer** [comment]
You are not the only one to think about that.

It's not as trivial to implement as you might think, because with interleaved observations you get into "too many open files" issues faster than you think. And you loose the ability to spread the computing over several nodes of a cluster.

But the main reason I haven't already implemented that is that I didn't have the time, and probably won't before the Zandvoort conference.

**Comment by rvweeren** [comment]
Maybe use virtual concat for the time chunks (only for the purpose of imaging and avoiding the "too many open files") ?

(imaging can indeed only be done on a single node is this case, however this is not too different from the imaging of facets, facets can also only be imaged at a single node with wsclean (although there is more averaging))

**Comment by twshimwell** [comment]
Or maybe for simplicity and to not worry about the "too many files opened issue" we could make it an option whether the user wants to use the wide band version of the subtract or the narrow band version.

**Comment by AHorneffer** [comment]
That was the plan anyway because one can run several wsclean processes in parallel on multiple node, but cannot do so for a single wsclean process (yet).
But right now "fixing DE601" is higher on my priority list..

**Comment by wllwen007** [comment]
There now is a working version on the deepimage branch
- wsclean is used to make a wideband image with channels equal to the number of input frequency bands
- clean components are taken from the channel images/models and subtracted from the corresponding MSs
- imaging can only be done on one node while the subtract steps could in principle use more
- I don't know if it will work for interleaved obs (may not work or give too many open files errors)

I've tested it on 5 bands only so far - output images:
http://stri-cluster.herts.ac.uk/~wwilliams/L343224_SB000_uv.dppp_1265693ADt_129g.pre-cal.wsclean_high1_deep-MFS-image.plot_im_high_deep.png
http://stri-cluster.herts.ac.uk/~wwilliams/L343224_SB000_uv.dppp_1265693ADt_129g.pre-cal.wsclean_low2_deep-MFS-image.plot_im_low_deep.png

**Comment by twshimwell** [comment]
I am presently testing this for 244subbands. 

The channel images in wsclean (if we use 1band to 1channel) will be the same depth as when we just made separate images for each band. Ideally it would be nice to be able to subtract the faint sources that are only detected in the MFS image as these are pretty numerous (see attached image below which shows a region outside the facet I am working on where you can see the brighter sources are subtracted but the fainter ones are not because they are not detected in the 10subband images -- left is the 10subband facet image and right is the 244subband facet image). Not sure if this is worth it as I don't know how much it will improve the calibration but I estimate that there are ~10sources with a combined flux of say 10-20mJy apparent flux within a typical circle of radius 0.25deg, hence in a radius of say 2deg we expect  nearly 1Jy of flux which we know is there. This seems quite a lot to me. Not sure if anyone else sees similar? 

Could we not use the MFS clean components and some reasonable estimate of the spectral index?

![screenshot from 2016-05-24 17-05-33](https://cloud.githubusercontent.com/assets/12065270/15508974/f6bc40ae-21d1-11e6-8661-95527d4049ac.png)

**Comment by twshimwell** [comment]
(although it may be that this flux is very small compared to the artefacts we have from the subtraction anyway).

**Comment by rvweeren** [comment]
> Ideally it would be nice to be able to subtract the faint sources that are only detected in the MFS image as these are pretty numerous

Does this not happen? WSclean should be run with -joinchannels then picks up the sources in deeper MFS image and cleans and subtracts them. (that is the reason in the first place why we do the "deep" imaging run)

**Comment by wllwen007** [comment]
The wsclean is run with joinchannels, so there should be components in the 'channel' maps detected in the deep image - the channels maps simply give a convenient way to subtract the components with the correct frequency dependence.

Tim, is this the first FACTOR facet after using the deepimage with all 244 subbands. The deepimaging is not fully tested, so you may want to check the masks and images actually look ok. Perhaps it did not clean deep enough?

**Comment by rvweeren** [comment]
>The channel images in wsclean (if we use 1band to 1channel) will be the same depth as when we just made separate images for each band. 

Well, the deep clean should be more accurate even for the channel maps, as in this case it also cleans the faint sources in the separate channels maps. (of course these clean components have very low values as the sources should have peak fluxes around the noise level of the maps).

**Comment by rvweeren** [comment]
Ah my message crossed with Wendy's…

BTW we probably need to increase niter for the "deep" run as there will be many more sources detected.

**Comment by wllwen007** [comment]
> BTW we probably need to increase niter for the "deep" run as there will be many more sources detected.

obvious now in hindsight, but I didn't update that -- the niter in the parset for deep cwslean is the same for 10subbands

**Comment by twshimwell** [comment]
Ah yes, ignore me. No this isn't the facet after the deep clean its from after running the master branch.

**Comment by twshimwell** [comment]
Is it also feasible to speed up this step with something like [https://github.com/lofar-astron/factor/issues/91](url)?

**Comment by wllwen007** [comment]
You mean factor issue 91 (your link doesn't work) - https://github.com/lofar-astron/factor/issues/91

It may be, but not trivially - it would mean some changes in how the subsequent subtract is done. Right now it was simple to implement because the clean components to be subtracted from each 10 subbands using dppp are exactly the clean components in the channel images. The subtract in FACTOR is done with wsclean to do the predict.

**Comment by rvweeren** [comment]
Yes, should be possible here as well, although the bookkeeping might be non-trivial as Wendy explained (one also has to take care of missing blocks in some way). It is really worth to do it in this step anyway ? i.e., How long does such a deep WSClean run typically take?

**Comment by twshimwell** [comment]
Yeh maybe not worth it at present. However this step is time consuming. I am attempting to make deep images of 244subbands using 24cpus (perhaps our cluster is not the fastest) and its taken 2.5days so far and I don't have an full1 MFS files.

**Comment by AHorneffer** [comment]
We could safely reduce the number of output channels for the high1 and low1 images, these images are only used to get a clean mask anyhow.

If the number of wsclean output channels is an even divisor of the number of frequency bands, then re-arranging the input for the predict-steps to make copies of the wsclean channel-maps for the contributing frequency bands wouldn't be a big issue. It is "just programming" so it could be done as soon as someone finds time for it. (Meaning: don't hold you breath!)

Two other issues are: 
- the spectral slope will be approximated with a step function with fewer steps
- missing frequency bands will make the steps of the step function have different widths

**Comment by twshimwell** [comment]
I have run this with 244 subbands on two fields. The time taken for one field was 6 days to produce the MFS high1 image. The other one only took 2 days to get to the same place. Not quite sure why the time taken is so different, perhaps related to other jobs running on the nodes. Anyway, the images are really very deep (less than 100uJy/beam sensitivity when measured well outside the primary beam) and completely full of sources so should be a much better subtraction than before. 

As was mentioned before there are certainly many more iterations (currently 40,000) are needed in the cleaning though  -- see attached image. This will increase the runtime further. Perhaps we should use a threshold (maybe 1mJy) rather than a number of iterations to stop the cleaning?

![screenshot from 2016-05-30 09-13-27](https://cloud.githubusercontent.com/assets/12065270/15642438/af5502a8-2647-11e6-9097-e642007bc340.png)

**Comment by wllwen007** [comment]
Tim, what size image is it making in your case? The difference in runtime could be because of wsclean not having enough memory.

I'm trying it on my equatorial field and am running into serious memory issues, even on a machine with 256 GB. wsclean warns that it doesn't have enough memory and proceeds to use only 2-3 cores out of 32. This is after adding some additional averaging before imaging (from 4ch/4s to 2ch/8s).

**Comment by twshimwell** [comment]
I was just using the default settings 

# size of the image is this value times the FWHM of the station beam
! fieldsize_highres    = 2.5
! fieldsize_lowres     = 6.5

and its a dec~50 field so FWHM is quite normal. However, I did monitor the job a little and noticed it was doing the same as you and just using a couple of threads and lots of memory.

**Comment by twshimwell** [comment]
This issue was discussed a little in the blank fields telecon today and given that it is proving a little tricky to make a single deep image in terms of memory and time perhaps we should:

a) make it so factor can read in a deep image sky model which the user could create by e.g. stacking 10subband images and running pybdsm (see this issue https://github.com/lofar-astron/factor/issues/10). 

b) make the subtract code so that it can combine data from X times 10subband chunks so we can do a better subtract with deeper images but not necessarily using all 244subbands and 10 subband chunk to 1 channel (so could say image 20 or 30 subbands together still or if you had a big computer you could still do all 200plus).

**Comment by rvweeren** [comment]
Could we average down a factor of 2 in time and freq when making this deep image ? Or would we get in trouble with bandwidth/time smearing?

(would make a factor of 4 difference in terms of data size and result in a big speedup).

**Comment by wllwen007** [comment]
> Could we average down a factor of 2 in time and freq when making this deep image ? Or would we get in trouble with bandwidth/time smearing?

yes, I'm currently doing this. I think at this resolution it is fine.

**Comment by wllwen007** [comment]
> b) make the subtract code so that it can combine data from X times 10subband chunks so we can do a better subtract with deeper images but not necessarily using all 244subbands and 10 subband chunk to 1 channel (so could say image 20 or 30 subbands together still or if you had a big computer you could still do all 200plus).

You can trick it for the moment to do this by manually splitting your data_input_path into a few containing only the bands you want and running the deep image pipeline as is with several instances for each data_input_path. (a bit of handwork to set up, but you don't have to mess with the pipeline code and mapfiles before you know it works). My first tests were on 50 subbands (at high dec) and were no slower than doing 5 * 10 subbands.

**Comment by AHorneffer** [comment]
> You can trick it for the moment to do this by manually splitting your data_input_path into a few containing only the bands you want and running the deep image pipeline as is with several instances for each data_input_path.

You can also use `data_input_pattern` if you can come up with a simple enough pattern. (The code benind it essentially only knows the wildcards "*" and "?".)

**Comment by rvweeren** [comment]
I also noted that for the high1 and low1 you can easily get a very significant speedup by changing from channelsout= nbands to channesout=numpy.int(nbands/4). As far as I can oversee this change would not require any other code modification because this is just to make the masks. 

(for high2/low2 you can keep channesouts=nbands to avoid "bookkeeping issues", although it is overkill in terms of precision required…so if one is desperate for speedup one might want to address it for low2/high2 as well)

**Comment by twshimwell** [comment]
I have made deep images (all 244subbands) and I'm pretty happy with the results which are some really very deep images and now M101 is identified and the automatic procedure for selecting the facets manages to avoid it.

<img width="674" alt="screen shot 2016-07-04 at 2 02 00 pm" src="https://cloud.githubusercontent.com/assets/12065270/16559860/15667cfc-41f0-11e6-9ba8-7ff6310581e2.png">

**Comment by twshimwell** [comment]
In the parset I have increased the number of iterations to 400000

I have also edited the magic code to give a new parameter called nchansout_clean1 which is np.int(nchan/4) as suggested above. 

I have edited the parset to now use nchansout_clean1 for the high1 and low1 images.

Perhaps once this is tested we can merge this branch.

**Comment by twshimwell** [comment]
Ongoing discussion in ticket https://github.com/lofar-astron/prefactor/issues/56
