### ISSUE TITLE
ssh jobs not running

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#74]
Hi,

I've been trying to set up prefactor to run on two machines at the same time. I created a test mapfile that has one ms on the local machine, and one on the remote machine. Both have the lofar software installed.

Now, when I run the genericpipeline, I get connection refused errors for 127.0.1.1, and the port seems to be different everytime I run the pipeline. But a task gets startet on the remote machine, but it does not do anything. I guess this is due to the connection refused error.
How I can fix that? Does the remote machine need some kind of listening server? Or can I somewhere change the port used to be standard ssh port 22?

I tested it with sockets in python, and if I try to open a socket on port 22 it works, on every other port I get the same connection refused error.

Thx.

**Comment by AHorneffer** [comment]
Are you running some sort of local firewall? The pipeline system communicates which remote process is to do what by opening TCP connections to more or less random ports between the master and slave machines.

When you do the tests from python, do you make sure that someone is listening on the port you are connecting to?

Another possible problem:  perfactor, like all genericpipeline pipelines, needs a shared file-system. I.e. that the data that is to be processed is reachable from all machines.

**Comment by fe56** [comment]
I suspect that we need a proper cluster description file for this kind of setup. My hunch is that the machine tries to open a connection to itself instead of the other node.

**Comment by AHorneffer** [comment]
I close this for now. Please re-open if this becomes an issue again.
