### ISSUE TITLE
produce plot showing runtime

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#75]
produce a plot showing the runtime of the various different steps.

**Comment by apmechev** [comment]
I have code that does this, however it parses statistics.xml which is not created until the *end* of a pipeline run. So when I include it in the list of steps (even at the end), it complains the statistic.xml file doesn't exist. 

Any idea how to (elegantly) include this?

**Comment by AHorneffer** [comment]
Well, I would suggest to **not** include it in the pipeline in the first place. Most people are not interested in it, so generating it all the time is probably a bit of a waste. But having a script that can be called after a pipeline run would be nice. 

Do you have something that could be included into prefactor? Then it would be great if you could do a pull request to merge your code into the repository.

**Comment by twshimwell** [comment]
I'm certainly falling into the interested category. But yeh, if it is fiddly then I agree that including a script in the repository that the user can then manually run it is still nice.

**Comment by mknapp55** [comment]
FWIW, I would be interested in this option too.

**Comment by adrabent** [comment]
A script for plotting runtime has been added.
Just run `./make_statistics.py` from the commandline like this:
`./make_statistics --obsdir /data/scratch/drabent/working_directory/ Pre-Facet-Target`

You will find the plots in the log-directory.
