### ISSUE TITLE
removal of bad block with close to most data flagged

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#8]
At the end of the Initial-Subtract.parset (or somewhere else) we should check the percentage of data flagged in each 10 SB block. If this is more than ~50% the data should not be used when running factor (important for more automated processing). For example in my dataset I found a block that is ~90% flagged, that will cause serious problems when running factor. Maybe we should let factor check the flagging percentage and remove blocks where this percentage is too high? (or handle it in the prefactor Initial-Subtract.parset?)

**Comment by AHorneffer** [comment]
That is being handled in Factor.

For interleaved datasets, there might be some gain in kicking out MSs with little unflagged data before the phase-calibration to save some computing time.

**Comment by AHorneffer** [comment]
I put a check for this into the Pre-Facet-Cal.parset.
(But haven't tested it yet.)
