### ISSUE TITLE
check make_clean_mask.py

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#80]
There were a lot of changes to the factor version of `make_clean_masks.py`. Check if we want to copy them for prefactor.

**Comment by manuorru** [comment]
Hi Andreas, shame on me that I can not find the info in the documentation. I would like to use Init-subtract deep, but I would like to know if there is a way to provide a cleaning mask to the prefactor. My problem is that the source is extended and diffuse and the mask takes only part of it.

**Comment by AHorneffer** [comment]
The new make_clean_mask.py in the experimental branch allows to do this, but it is not included in the pipeline parset.

It is also normal, that extended emission is not included in the clean-mask of the "high" imaging step, and only picked up in the "low" imaging step.

**Comment by AHorneffer** [comment]
Done #101
