### ISSUE TITLE
getStructure_from_phases.py error if nan values in instrument table

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#88]
Seems to have issues when nan values are present in the instrument table (not sure why nan values are in the instrument table. Is this where the data are flagged or NDPPP can't find a solution perhaps due to a particularly bad ionosphere?)

Error looks like:

```
bins = np.logspace(np.log10(np.min(xplot)),np.log10(np.max(xplot)),10)
File "/software/local/lib64/python2.7/site-packages/numpy/core/fromnumeric.py", line 2224, in amin
out=out, keepdims=keepdims)
 File "/software/local/lib64/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

and when looking the myselect array is all False because dvarx and dvary are all nans

**Comment by twshimwell** [comment]
Perhaps solution is just filtering out the nans.

**Comment by shulevski** [comment]
I see it as well:

> 2016-11-05 22:25:28 WARNING node.flits-06.executable_args.instrument_directionindependent: /home/shulevski/lofar_local/prefactor/scripts/getStructure_from_phases.py stderr: /home/shulevski/lofar_local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)
> /home/shulevski/lofar_local/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> Traceback (most recent call last):
>   File "/home/shulevski/lofar_local/prefactor/scripts/getStructure_from_phases.py", line 211, in <module>
>     getStructure(parmdb,anttab,nr_grid,doplot,outbasename,dofilter)
>   File "/home/shulevski/lofar_local/prefactor/scripts/getStructure_from_phases.py", line 128, in getStructure
>     par=np.dot(np.linalg.inv(np.dot(A,A.T)),np.dot(A,np.log10(y)))
>   File "/home/shulevski/lofar_local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 526, in inv
>     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
>   File "/home/shulevski/lofar_local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
>     raise LinAlgError("Singular matrix")
> numpy.linalg.linalg.LinAlgError: Singular matrix
> 
> 2016-11-05 22:25:28 WARNING node.flits-06.executable_args.instrument_directionindependent: /home/shulevski/lofar_local/prefactor/scripts/getStructure_from_phases.py stderr: Traceback (most recent call last):
>   File "/home/shulevski/lofar_local/prefactor/scripts/getStructure_from_phases.py", line 211, in <module>
>     getStructure(parmdb,anttab,nr_grid,doplot,outbasename,dofilter)
>   File "/home/shulevski/lofar_local/prefactor/scripts/getStructure_from_phases.py", line 96, in getStructure
>     bins = np.logspace(np.log10(np.min(xplot)),np.log10(np.max(xplot)),10)
>   File "/home/shulevski/lofar_local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2397, in amin
>     out=out, **kwargs)
>   File "/home/shulevski/lofar_local/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
>     return umr_minimum(a, axis, None, out, keepdims)
> ValueError: zero-size array to reduction operation minimum which has no identity
> 

And even though it is an error, the pipeline finishes and reports that it has finished successfully.

**Comment by amisk** [comment]
Hi,

I also encountered this error now. Curiously, on another machine, where a newer software version is installed, it apparently does not have this error. Altough it works on a different timestamp. I had to split it into single timesteps due to disk space limitations.
