### ISSUE TITLE
Pre-Facet-Cal.parset msout.writefullresflag= False should be used

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#9]
We should run NDPPP in the step below from Pre-Facet-Cal.parset with the option msout.writefullresflag= False

(this blows up the data unnecessarily and just eats disks space).

I think it is just a matter of adding:

dpppaverage.argument.msout.writefullresflag = false

Reinout

dpppaverage.control.type                 = dppp
dpppaverage.control.max_per_node         = 12                   # \ feel free to adjust these two values to match your system
dpppaverage.control.environment          = {OMP_NUM_THREADS: 4} # / they should be reasonable for CEP3
dpppaverage.control.error_tolerance      = {{ error_tolerance }}
dpppaverage.argument.msin                = ndppp_prep_target.output.mapfile  # The input data.
dpppaverage.argument.msin.datacolumn     = CORRECTED_DATA
dpppaverage.argument.msout.datacolumn    = DATA
dpppaverage.argument.steps               = [count,flag,count,avg]
dpppaverage.argument.flag.type           = aoflagger
dpppaverage.argument.flag.keepstatistics = false
dpppaverage.argument.flag.memoryperc     = 10
dpppaverage.argument.flag.strategy       = {{ flagging_strategy }}
dpppaverage.argument.avg.type            = average
dpppaverage.argument.avg.timestep        = {{ avg_timestep }}       # average to 8 second intervals , PLEASE ADJUST!
dpppaverage.argument.avg.freqstep        = {{ avg_freqstep }}       # average to 2 ch/SB , PLEASE ADJUST!

**Comment by AHorneffer** [comment]
I didn't find any reason why it should be set to true. So I can include that.

Is there a reason not to include that in all calls to NDPPP (that are not "inplace")?

**Comment by tammojan** [comment]
The flag only has an effect when averaging data.

**Comment by rvweeren** [comment]
This msout.writefullresflag option was included such that one could explicitly compute the time and bandwidth smearing when averaging (this depends the properties on the FLAG column). We never use that info though.

**Comment by AHorneffer** [comment]
O.K. Done.
