### ISSUE TITLE
give starting subband in the concat

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#90]
For the surveys we are processing 10subbands at a time on a node. In the concat step if the first subband is missing then only 9 subbands go into the concat step and this step doesnt know whether to add a dummy ms on the start or end. A solution (suggested by Andreas) is giving the starting subband as an input into the concat step.

**Comment by AHorneffer** [comment]
Well, in the "experimental" branch there is now an option `firstSB` for the `sortmap_target` step in Pre-Facet-Target.parset. It is the station subband number (i.e. 0 -> 100MHz; 55 -> 110.74MHz; 512 -> 200MHz) used to reference the grouping of the files.

Please let me know if that works.

**Comment by twshimwell** [comment]
Excellent. I will test this.

Just for reference I think that this is the site that converts absolute subband to frequency https://proxy.lofar.eu/rtsm/tests/  (shame the absolute subband isn't used in the filename).

Many thanks Andreas!

**Comment by AHorneffer** [comment]
WTF? Why should I need a webpage for: `SBnum/512.*100+100`?

**Comment by twshimwell** [comment]
Its not a bad webpage, whilst we don't need them here it has other features besides SBnum/512.*100+100  that can be handy for people.

Anyway, I think line 215 of sortmap_target should be:

 if np.min(freqliste) < minfreq:

Also fgroup on line 258 is undefined. I think this should be groupIdx?

After making those small changes though it seems to work and the frequency coverage is as expected. 

For the test I removed the first subband in a 10 subband group and in the final concat file the frequency of the missing subband was included in the CHAN_FREQ. A minor thing is that doesnt really matter is that the concat filename did not use the missing frequency band name but the first subband in the ones that actually existed.

Thanks

**Comment by AHorneffer** [comment]
> Anyway, I think line 215 of sortmap_target should be:
> 
> if np.min(freqliste) < minfreq:

Yupp.

> Also fgroup on line 258 is undefined. I think this should be groupIdx?

Nope. That was copy&paste of old code, that I needed to change a bit more...

**Comment by AHorneffer** [comment]
> A minor thing (that doesnt really matter in terms of the actual data) is that the concat filename did not use the missing frequency band name but the first subband in the ones that actually existed.

How the *bleeep* am I supposed to figure out the name of a non-existing file?

If you want code that makes assumptions about file names, then feel free to use prefactor version 1.

**Comment by twshimwell** [comment]
Ah yes I was thinking to extrapolate back the subband names but yeh not a good idea as subbands are not necessarily uniformly spaced in freq

**Comment by twshimwell** [comment]
I testing the new code after the fixes and it works for me so this seems all done which is good. Would be great if this could be merged into the master branch.

**Comment by AHorneffer** [comment]
Done
