### ISSUE TITLE
Add handling of international baselines

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#92]
Some handling of the international baselines could/should be included, e.g.:
- calibration of core / Dutch stations (from calibrator obs?)
- phasing up of the superterp
- conversion to circular?

**Comment by adrabent** [comment]
This is done by the Long  Baseline Pipeline version of the pipeline:

https://github.com/lmorabit/long_baseline_pipeline/blob/master/long_baseline_pipeline.parset
