### ISSUE TITLE
Investigate weighting of visibilities

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#93]
For the LBA the WEIGHT_SPECTRUM is not optimal. This will be similar on the HBA and perhaps should be made more optimal in the prefactor pipeline.

Francesco suggested this issue is due to:

The calculation of the weights is presently done with 1/autocorr which is correct in a time/freq cell but might fail when a longer time/freq chunk of data is used. 

The solution he suggested was:

Update the weights with the updateweight=True in NDPPP in two steps: 1. when applying the bandpass (correct for the freq-dep) and 2. when applying the element beam (correct for the time-dep). Alternatively the weights have to be recalculated after the major amplitude corrections are applied.

**Comment by AHorneffer** [comment]
So essentially just set `updateweights=True`  in the `applygain` and `applybeam` steps of the `ndppp_prep_target` step of the target pipeline?

**Comment by tammojan** [comment]
Yes.

**Comment by AHorneffer** [comment]
Hmmm... that will take some time to implement.

**Comment by twshimwell** [comment]
Is testing required or is it clear this won't cause any issues?

**Comment by AHorneffer** [comment]
Testing is always required!
But I don't think this is likely to break things enough that I had doubts to commit the change.

Another question: From the documentation of NDPPP it seems to me that `updateweights=True` is only needed in the last  step that changes the amplitudes. (Because it makes the weights inverse proportional to the autocorrelations.) Is that correct?

**Comment by tammojan** [comment]
> Another question: From the documentation of NDPPP it seems to me that updateweights=True is only needed in the last step that changes the amplitudes. (Because it makes the weights inverse proportional to the autocorrelations.) Is that correct?

No. Only `autoweight=true` does the thing with the autocorrelations. When you correct for instrument tables or a beam, the correction is used for correcting the weight. See http://www.lofar.org/operations/lib/exe/fetch.php?media=commissioning:bw19tammo.pdf

**Comment by AHorneffer** [comment]
Hmmm... The slides (well, slide 8) don't really tell what you are doing with the weights. (E.g. where do you get **C**? I guess it is `1/weights`, but it doesn't say so.)

Anyhow, would it be correct to change the documentation on the NDPPP wiki to:
> Update the weights column, in a way consistent with the weights being inverse proportional to the autocorrelations (e.g. if 'autoweights' was used before).

**Comment by AHorneffer** [comment]
I took the liberty to update the NDPPP wiki page.

Please re-open if you think we need to discuss this further.
