### ISSUE TITLE
phase calibration solution interval

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#94]
With the phase calibration solution interval we presently have:

gsmcal_solve.argument.gaincal.solint                  = 1

However, the integration time used by people varies a little (maybe from 4 to 10 secs). Maybe the solint should be varied to always be about the same amount of time? (perhaps we want about 8-10 secs).

**Comment by AHorneffer** [comment]
I guess we'll add that when we implement specifying the output resolution: #66

**Comment by adrabent** [comment]
This is now handled properly.
