### ISSUE TITLE
'Band' object has no attribute timestep_sec  -- initial subtract pipelines

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#95]
The initsubtract_deep_sort_and_compute does:

(freqstep,timestep) = bands[0].get_averaging_steps()

to get the time and frequency averaging of the first data band (assumed the same for all bands). However, in the following loop over bands the band.nwavelength looks for self.timestep_sec which only has been set for bands[0] so for bands[1] it fails.

(hopefully this makes sense)

Anyway, a solution is that in the loop over bands we put:

band.get_averaging_steps() 

so that self.timestep_sec is defined for all bands.

**Comment by wllwen007** [comment]
I think I fixed this... https://github.com/lofar-astron/prefactor/commit/373faa2a2c21d866d3fc1e9acc2da869d7a9944b

**Comment by twshimwell** [comment]
Ah ok, your fix was nicer than my one. I have put this in the master branch too (as presently it just crashes  without it)
