### ISSUE TITLE
support.utilities.spawn_process is DEPRECATED

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#98]
This needs to be fixed somewhere in the guts of the pipeline framework. I started an issue on the issure tracker at: https://support.astron.nl/lofar_issuetracker/issues/9996

**Comment by AHorneffer** [comment]
I guess with the message not showing up as an error anymore, we can put this issue to rest.

**Comment by nudomarinero** [comment]
Yes, it has been already patched in LOFAR (https://support.astron.nl/lofar_issuetracker/issues/9996)
